import type { SwipeCard } from '../cyklusTypes';

export const CRISIS_CARDS: Record<string, SwipeCard> = {


  // ── CRISIS (8) ──────────────────────────────────────────────────────────────
  crisis_energy_depletion: {
    id: 'crisis_energy_depletion',
    title: 'Vyčerpání',
    logLabel: 'CRISIS',
    scene: 'Systém varuje, že jsi téměř prázdný. Můžeš se rozpadnout, nebo někoho jiného vyždímat.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [CRISIS/ENERGY_LOW]:</span> výkon subjektu klesl pod hranici důstojného rozpadu.</p><p class="text">Světlo kolem tebe slábne. Ne dramaticky. Jen účinně. Každý krok má hmotnost mokré deky a i vlastní stín vypadá, že by si nejraději sedl a podal stížnost.</p><p class="text"><span class="fx-outline hollow">Energie</span> není pryč úplně. Jen se tváří, že tě nezná. Velmi dospělé.</p>`,
    sceneFx: ['scene-crisis', 'scene-energy-low', 'scene-danger'],
    yesLabel: 'SLEPIT SE',
    noLabel: 'PŘIPOJIT SE K JINÉMU',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statBelow', stat: 'energy', value: 25 }],
    tags: ['crisis', 'energy', 'danger'],
    yes: { resultText: 'Slepil ses zbytky. Nebylo to elegantní, ale bylo to tvoje.', effects: [{ type: 'stat', key: 'energy', amount: 8 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'T', amount: 1 }], preview: { hint: 'Energie ↑ · Vazba ↓ · Kontrola ↓', statHints: { energy: 'up', bond: 'down', control: 'down' }, risk: 'high' } },
    no: { resultText: 'Připojil ses k někomu jinému. Na chvíli jste byli jedním systémem. Potom ti utekl.', effects: [{ type: 'stat', key: 'energy', amount: 10 }, { type: 'stat', key: 'bond', amount: -6 }, { type: 'stat', key: 'control', amount: -6 }, { type: 'profile', key: 'E', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Energie ↑↑ · Vazba ↓ · Kontrola ↓', statHints: { energy: 'up', bond: 'down', control: 'down' }, risk: 'high' } },
  },

  crisis_energy_overload: {
    id: 'crisis_energy_overload',
    title: 'Přepětí',
    logLabel: 'CRISIS',
    scene: 'Energie máš tolik, že věci kolem tebe začínají hořet. Sám taky.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [CRISIS/ENERGY_OVERLOAD]:</span> subjekt generuje víc světla, než zvládá přežít.</p><p class="text">Hrany světa začnou hořet žlutě. Pod kůží se ti rozběhne <span class="fx-flicker">přepětí</span>, rychlé, krásné a úplně hloupé, jako každý nápad, který vypadá skvěle dvě vteřiny před pádem.</p><p class="dialogS">„Výborně. Teď jsi emocionální žárovka v místnosti plné benzínu.“</p>`,
    sceneFx: ['scene-crisis', 'scene-energy', 'scene-acid', 'scene-danger'],
    yesLabel: 'VYPUSTIT',
    noLabel: 'UŽÍT SI',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statAbove', stat: 'energy', value: 75 }],
    tags: ['crisis', 'energy', 'danger'],
    yes: { resultText: 'Vypustil jsi přebytek do systému. Systém si na chvíli myslel, že je slunce.', effects: [{ type: 'stat', key: 'energy', amount: -10 }, { type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'control', amount: 4 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Fi', amount: 1 }], preview: { hint: 'Energie ↓↓ · Vazba ↑ · Kontrola ↑', statHints: { energy: 'down', bond: 'up', control: 'up' }, risk: 'high' } },
    no: { resultText: 'Užil sis to. Hořelo. Byl jsi to ty.', effects: [{ type: 'stat', key: 'energy', amount: 8 }, { type: 'stat', key: 'control', amount: -8 }, { type: 'stat', key: 'memory', amount: -6 }, { type: 'profile', key: 'Se', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Energie ↑ · Kontrola ↓ · Paměť ↓', statHints: { energy: 'up', control: 'down', memory: 'down' }, risk: 'high' } },
  },

  crisis_memory_loss: {
    id: 'crisis_memory_loss',
    title: 'Ztráta paměti',
    logLabel: 'CRISIS',
    scene: 'Velká část paměti je nedosažitelná. Zapomněl jsi, proč jsi zapomněl.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [CRISIS/MEMORY_LOSS]:</span> indexy paměti vrací prázdné rámečky.</p><p class="text">Některé vzpomínky se neztratily. Jen odpojily zvonek a dělají, že nejsou doma. V hlavě zůstaly bílé obdélníky, tiché jako fotografie vytržené z alba.</p><p class="text">Zapomněl jsi důvod. Pak i otázku. A systém se tváří, že to je úspora místa. Kdyby měl ruce, třídil by tě do krabic.</p>`,
    sceneFx: ['scene-crisis', 'scene-memory-low', 'scene-void'],
    yesLabel: 'PŘIJMOUT',
    noLabel: 'REKONSTRUOVAT',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statBelow', stat: 'memory', value: 25 }],
    tags: ['crisis', 'memory', 'danger'],
    yes: { resultText: 'Přijal jsi díru. Stala se oknem. Přes ni šel vítr, ale taky světlo.', effects: [{ type: 'stat', key: 'memory', amount: 6 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'stat', key: 'control', amount: 2 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Paměť ↑ · Vazba ↓', statHints: { memory: 'up', bond: 'down' }, risk: 'high' } },
    no: { resultText: 'Rekonstruoval jsi. Paměť si vzpomněla, ale jinak, než bylo. Některé lži jsou přijemné.', effects: [{ type: 'stat', key: 'memory', amount: 10 }, { type: 'stat', key: 'energy', amount: -6 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Paměť ↑↑ · Energie ↓ · Vazba ↓', statHints: { memory: 'up', energy: 'down', bond: 'down' }, risk: 'high' } },
  },

  crisis_memory_flood: {
    id: 'crisis_memory_flood',
    title: 'Povodeň vzpomínek',
    logLabel: 'CRISIS',
    scene: 'Paměť se ti hroutí na hlavu. Všechno najednou. Včetně věcí, které nejsou tvoje.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [CRISIS/MEMORY_FLOOD]:</span> archivní hladina překročila subjekt.</p><p class="text">Vzpomínky se nevynoří. Ony se vylijí. Zdi prasknou a dovnitř se nahrne dětský smích, cizí rozchod, starý pach deště, vina bez majitele a tři věty, které nikdo nikdy neposlal.</p><p class="text"><span class="fx-glow-magenta">Všechno je najednou tvoje</span>, což je přesně ten druh lži, na kterém paměť nejraději staví města.</p>`,
    sceneFx: ['scene-crisis', 'scene-memory', 'scene-archive', 'scene-danger'],
    yesLabel: 'PLAVAT',
    noLabel: 'UTÉCT NA STŘECHU',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statAbove', stat: 'memory', value: 75 }],
    tags: ['crisis', 'memory', 'danger'],
    yes: { resultText: 'Plaval jsi v pamětech. Některé tě obejmuly, některé utopily. Ale plaval jsi.', effects: [{ type: 'stat', key: 'memory', amount: -8 }, { type: 'stat', key: 'bond', amount: 6 }, { type: 'stat', key: 'energy', amount: -4 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Paměť ↓ · Vazba ↑ · Energie ↓', statHints: { memory: 'down', bond: 'up', energy: 'down' }, risk: 'high' } },
    no: { resultText: 'Utekl jsi na střechu. Příjemné. Osamělé. Až voda opadá, budeš mít odsud výhled na jiný svět.', effects: [{ type: 'stat', key: 'control', amount: 8 }, { type: 'stat', key: 'memory', amount: -6 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'Ti', amount: 1 }], preview: { hint: 'Kontrola ↑ · Paměť ↓ · Vazba ↓', statHints: { control: 'up', memory: 'down', bond: 'down' }, risk: 'medium' } },
  },

  crisis_bond_abandonment: {
    id: 'crisis_bond_abandonment',
    title: 'Opuštění',
    logLabel: 'CRISIS',
    scene: 'Vazba je tak tenká, že slyšíš, jak kolem tebe prochází všechno, co tě nepotřebuje.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [CRISIS/BOND_LOW]:</span> vazební vlákna hlásí chlad a odchod.</p><p class="text">Kolem tebe prochází všechno, co tě nepotřebuje. Dveře se zavírají tiše, zprávy zůstávají bez odpovědi a <span class="fx-outline hollow">vazba</span> je tenká jako nit, kterou už někdo dávno přestal držet.</p><p class="text">Opuštění není výbuch. Je to servisní hláška světa: „subjekt není připojen“.</p>`,
    sceneFx: ['scene-crisis', 'scene-bond-low', 'scene-bond', 'scene-danger'],
    yesLabel: 'DRŽET SE',
    noLabel: 'POVOLIT',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statBelow', stat: 'bond', value: 25 }],
    tags: ['crisis', 'bond', 'danger'],
    yes: { resultText: 'Držel ses. I když to druhé straně možná připadalo divné, že se držíš vzduchu.', effects: [{ type: 'stat', key: 'bond', amount: 6 }, { type: 'stat', key: 'energy', amount: -4 }, { type: 'stat', key: 'control', amount: -3 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Fe', amount: 1 }], preview: { hint: 'Vazba ↑ · Energie ↓ · Kontrola ↓', statHints: { bond: 'up', energy: 'down', control: 'down' }, risk: 'high' } },
    no: { resultText: 'Povolil jsi. Cítil jsi, jak se svět odtahuje. Bylo to tiché. Bylo to osvobozující.', effects: [{ type: 'stat', key: 'bond', amount: -8 }, { type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'energy', amount: 4 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'Ti', amount: 1 }], preview: { hint: 'Vazba ↓↓ · Kontrola ↑ · Energie ↑', statHints: { bond: 'down', control: 'up', energy: 'up' }, risk: 'high' } },
  },

  crisis_bond_suffocation: {
    id: 'crisis_bond_suffocation',
    title: 'Udušení vazbami',
    logLabel: 'CRISIS',
    scene: 'Vazba je tak silná, že každý pohyb tě táhne ke kompromisu. Můžeš se oddálit, nebo zlomit.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [CRISIS/BOND_OVERLOAD]:</span> vazba překročila hranici podpory a přešla do majetkového režimu.</p><p class="text">Vlákna vazeb se kolem tebe stáhnou jako teplá síť. Není to studené. To je na tom právě hnusně chytré. Dusí tě něco, co voní po domově.</p><p class="text"><span class="halo">Blízkost</span> se tváří jako spása, ale její prsty už hledají, kde máš vypínač.</p>`,
    sceneFx: ['scene-crisis', 'scene-bond-high', 'scene-bond', 'scene-danger'],
    yesLabel: 'ODDÁLIT SE',
    noLabel: 'POVOLIT',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statAbove', stat: 'bond', value: 75 }],
    tags: ['crisis', 'bond', 'danger'],
    yes: { resultText: 'Oddálil ses. Bolelo to. Ale zase jsi slyšel svůj vlastní tep.', effects: [{ type: 'stat', key: 'bond', amount: -10 }, { type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'memory', amount: 4 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'T', amount: 1 }], preview: { hint: 'Vazba ↓↓ · Kontrola ↑ · Paměť ↑', statHints: { bond: 'down', control: 'up', memory: 'up' }, risk: 'high' } },
    no: { resultText: 'Povolil jsi. Vazba se usmála. Možná to byl úsměv, možná to bylo vítězství. Těžko říct.', effects: [{ type: 'stat', key: 'bond', amount: 6 }, { type: 'stat', key: 'control', amount: -6 }, { type: 'stat', key: 'energy', amount: -4 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Fe', amount: 1 }], preview: { hint: 'Vazba ↑ · Kontrola ↓ · Energie ↓', statHints: { bond: 'up', control: 'down', energy: 'down' }, risk: 'high' } },
  },

  crisis_control_breakdown: {
    id: 'crisis_control_breakdown',
    title: 'Kontrola se rozpadá',
    logLabel: 'CRISIS',
    scene: 'Kontrola je tak nízká, že se ti i stíny posmívají. Někdo se zasměje a ty slyšíš vlastní hlas.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [CRISIS/CONTROL_LOSS]:</span> řídicí vrstva subjektu se směje vlastnímu pádu.</p><p class="text">Kontrola se rozpadne nejdřív na drobnosti. Křivý dech. Špatně dlouhý stín. Věta, která se ti rozběhne z úst dřív, než ji stihneš zatknout.</p><p class="dialogS">„Dobrá zpráva: už to neřídíš. Špatná zpráva: ono se to řídí samo a má to tvůj rukopis.“</p>`,
    sceneFx: ['scene-crisis', 'scene-control-low', 'scene-glitch', 'scene-danger'],
    yesLabel: 'PŘIZNAT',
    noLabel: 'BOJOVAT',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statBelow', stat: 'control', value: 25 }],
    tags: ['crisis', 'control', 'danger'],
    yes: { resultText: 'Přiznal jsi, že nemáš kontrolu. To bylo poprvé, co se věci začaly ukládat na správné místo.', effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'energy', amount: -4 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↑ · Energie ↓', statHints: { control: 'up', bond: 'up', energy: 'down' }, risk: 'high' } },
    no: { resultText: 'Bojoval jsi. Prohrál jsi. Ale prohrál jsi se ctí, což si systém zapamatoval jako kód chyby.', effects: [{ type: 'stat', key: 'control', amount: -6 }, { type: 'stat', key: 'energy', amount: 6 }, { type: 'stat', key: 'memory', amount: -4 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↓ · Energie ↑ · Paměť ↓', statHints: { control: 'down', energy: 'up', memory: 'down' }, risk: 'high' } },
  },

  crisis_control_tyranny: {
    id: 'crisis_control_tyranny',
    title: 'Tyranie kontroly',
    logLabel: 'CRISIS',
    scene: 'Kontrola je tak vysoká, že všechno kolem tebe dýchá synchroně. Můžeš to rozbít, nebo vládnout.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [CRISIS/CONTROL_TYRANNY]:</span> stabilita překročila práh života.</p><p class="text">Všechno kolem tebe dýchá synchronně. Kroky, světla, zdi, myšlenky. Dokonalý pořádek. Dokonalé ticho. Dokonalá malá totalita, která si říká disciplína, protože tyranie má ráda hezká slova.</p><p class="text"><span class="fx-outline is-lit">Kontrola</span> konečně vyhrála. Teď už jen zbývá zjistit, koho vlastně porazila.</p>`,
    sceneFx: ['scene-crisis', 'scene-control-high', 'scene-control', 'scene-danger'],
    yesLabel: 'ROZBÍT',
    noLabel: 'VLÁDNOUT',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statAbove', stat: 'control', value: 75 }],
    tags: ['crisis', 'control', 'danger'],
    yes: { resultText: 'Rozbil jsi to. Věci se vrátily do náhodného, ale upřímného stavu.', effects: [{ type: 'stat', key: 'control', amount: -10 }, { type: 'stat', key: 'energy', amount: 8 }, { type: 'stat', key: 'bond', amount: 4 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Ne', amount: 1 }], preview: { hint: 'Kontrola ↓↓ · Energie ↑ · Vazba ↑', statHints: { control: 'down', energy: 'up', bond: 'up' }, risk: 'high' } },
    no: { resultText: 'Vládl jsi. Všechno se ti klanělo. Bylo to tiché, bylo to pusté, bylo to tvoje.', effects: [{ type: 'stat', key: 'control', amount: 8 }, { type: 'stat', key: 'bond', amount: -8 }, { type: 'stat', key: 'memory', amount: -6 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓ · Paměť ↓', statHints: { control: 'up', bond: 'down', memory: 'down' }, risk: 'high' } },
  },


  system_overheat: {
    id: 'system_overheat',
    title: 'Systém se přehřívá',
    logLabel: 'SYSTEM_OVERHEAT',
    scene: 'Teplota systému překročila bezpečnou mez. Systém navrhuje paniku. Aspoň je tentokrát upřímný, ta malá přehřátá tragédie.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [SYSTEM_OVERHEAT]:</span> teplota reality překročila bezpečnou mez.</p><p class="text">Stěny začnou dýchat horkem. Neon se roztáhne do žlutých skvrn a hrany prostoru měknou, jako by se realita rozhodla stát levnou svíčkou.</p><p class="text"><span class="fx-flicker">PANIKA DOPORUČENA</span> bliká na stropě. Když systém doporučí paniku, je to skoro roztomilé. Jako požár s procedurou.</p><p class="dialogS">„Chladit, nebo přidat výkon. Dvě volby, jedna civilizační diagnóza.“</p>`,
    sceneFx: ['scene-crisis', 'scene-energy', 'scene-overheat'],
    yesLabel: 'CHLADIT',
    noLabel: 'PŘIDAT VÝKON',
    category: 'crisis',
    rarity: 'critical',
    cooldownTurns: 8,
    tags: ['crisis', 'energy', 'system'],
    yes: {
      resultText: 'Začal jsi chladit. Šum syčel, jako když někdo hasí malý osobní vesmír.',
      effects: [
        { type: 'stat', key: 'energy', amount: -14 },
        { type: 'stat', key: 'control', amount: 5 },
        { type: 'profile', key: 'J', amount: 1 },
        { type: 'profile', key: 'Ti', amount: 1 },
      ],
      preview: { hint: 'Energie ↓↓ · Kontrola ↑', statHints: { energy: 'down', control: 'up' }, risk: 'medium' },
    },
    no: {
      resultText: 'Přidal jsi výkon. Na chvíli to bylo nádherné. Pak drahé. Pak hlučné. Pak už jen tvoje.',
      effects: [
        { type: 'stat', key: 'energy', amount: 14 },
        { type: 'stat', key: 'control', amount: -10 },
        { type: 'unlockPool', poolId: 'acid_pool' },
        { type: 'profile', key: 'Se', amount: 2 },
      ],
      preview: { hint: 'Energie ↑↑ · Kontrola ↓↓ · Acid pool', statHints: { energy: 'up', control: 'down' }, risk: 'high' },
    },
  },


  audit_siren: {
    id: 'audit_siren',
    title: 'Auditní siréna',
    logLabel: 'AUDIT_SIREN',
    scene: 'Spustila se auditní siréna. Zní jako tiskárna, která se naučila soudit.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [AUDIT/SIREN]:</span> spuštěna kontrola smyslu. Doporučení: nebýt nalezen jako příloha.</p><p class="text">Spustila se auditní siréna. Zní jako tiskárna, která se naučila soudit, a pak získala pravomoc. Stěny Formulářovny se otevřou do šanonů, šanony do chodeb a chodby do drobných políček s tvým jménem napsaným špatně.</p><p class="text">Razítka začnou padat ze stropu jako úřední kroupy. Každé z nich hledá místo, kam tě označit.</p><p class="dialogS">„Schovat se za razítko je zoufalé. Utéct před auditem taky. Aspoň máme konzistentní ponížení.“</p>`,
    sceneFx: ['scene-crisis', 'scene-form', 'scene-office', 'scene-audit'],
    yesLabel: 'SCHOVAT SE ZA RAZÍTKO',
    noLabel: 'UTÉCT',
    category: 'crisis',
    rarity: 'critical',
    cooldownTurns: 8,
    tags: ['crisis', 'form', 'office', 'trap'],
    yes: {
      resultText: 'Schoval ses za razítko. Bylo malé, gumové a absurdně autoritativní. Audit chvíli nevěděl, koho má šikanovat.',
      effects: [
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'stat', key: 'energy', amount: -4 },
        { type: 'profile', key: 'J', amount: 1 },
        { type: 'profile', key: 'Te', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Utekl jsi. Audit běžel za tebou. Má razítka, tabulky a kardio překvapivě dobré na papír.',
      effects: [
        { type: 'stat', key: 'energy', amount: 8 },
        { type: 'stat', key: 'control', amount: -10 },
        { type: 'moveSector', sectorId: 'void' },
        { type: 'profile', key: 'Se', amount: 2 },
      ],
      preview: { hint: 'Energie ↑↑ · Kontrola ↓↓ · návrat do Prázdnoty', statHints: { energy: 'up', control: 'down' }, risk: 'high' },
    },
  },



    // ── CRISIS CARDS ─────────────────────────────────────────────────────────────

  energy_dim_light: {
    id: 'energy_dim_light',
    title: 'Světlo ztrácí důvod',
    logLabel: 'ENERGY_LOW',
    scene: 'Světlo nezhaslo. Jen přestalo věřit, že má důvod svítit.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [ENERGY/LOW]:</span> světlo ztratilo motivaci. Subjektu doporučeno najít jiskru nebo si zvyknout na tmu s komentářem.</p><p class="text">Světlo nezhaslo. Jen přestalo věřit, že má důvod svítit. Neonové linky ve zdech poblikávají líně, jako by je někdo platil podle smutku.</p><p class="text">Tvoje kroky jsou těžší. Ne proto, že by se změnila gravitace. Spíš proto, že svět najednou čeká, jestli si sám dokážeš vyrobit aspoň malou jiskru. Hnusná forma důvěry.</p><p class="dialogS">„Rozfoukat jiskru, nebo elegantně zhasnout. Dvě možnosti, obě s poetickou závadou.“</p>`,
    sceneFx: ['scene-crisis', 'scene-energy-low', 'scene-dim', 'scene-light'],
    yesLabel: 'ROZFOUKAT JISKRU',
    noLabel: 'ZŮSTAT POTICHU',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statBelow', stat: 'energy', value: 22 }],
    tags: ['crisis', 'energy', 'low'],
    yes: {
      resultText: 'Rozfoukal jsi jiskru. Nebyla velká. Ale měla drzost pokračovat.',
      effects: [
        { type: 'stat', key: 'energy', amount: 14 },
        { type: 'stat', key: 'control', amount: -5 },
        { type: 'profile', key: 'Se', amount: 1 },
      ],
      preview: { hint: 'Energie ↑↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Zůstal jsi potichu. Ticho si tě začalo zkoušet jako kabát.',
      effects: [
        { type: 'stat', key: 'energy', amount: -8 },
        { type: 'stat', key: 'bond', amount: -4 },
        { type: 'entityRelation', entity: 'shadow', delta: 2 },
        { type: 'profile', key: 'I', amount: 1 },
      ],
      preview: { hint: 'Energie ↓ · Vazba ↓', statHints: { energy: 'down', bond: 'down' }, risk: 'high' },
    },
  },


  energy_too_fast: {
    id: 'energy_too_fast',
    title: 'Všechno běží moc rychle',
    logLabel: 'ENERGY_HIGH',
    scene: 'Všechno běží. Tvoje ruce. Tvoje myšlenky. I věci, které by podle dokumentace ruce mít neměly.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [ENERGY/HIGH]:</span> procesy překročily bezpečnou rychlost. Myšlenky předbíhají tělo a tváří se kompetentně.</p><p class="text">Všechno běží. Tvoje ruce. Tvoje myšlenky. I věci, které by podle dokumentace ruce mít neměly. Okraje místnosti se protahují do ostrých čar a každá z nich tvrdí, že ví, kam máš jít.</p><p class="text">Energie není síla, když nemá směr. Je to jen panika v neonovém obalu. Velkolepé, drahé a použitelné asi jako motor přivařený k posteli.</p><p class="dialogS">„Předběhnout sám sebe je krásná ambice. Jen škoda, že cílová páska bývá stěna.“</p>`,
    sceneFx: ['scene-crisis', 'scene-energy-high', 'scene-overheat', 'scene-speed'],
    yesLabel: 'ZPOMALIT',
    noLabel: 'PŘEDBĚHNOUT SÁM SEBE',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statAbove', stat: 'energy', value: 82 }],
    tags: ['crisis', 'energy', 'high'],
    yes: {
      resultText: 'Zpomalil jsi. Některé myšlenky do tebe narazily zezadu. Bylo to trapné, ale přežitelné.',
      effects: [
        { type: 'stat', key: 'energy', amount: -14 },
        { type: 'stat', key: 'control', amount: 5 },
        { type: 'profile', key: 'Si', amount: 1 },
      ],
      preview: { hint: 'Energie ↓↓ · Kontrola ↑', statHints: { energy: 'down', control: 'up' }, risk: 'medium' },
    },
    no: {
      resultText: 'Předběhl jsi sám sebe. Chvíli jsi viděl vlastní záda. Pak už jen varování.',
      effects: [
        { type: 'stat', key: 'energy', amount: 10 },
        { type: 'stat', key: 'control', amount: -8 },
        { type: 'unlockPool', poolId: 'acid_pool' },
        { type: 'profile', key: 'Se', amount: 2 },
      ],
      preview: { hint: 'Energie ↑ · Kontrola ↓↓ · Acid pool', statHints: { energy: 'up', control: 'down' }, risk: 'high' },
    },
  },


  memory_empty_label: {
    id: 'memory_empty_label',
    title: 'Prázdný štítek',
    logLabel: 'MEMORY_LOW',
    scene: 'Na všech věcech jsou štítky. Jenže jsou prázdné. Svět je najednou perfektně uklizený a úplně k ničemu.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [MEMORY/LOW]:</span> indexy zůstaly, obsah odpadl. Výborně, archiv má popisky bez reality.</p><p class="text">Na každé věci visí štítek. Na židli. Na dveřích. Na vlastním zápěstí. Jenže všechny jsou prázdné, čisté a poslušné jako formulář před katastrofou.</p><p class="text"><span class="fx-outline hollow">Paměť</span> se nevymazala nahlas. Jen přestala dodávat názvy. Což je elegantní způsob, jak z člověka udělat sklad bez mapy.</p><p class="dialogS">„Když nevíš, jak se něco jmenuje, můžeš to pořád ztratit. Jen u toho budeš působit méně kompetentně.“</p>`,
    sceneFx: ['scene-crisis', 'scene-memory-low', 'scene-label', 'scene-empty'],
    yesLabel: 'DOPSAT NÁZVY',
    noLabel: 'NECHAT PRÁZDNO',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statBelow', stat: 'memory', value: 22 }],
    tags: ['crisis', 'memory', 'low'],
    yes: {
      resultText: 'Dopsal jsi názvy. Některé byly špatně. Ale špatné jméno je pořád víc než žádné.',
      effects: [
        { type: 'stat', key: 'memory', amount: 14 },
        { type: 'stat', key: 'control', amount: -4 },
        { type: 'profile', key: 'Si', amount: 1 },
        { type: 'profile', key: 'N', amount: 1 },
      ],
      preview: { hint: 'Paměť ↑↑ · Kontrola ↓', statHints: { memory: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Nechal jsi prázdno. Prázdno se roztáhlo. Vždycky čekalo na pozvání, drzoun.',
      effects: [
        { type: 'stat', key: 'memory', amount: -8 },
        { type: 'stat', key: 'control', amount: 4 },
        { type: 'profile', key: 'T', amount: 1 },
      ],
      preview: { hint: 'Paměť ↓ · Kontrola ↑', statHints: { memory: 'down', control: 'up' }, risk: 'high' },
    },
  },


  memory_flood: {
    id: 'memory_flood',
    title: 'Archivní povodeň',
    logLabel: 'MEMORY_HIGH',
    scene: 'Archiv přetekl. Vzpomínky se valí chodbou a každá tvrdí, že je ta nejdůležitější. Typické.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [MEMORY/HIGH]:</span> archivní hladina překročila práh sebeúcty.</p><p class="text">Chodbou se valí vzpomínky. Ne jako voda. Voda aspoň nevypráví, proč má pravdu. Každý fragment křičí, že je klíčový, poslední, základní, neodložitelný.</p><p class="text">Archiv nemá povodeň. Archiv má <span class="fx-glow-magenta">přebytek významu</span>. A význam, když ho nikdo neřídí, se chová jako dav v hořícím divadle.</p><p class="dialogS">„Gratuluju. Tvoje minulost se rozhodla založit odbory.“</p>`,
    sceneFx: ['scene-crisis', 'scene-memory-high', 'scene-archive', 'scene-flood'],
    yesLabel: 'OTEVŘÍT STAVIDLA',
    noLabel: 'ZABEDNIT DVEŘE',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statAbove', stat: 'memory', value: 82 }],
    tags: ['crisis', 'memory', 'high', 'archive', 'memory_flood', 'archive_pattern'],
    yes: {
      resultText: 'Otevřel jsi stavidla. Paměť odtekla. Ne všechna. Jen dost na to, abys zase dýchal.',
      effects: [
        { type: 'stat', key: 'memory', amount: -14 },
        { type: 'stat', key: 'energy', amount: -3 },
        { type: 'moveSector', sectorId: 'archive' },
        { type: 'profile', key: 'Ni', amount: 1 },
      ],
      preview: { hint: 'Paměť ↓↓ · Archiv', statHints: { memory: 'down', energy: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Zabednil jsi dveře. Vzpomínky začaly prosakovat klíčovou dírkou. Dramaticky. Neefektivně. Vytrvale.',
      effects: [
        { type: 'stat', key: 'memory', amount: 9 },
        { type: 'stat', key: 'control', amount: -7 },
        { type: 'schedule', cardId: 'memory_files_complaint', inTurns: 3 },
        { type: 'profile', key: 'J', amount: 1 },
      ],
      preview: { hint: 'Paměť ↑ · Kontrola ↓ · stížnost', statHints: { memory: 'up', control: 'down' }, risk: 'high' },
    },
  },


  bond_thin_signal: {
    id: 'bond_thin_signal',
    title: 'Signál se ztenčil',
    logLabel: 'BOND_LOW',
    scene: 'Signál k ostatním se ztenčil na jednu nit. Ještě drží. To je na ní nejhorší.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [BOND/LOW]:</span> signál vazby degradoval na poslední nit. Překvapivě ještě drží.</p><p class="text">Mezi tebou a zbytkem světa visí jediné vlákno. Tenké, napnuté, skoro směšné. Přesně takové, jaké lidé používají pro věci typu naděje, omluva a „ještě jsem to neposral úplně“.</p><p class="text">Na druhé straně se něco hýbe. Možná někdo. Možná jen ozvěna kontaktu, který byl kdysi živý a teď má otevírací dobu jako úřad.</p><p class="dialogS">„Jestli za to zatáhneš, může to bolet. Jestli ne, budeš tomu říkat klid, protože samota má skvělý marketing.“</p>`,
    sceneFx: ['scene-crisis', 'scene-bond-low', 'scene-thread', 'scene-isolation'],
    yesLabel: 'ZATÁHNOUT ZA NI',
    noLabel: 'PŘESTŘIHNOUT',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statBelow', stat: 'bond', value: 22 }],
    tags: ['crisis', 'bond', 'low', 'isolation_cards', 'empty_contacts', 'thread_cards'],
    yes: {
      resultText: 'Zatáhl jsi. Na druhé straně někdo zatáhl zpátky. Nebylo jasné kdo. Stačilo to.',
      effects: [
        { type: 'stat', key: 'bond', amount: 14 },
        { type: 'stat', key: 'energy', amount: -4 },
        { type: 'profile', key: 'Fe', amount: 1 },
      ],
      preview: { hint: 'Vazba ↑↑ · Energie ↓', statHints: { bond: 'up', energy: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Přestřihl jsi ji. Ticho bylo čisté. A přesně tak prázdné, jak sis myslel, že chceš.',
      effects: [
        { type: 'stat', key: 'bond', amount: -9 },
        { type: 'stat', key: 'control', amount: 5 },
        { type: 'entityRelation', entity: 'shadow', delta: 2 },
        { type: 'profile', key: 'I', amount: 1 },
      ],
      preview: { hint: 'Vazba ↓ · Kontrola ↑', statHints: { bond: 'down', control: 'up' }, risk: 'high' },
    },
  },


  bond_overflow: {
    id: 'bond_overflow',
    title: 'Příliš mnoho hlasů',
    logLabel: 'BOND_HIGH',
    scene: 'Všichni mluví najednou. Některé hlasy jsou tvoje. To situaci nijak nezlepšuje.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [BOND/HIGH]:</span> počet aktivních hlasů překročil hranici subjektu.</p><p class="text">Všichni mluví najednou. Prosí, radí, obviňují, milují, vysvětlují. Některé věty mají tvůj tón a cizí úmysl. Některé mají cizí tón a tvoji slabost.</p><p class="text"><span class="fx-outline is-lit">Vazba</span> přestala být mostem. Teď je to dav ve dveřích. A dav ve dveřích nikdy neřeší, jestli máš doma uklizeno.</p><p class="dialogS">„Blízkost je krásná. Až do chvíle, kdy ti začne nosit vlastní nábytek do lebky.“</p>`,
    sceneFx: ['scene-crisis', 'scene-bond-high', 'scene-overflow', 'scene-boundary'],
    yesLabel: 'NASTAVIT HRANICI',
    noLabel: 'PUSTIT JE DOVNITŘ',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statAbove', stat: 'bond', value: 82 }],
    tags: ['crisis', 'bond', 'high', 'dissolution', 'merge_cards'],
    yes: {
      resultText: 'Nastavil jsi hranici. Některé hlasy se urazily. Konečně důkaz, že hranice funguje.',
      effects: [
        { type: 'stat', key: 'bond', amount: -14 },
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'profile', key: 'Ti', amount: 1 },
        { type: 'profile', key: 'J', amount: 1 },
      ],
      preview: { hint: 'Vazba ↓↓ · Kontrola ↑', statHints: { bond: 'down', control: 'up' }, risk: 'medium' },
    },
    no: {
      resultText: 'Pustil jsi je dovnitř. Na chvíli to vypadalo jako láska. Pak jako invaze s lepším PR.',
      effects: [
        { type: 'stat', key: 'bond', amount: 9 },
        { type: 'stat', key: 'control', amount: -8 },
        { type: 'profile', key: 'Fe', amount: 2 },
      ],
      preview: { hint: 'Vazba ↑ · Kontrola ↓↓', statHints: { bond: 'up', control: 'down' }, risk: 'high' },
    },
  },


  control_unraveling: {
    id: 'control_unraveling',
    title: 'Rámec se rozplétá',
    logLabel: 'CONTROL_LOW',
    scene: 'Rámec se rozplétá. Rozhodnutí se začala dít sama. Některá mají znepokojivě dobré sebevědomí.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [CONTROL/LOW]:</span> rámec rozhodování ztratil uzly. Některé uzly podaly výpověď.</p><p class="text">Pravidla se rozplétají jako mokrý svetr. Dveře se rozhodují za tebe. Stíny chodí dřív než tvoje nohy. Myšlenky si berou dovolenou bez schválení.</p><p class="text">Kontrola nezmizela. Jen už není tvoje. To je drobný rozdíl, který systém považuje za administrativní detail a psychika za důvod k požáru.</p><p class="dialogS">„Dobrá zpráva: nemusíš nic řídit. Špatná zpráva: řídí to něco, co si plete svobodu s pádem ze schodů.“</p>`,
    sceneFx: ['scene-crisis', 'scene-control-low', 'scene-unravel', 'scene-collapse'],
    yesLabel: 'SVÁZAT RÁMEC',
    noLabel: 'NECHAT HO PADNOUT',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statBelow', stat: 'control', value: 22 }],
    tags: ['crisis', 'control', 'low', 'collapse_cards', 'post_collapse'],
    yes: {
      resultText: 'Svázal jsi rámec. Drží. Ošklivě, provizorně, ale drží. Což je někdy nejvyšší forma důstojnosti.',
      effects: [
        { type: 'stat', key: 'control', amount: 14 },
        { type: 'stat', key: 'energy', amount: -5 },
        { type: 'profile', key: 'J', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Nechal jsi ho padnout. Prázdnota zatleskala. Rukama, které ještě před chvílí neměla.',
      effects: [
        { type: 'stat', key: 'control', amount: -9 },
        { type: 'stat', key: 'energy', amount: 6 },
        { type: 'unlockPool', poolId: 'glitch_pool' },
        { type: 'profile', key: 'P', amount: 2 },
      ],
      preview: { hint: 'Kontrola ↓ · Energie ↑ · Glitch pool', statHints: { control: 'down', energy: 'up' }, risk: 'high' },
    },
  },


  control_crystal: {
    id: 'control_crystal',
    title: 'Všechno ztuhlo',
    logLabel: 'CONTROL_HIGH',
    scene: 'Všechno je přesné. Všechno je čisté. Všechno je mrtvě klidné. Kontrola konečně dostala, co chtěla, a tváří se překvapeně.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [CONTROL/HIGH]:</span> systém dosáhl dokonalé přesnosti. Život nebyl konzultován.</p><p class="text">Pokoj ztuhl. Hrany stolu jsou ideální. Prach se seřadil podle velikosti. I ticho stojí v pozoru, jako by prošlo školením pro nižší manažery.</p><p class="text"><span class="fx-outline is-lit">Kontrola</span> konečně vyhrála. Jenže vítězství bez pohybu vypadá podezřele podobně jako vitrína. Čistá. Bezpečná. Nepoužitelná.</p><p class="dialogS">„Perfektní. Jsi stabilní jako socha. Teď už jen vyřešit, že sochy obvykle nežijí.“</p>`,
    sceneFx: ['scene-crisis', 'scene-control-high', 'scene-crystal', 'scene-stillness'],
    yesLabel: 'POVOLIT SEVŘENÍ',
    noLabel: 'ZATVRDIT SE',
    category: 'crisis',
    rarity: 'critical',
    conditions: [{ type: 'statAbove', stat: 'control', value: 82 }],
    tags: ['crisis', 'control', 'high', 'crystal_cards', 'statue_cards', 'audit_cards'],
    yes: {
      resultText: 'Povolil jsi sevření. Něco se pohnulo. Nebylo to mnoho, ale i malý pohyb je urážka krystalizace.',
      effects: [
        { type: 'stat', key: 'control', amount: -14 },
        { type: 'stat', key: 'bond', amount: 4 },
        { type: 'profile', key: 'P', amount: 1 },
        { type: 'profile', key: 'Fe', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↓↓ · Vazba ↑', statHints: { control: 'down', bond: 'up' }, risk: 'medium' },
    },
    no: {
      resultText: 'Zatvrdil ses. Krystal byl krásný. Použitelný asi jako člověk ve vitríně.',
      effects: [
        { type: 'stat', key: 'control', amount: 9 },
        { type: 'stat', key: 'bond', amount: -7 },
        { type: 'profile', key: 'J', amount: 2 },
        { type: 'profile', key: 'Ti', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'high' },
    },
  },
};
