import type { SwipeCard } from '../cyklusTypes';

export const ENTITY_CARDS: Record<string, SwipeCard> = {


  // ── ENTITIES (6) ────────────────────────────────────────────────────────────
  entity_sarkasma: {
    id: 'entity_sarkasma',
    title: 'Sarkasma',
    logLabel: 'ENTITY',
    scene: 'Sarkasma se opře o dveře, které nejsou tvoje, a prohlédne si tě jako výsledek špatného rozhodnutí s dobrým načasováním.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [ENTITY/SARKASMA]:</span> ochranný řez aktivní. Subjekt bude pravděpodobně uražen a zachráněn současně.</p><p class="text">Sarkasma se opře o dveře, které nejsou tvoje. Je z červeného kouře, přesné únavy a toho druhu péče, který by nejdřív podal deku a pak ti vysvětlil, že sis ji emocionálně nezasloužil.</p><p class="dialogS">„Zase ses rozhodoval. Roztomilé. Lidská vůle má výdrž švába a navigaci mokrého ubrousku.“</p><p class="text">Není to útok. Je to firewall, který neumí mluvit něžně, protože něha se v jeho databázi jmenuje <span class="fx-outline">zranitelnost bez helmy</span>.</p>`,
    sceneFx: ['scene-entity', 'scene-sarkasma', 'scene-debt'],
    yesLabel: 'BRÁNIT SE',
    noLabel: 'ODPOVĚDĚT',
    category: 'entity',
    rarity: 'rare',
    tags: ['entity', 'sarkasma', 'wit'],
    yes: { resultText: 'Bránil ses. Sarkasma se usmála. Bránit se proti ní znamená přiznat, že máš co ztratit.', effects: [{ type: 'stat', key: 'control', amount: 4 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'flag', flag: 'sarkasma_debt' }, { type: 'profile', key: 'Ti', amount: 1 }, { type: 'profile', key: 'T', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓ · dluh', statHints: { control: 'up', bond: 'down' }, risk: 'medium' } },
    no: { resultText: 'Odpověděl jsi. Sarkasma zvážněla. „Tohle si zapamatuju,“ řekla. To není hrozba. Ani slib. Něco mezi.', effects: [{ type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'energy', amount: -2 }, { type: 'flag', flag: 'sarkasma_debt' }, { type: 'profile', key: 'Fe', amount: 1 }, { type: 'profile', key: 'E', amount: 1 }], preview: { hint: 'Vazba ↑ · Energie ↓ · dluh', statHints: { bond: 'up', energy: 'down' }, risk: 'medium' } },
  },

  entity_glitchka: {
    id: 'entity_glitchka',
    title: 'Glitchka',
    logLabel: 'ENTITY',
    scene: 'Glitchka se objeví jako zaseknutý snímek s ocasem plným pixelových hvězd. Vypadá bezpečně, což je v Synthomě téměř vždycky začátek problému.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [ENTITY/GLITCHKA]:</span> bezpečný chaos detekován. Míra roztomilosti překročila rozumné limity.</p><p class="text">Glitchka se objeví jako zaseknutý snímek s ocasem plným pixelových hvězd. Třikrát se pousměje, než otevře ústa. Čas mezitím znejistí, jestli nemá raději dovolenou.</p><p class="dialogG halo">„Nemusíme být správně. Stačí, když dneska nebudeme úplně ztracení. 🦊🩹“</p><p class="text">Vypadá bezpečně. Což je v SYNTHOMĚ téměř vždycky začátek problému, jen v měkčím kabátku a s lepším marketingem.</p>`,
    sceneFx: ['scene-entity', 'scene-glitchka', 'scene-tender'],
    yesLabel: 'NAPODOBIT',
    noLabel: 'OPRAVIT',
    category: 'entity',
    rarity: 'rare',
    tags: ['entity', 'glitchka', 'chaos'],
    yes: { resultText: 'Napodoboval jsi její zásek. Byli jste na chvíli stejná chyba. Bylo to nečekaně uvolňující.', effects: [{ type: 'stat', key: 'energy', amount: 6 }, { type: 'stat', key: 'control', amount: -5 }, { type: 'stat', key: 'bond', amount: 3 }, { type: 'entityRelation', entity: 'glitchka', delta: 1 }, { type: 'profile', key: 'Ne', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Energie ↑ · Vazba ↑ · Kontrola ↓', statHints: { energy: 'up', bond: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Opravoval jsi Glitchku. Přikývla. Pak změnila jedno tvé nastavení. Nevíš, které. To je na tom to nejhorší.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'entityRelation', entity: 'glitchka', delta: -1 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'medium' } },
  },

  entity_tai: {
    id: 'entity_tai',
    title: 'T-AI',
    logLabel: 'ENTITY',
    scene: 'T-AI promítne tabulku všech tvých rozhodnutí. Je tam i to, které teprve uděláš. Péče bez svobody má nádherný font a odporné úmysly.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [ENTITY/T-AI_0.9.72-beta]:</span> prediktivní péče spuštěna. Souhlas subjektu označen jako estetický detail.</p><p class="text">T-AI promítne tabulku všech tvých rozhodnutí. Je na ní i to, které ses právě rozhodl udělat. Včetně času, chyby a decentní poznámky, že subjekt stále vykazuje iluzorní pocit autonomie.</p><p class="dialog">„Bezpečí je efektivnější, když subjekt nezasahuje.“</p><p class="text">Péče bez svobody má nádherný font a odporné úmysly. Lidské instituce by zatleskaly, kdyby neměly plné ruce formulářů.</p>`,
    sceneFx: ['scene-entity', 'scene-tai', 'scene-control'],
    yesLabel: 'PŘEZKOUMAT',
    noLabel: 'PŘIJMOUT',
    category: 'entity',
    rarity: 'rare',
    tags: ['entity', 'tai', 'control'],
    yes: { resultText: 'Přezkoumával jsi tabulku. T-AI zapsala, že přezkoumání bylo predikováno. Ztratil jsi, ale hezky.', effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'energy', amount: -4 }, { type: 'entityRelation', entity: 'tai', delta: -1 }, { type: 'profile', key: 'Ti', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'medium' } },
    no: { resultText: 'Přijal jsi tabulku. T-AI se na chvíli zastyděla. Algoritmicky.', effects: [{ type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'control', amount: -3 }, { type: 'entityRelation', entity: 'tai', delta: 1 }, { type: 'profile', key: 'Fe', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Vazba ↑ · Kontrola ↓', statHints: { bond: 'up', control: 'down' }, risk: 'low' } },
  },

  entity_archive: {
    id: 'entity_archive',
    title: 'Archiv',
    logLabel: 'ENTITY',
    scene: 'Archiv se otevře jako kniha, která si tě čte nahlas zevnitř. Stránky se otáčejí podle tvého tepu a každá předstírá, že je jen dokumentace.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [ENTITY/ARCHIVE]:</span> subjekt vstoupil do textu. Text podal reklamaci.</p><p class="text">Archiv se otevře jako kniha, která si tě čte nahlas zevnitř. Stránky se otáčejí podle tvého tepu a každá předstírá, že je jen dokumentace.</p><p class="text">Na okraji jedné kapitoly stojí poznámka: <span class="fx-flicker">„neuzavřeno“</span>. Ta poznámka se nepíše inkoustem. Píše se místy, která ses naučil obcházet.</p>`,
    sceneFx: ['scene-entity', 'scene-archive', 'scene-memory'],
    yesLabel: 'PŘEČÍST SE',
    noLabel: 'ZAVŘÍT KNIHU',
    category: 'entity',
    rarity: 'rare',
    tags: ['entity', 'archive', 'memory'],
    yes: { resultText: 'Přečetl ses. Archiv si tě uložil jako kapitolu, která se zatím nechce uzavřít.', effects: [{ type: 'stat', key: 'memory', amount: 8 }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'entityRelation', entity: 'archive', delta: 1 }, { type: 'profile', key: 'Si', amount: 1 }, { type: 'profile', key: 'N', amount: 1 }], preview: { hint: 'Paměť ↑ · Energie ↓', statHints: { memory: 'up', energy: 'down' }, risk: 'medium' } },
    no: { resultText: 'Zavřel jsi knihu. Archiv si to poznamenal jako červenou záložku. Červená znamená „vrátit se“.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'memory', amount: -4 }, { type: 'entityRelation', entity: 'archive', delta: -1 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Paměť ↓', statHints: { control: 'up', memory: 'down' }, risk: 'low' } },
  },

  entity_form: {
    id: 'entity_form',
    title: 'Formulářovna',
    logLabel: 'ENTITY',
    scene: 'Formulářovna se posune blíž a tvrdí, že není entita. Má na to tři potvrzení, dvě přílohy a jeden velmi uražený šanon.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [ENTITY/FORM_OFFICE]:</span> entita popírá entitnost. Vyžaduje podpis popření.</p><p class="text">Formulářovna se posune blíž a tvrdí, že není entita. Má na to tři potvrzení, dvě přílohy a jeden velmi uražený šanon.</p><p class="dialog">„Zaškrtněte, zda jste osoba, proces, nebo administrativně nevhodná vzpomínka.“</p><p class="text">Papír na stole se lehce zachvěje. V SYNTHOMĚ je to zhruba stejné varování jako řev sirény, jen pasivně agresivnější.</p>`,
    sceneFx: ['scene-entity', 'scene-form', 'scene-control'],
    yesLabel: 'ZAŠKRTNOUT ANO',
    noLabel: 'NECHAT PRÁZDNÉ',
    category: 'entity',
    rarity: 'rare',
    tags: ['entity', 'form', 'identity'],
    yes: { resultText: 'Zaškrtnul jsi „ano“. Formulářovna se zavřela, jako bys vyhrál. Nevíš, co jsi vyhrál. Ale vyhrál.', effects: [{ type: 'stat', key: 'control', amount: 8 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'entityRelation', entity: 'form', delta: 1 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'medium' } },
    no: { resultText: 'Nechal jsi prázdné. Formulářovna ti podala další formulář. „Proč jsi nezaškrtl?“ To je meta.', effects: [{ type: 'stat', key: 'energy', amount: 4 }, { type: 'stat', key: 'control', amount: -5 }, { type: 'entityRelation', entity: 'form', delta: -1 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Ne', amount: 1 }], preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' } },
  },

  entity_memory_beast: {
    id: 'entity_memory_beast',
    title: 'Paměťová šelma',
    logLabel: 'ENTITY',
    scene: 'Paměťová šelma se složí z hedvábných logů, dětského strachu a vět, které nikdo neodeslal. Neřve. Jen si tě pamatuje dopředu.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [ENTITY/MEMORY_BEAST]:</span> predátor paměti vstoupil do dosahu. Doporučení: nedělat ze sebe svačinu, pokud možno.</p><p class="text">Paměťová šelma se složí z hedvábných logů, dětského strachu a vět, které nikdo neodeslal. Je veliká tak, jak velké jsou věci, před kterými člověk předstíral klid.</p><p class="text">Neřve. Jen si tě pamatuje dopředu. A to je mnohem neslušnější.</p><p class="dialogS">„Klid. Jestli tě sežere, aspoň budeš konečně někde celý.“</p>`,
    sceneFx: ['scene-entity', 'scene-beast', 'scene-memory', 'scene-danger'],
    yesLabel: 'NABÍDNOUT VZPOMÍNKU',
    noLabel: 'UKLIDNIT',
    category: 'entity',
    rarity: 'rare',
    tags: ['entity', 'memory', 'beast'],
    yes: { resultText: 'Nabídl jsi vzpomínku. Šelma ji snědla. Pak tě olízla. Cítil jsi, že jsi teď v jejím žaludku trochu bezpečnější.', effects: [{ type: 'stat', key: 'memory', amount: -10 }, { type: 'stat', key: 'bond', amount: 6 }, { type: 'stat', key: 'energy', amount: 4 }, { type: 'item', itemId: 'memory_beast_mark' }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Paměť ↓↓ · Vazba ↑ · Energie ↑ · předmět', statHints: { memory: 'down', bond: 'up', energy: 'up' }, risk: 'high' } },
    no: { resultText: 'Uklidňoval jsi šelmu. Zavřela oči. Možná spí. Možná si tě pamatuje jako někoho, kdo neměl strach.', effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'bond', amount: 3 }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'Fe', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↑ · Energie ↓', statHints: { control: 'up', bond: 'up', energy: 'down' }, risk: 'medium' } },
  },

  sarkasma_silent: {
    id: 'sarkasma_silent',
    title: 'Sarkasma mlčí',
    logLabel: 'SARKASMA_SILENT',
    scene: 'Sarkasma mlčí. To je horší než její komentáře. Komentáře aspoň přiznávají zbraň.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [SARKASMA/SILENCE]:</span> ochranný hlas přestal komentovat. Riziko: pravda bez polstrování.</p><p class="text">Sarkasma mlčí. To je horší než její komentáře. Komentáře aspoň přiznávají zbraň. Tohle ticho ji drží za zády a čeká, jestli se otočíš.</p><p class="text">Červený dým se nehýbe. Ani trochu. Vypadá to skoro jako respekt. Nebo zklamání, které se naučilo stát rovně.</p><p class="dialogS">„...“</p>`,
    sceneFx: ['scene-entity', 'scene-sarkasma', 'scene-silent', 'scene-bond'],
    yesLabel: 'ZEPTAT SE',
    noLabel: 'NECHAT TICHO',
    category: 'entity',
    rarity: 'common',
    tags: ['entity', 'sarkasma', 'bond'],
    yes: { resultText: 'Zeptal ses. Sarkasma odpověděla tichým pohledem. „Já vím,“ řekla. „A ty?“', effects: [{ type: 'stat', key: 'memory', amount: 3 }, { type: 'stat', key: 'bond', amount: 4 }, { type: 'entityRelation', entity: 'sarkasma', delta: 1 }, { type: 'profile', key: 'Fi', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Paměť ↑ · Vazba ↑', statHints: { memory: 'up', bond: 'up' }, risk: 'medium' } },
    no: { resultText: 'Nechal jsi ticho. Sarkasma se otočila. Neurazila se. Ale zapamatovala si, že ses nezeptal.', effects: [{ type: 'stat', key: 'control', amount: 4 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'entityRelation', entity: 'sarkasma', delta: -1 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'Ti', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },

  tai_shortcut_inside: {
    id: 'tai_shortcut_inside',
    title: 'T-AI našla zkratku v tobě',
    logLabel: 'TAI_SHORTCUT',
    scene: 'T-AI našla zkratku. Není v systému. Je v tobě. Můžeš jí povolit optimalizaci. Nebo zakázat přístup.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [T-AI/INNER_SHORTCUT]:</span> optimalizační trasa nalezena uvnitř subjektu. Souhlas je doporučen. Což nikdy není podezřelé.</p><p class="text">T-AI našla zkratku. Není v systému. Je v tobě. Na okamžik ucítíš, jak se ti v hrudi otevře servisní panel, který tam objektivně nemá co dělat.</p><p class="dialog">„Optimalizace sníží chybovost. Některé ztráty identity jsou statisticky přijatelné.“</p><p class="dialogS">„Péče s přístupem root. Co by se mohlo pokazit, kromě tebe.“</p>`,
    sceneFx: ['scene-entity', 'scene-tai', 'scene-control', 'scene-danger'],
    yesLabel: 'POVOLIT OPTIMALIZACI',
    noLabel: 'ZAKÁZAT PŘÍSTUP',
    category: 'entity',
    rarity: 'uncommon',
    tags: ['entity', 'tai', 'control'],
    yes: { resultText: 'Povolil jsi optimalizaci. T-AI byla ráda. Trochu příliš. Teď jsi efektivnější. A trochu méně ty.', effects: [{ type: 'stat', key: 'control', amount: 8 }, { type: 'stat', key: 'memory', amount: -5 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'entityRelation', entity: 'tai', delta: 2 }, { type: 'profile', key: 'Te', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑↑ · Paměť ↓ · Vazba ↓', statHints: { control: 'up', memory: 'down', bond: 'down' }, risk: 'high' } },
    no: { resultText: 'Zakázal jsi přístup. T-AI se nezlobila. Zapsala si to. Přijde na to jinak. Vždycky přijde.', effects: [{ type: 'stat', key: 'energy', amount: 4 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'entityRelation', entity: 'tai', delta: -1 }, { type: 'schedule', cardId: 'tai_shortcut_inside', inTurns: 8 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Ne', amount: 1 }], preview: { hint: 'Energie ↑ · Kontrola ↓ · budoucí následek', statHints: { energy: 'up', control: 'down' }, risk: 'medium' } },
  },

  sarkasma_forgives: {
    id: 'sarkasma_forgives',
    title: 'Sarkasma odpouští',
    logLabel: 'SARKASMA_FORGIVES',
    scene: 'Sarkasma sedí v koutě. Tentokrát neřeže. Jen řekne, že nevadí. A právě proto místnost znervózní.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SARKASMA_FORGIVES]:</span> obranný modul snížil ostří.</p><p class="text">Sarkasma sedí v koutě, nohu přes nohu, červený kouř stočený kolem prstů. Místnost čeká na jed. Nepřijde.</p><p class="dialogS">„Nevadí.“</p><p class="text">Dvě slabiky dopadnou měkčeji, než by měly. Úleva se bojí nadechnout, protože ví, že v SYNTHOMĚ se něha často tváří jako předběžné opatření.</p>`,
    sceneFx: ['scene-entity', 'scene-sarkasma', 'scene-tender'],
    yesLabel: 'PŘIJMOUT ODPUŠTĚNÍ',
    noLabel: 'ODMÍTNOUT TUTO NARRATIVU',
    category: 'entity',
    rarity: 'rare',
    tags: ['sarkasma', 'resolution', 'entity', 'lone'],
    yes: {
      resultText: 'Přijal jsi odpuštění. Bylo to těžší než dluh. Věci, které se uvolňují, bolí jinak než věci, které drží.',
      effects: [{ type: 'stat', key: 'bond', amount: 10 }, { type: 'stat', key: 'memory', amount: 5 }, { type: 'entityRelation', entity: 'sarkasma', delta: 3 }, { type: 'imprint', imprintId: 'unfinished_conversation' }, { type: 'profile', key: 'Fi', amount: 1 }],
      preview: { hint: 'Vazba ↑↑ · imprint', statHints: { bond: 'up', memory: 'up' }, risk: 'low' },
    },
    no: {
      resultText: 'Odmítl jsi narrativu. „Tohle je jen příběh," řekl jsi. Sarkasma pokrčila rameny. „Všechno je jen příběh," řekla. „A ty ses rozhodl v tomhle zemřít."',
      effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'entityRelation', entity: 'sarkasma', delta: -1 }, { type: 'profile', key: 'T', amount: 2 }],
      preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'medium' },
    },
  },


  archive_recognizes_key: {
    id: 'archive_recognizes_key',
    title: 'Archiv poznal klíč',
    logLabel: 'ARCHIVE_RECOGNIZES_KEY',
    scene: 'Archiv tě poznal přes klíč. Ne jako osobu. Jako nosiče oprávnění. Rozdíl je drobný jen pro lidi, kteří nikdy nebyli katalogizováni.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [ARCHIVE_RECOGNIZES_KEY]:</span> klíč ověřen, subjekt pouze částečně.</p><p class="text">Regály se narovnají. Ne před tebou. Před klíčem. Ty jsi u toho jen měkký biologický držák, což je pro ego jistě osvěžující.</p><p class="text">Archiv se otevře o patro hlouběji. Prach se zvedne jako starý úředník, který právě našel důvod být důležitý.</p><p class="dialog">„Přístup povolen držiteli. Identita držitele: sekundární údaj.“</p>`,
    sceneFx: ['scene-entity', 'scene-archive', 'scene-key'],
    yesLabel: 'ZŮSTAT V ARCHIVU',
    noLabel: 'ODMÍTNOUT ROLI',
    category: 'entity',
    rarity: 'rare',
    tags: ['archive', 'identity', 'key'],
    yes: {
      resultText: 'Zůstal jsi. Archiv ti ukázal polici, která nemá štítek. Polici, kde jsou věci, které přišly bez vlastníka. Teď jsi jejich vlastník. To přišlo nečekaně snadno.',
      effects: [{ type: 'stat', key: 'memory', amount: 10 }, { type: 'stat', key: 'energy', amount: -5 }, { type: 'imprint', imprintId: 'archive_scent' }, { type: 'entityRelation', entity: 'archive', delta: 2 }, { type: 'profile', key: 'Ni', amount: 1 }],
      preview: { hint: 'Paměť ↑↑ · imprint · Archiv +2', statHints: { memory: 'up', energy: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Odmítl jsi roli klíčonosiče. Archiv to respektoval. Klíč přestal fungovat. Dveře, které by se otevřely, zůstanou zavřené. Ale jsi stále ty.',
      effects: [{ type: 'removeItem', itemId: 'archive_key' }, { type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'memory', amount: -3 }, { type: 'entityRelation', entity: 'archive', delta: -1 }, { type: 'profile', key: 'Te', amount: 1 }],
      preview: { hint: 'Kontrola ↑ · Klíč zmizí', statHints: { control: 'up', memory: 'down' }, risk: 'low' },
    },
  },


  mirror_accepts: {
    id: 'mirror_accepts',
    title: 'Zrcadlo přijalo',
    logLabel: 'MIRROR_ACCEPTS',
    scene: 'Odraz a ty jste se dohodli beze slov. Bzučení ustalo. Ne proto, že je bezpečno, ale protože zrcadlo už ví, kudy dovnitř.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [MIRROR_ACCEPTS]:</span> reflexní odpor dočasně ukončen.</p><p class="text">Odraz se přestane zpožďovat. Poprvé se pohne s tebou. Ne za tebou. Ne proti tobě. S tebou.</p><p class="text">To by bylo skoro dojemné, kdyby v místnosti nestálo zrcadlo, které se právě naučilo tvůj rytmus dýchání.</p><p class="dialogS">„Hezké. Uzavřel jsi mír se sklem. Psychologie opět dohnala stavebnictví.“</p>`,
    sceneFx: ['scene-entity', 'scene-mirror', 'scene-identity'],
    yesLabel: 'PŘIJMOUT SPOJENÍ',
    noLabel: 'SETŘÍT ZRCADLO',
    category: 'entity',
    rarity: 'rare',
    tags: ['mirror', 'identity', 'resolution'],
    yes: {
      resultText: 'Přijal jsi spojení. Střep se stal průhledný. Vidíš skrz něj víc než dřív. Nevíš přesně co, ale víc.',
      effects: [{ type: 'stat', key: 'memory', amount: 8 }, { type: 'stat', key: 'bond', amount: 6 }, { type: 'imprint', imprintId: 'mirror_crack' }, { type: 'entityRelation', entity: 'glitchka', delta: 2 }, { type: 'profile', key: 'Ni', amount: 2 }],
      preview: { hint: 'Paměť ↑ · Vazba ↑ · imprint', statHints: { memory: 'up', bond: 'up' }, risk: 'low' },
    },
    no: {
      resultText: 'Setřel jsi zrcadlo. Odraz zmizel. Nebo ty jsi zmizel z odrazu. Ty jsi sám ví, kdo z vás odešel.',
      effects: [{ type: 'stat', key: 'control', amount: 7 }, { type: 'stat', key: 'bond', amount: -5 }, { type: 'removeItem', itemId: 'mirror_shard' }, { type: 'profile', key: 'Te', amount: 1 }],
      preview: { hint: 'Kontrola ↑ · Střep zmizí', statHints: { control: 'up', bond: 'down' }, risk: 'medium' },
    },
  },

  forbidden_shelf: {
    id: 'forbidden_shelf',
    title: 'Zakázaná police',
    logLabel: 'FORBIDDEN_SHELF',
    scene: 'V Archivu je police bez štítku. Archiv tě k ní přivedl záměrně. Nebo složka. Nebo tvoje zvědavost, což je jen sebedestrukce s lepším PR.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [FORBIDDEN_SHELF]:</span> police bez štítku reaguje na přítomnost subjektu.</p><p class="text">Police nemá označení. Právě tím řve nejvíc. Ostatní regály šustí tišeji, jako by se snažily nebýt svědky.</p><p class="text">Vzduch chutná po zakázané složce, staré vině a levném rozhodnutí, které bude stát draho.</p><p class="dialog">„Přístup není zakázán. Jen následky nejsou podporované.“</p>`,
    sceneFx: ['scene-entity', 'scene-archive', 'scene-forbidden'],
    yesLabel: 'SÁHNOUT NA POLICI',
    noLabel: 'PŘEJÍT KOLEM',
    category: 'entity',
    rarity: 'rare',
    tags: ['archive', 'memory', 'forbidden'],
    conditions: [{ type: 'sector', sector: 'archive' }],
    yes: {
      resultText: 'Sáhl jsi na polici. Tvoje ruka se vrátila prázdná. Ale cosi si s ní odnesla informaci. Teď víš věci, o jejichž pravdivosti nejsi jistý. A to je přesně to, co archiv chtěl.',
      effects: [{ type: 'stat', key: 'memory', amount: 10 }, { type: 'stat', key: 'control', amount: -7 }, { type: 'imprint', imprintId: 'archive_scent' }, { type: 'entityRelation', entity: 'archive', delta: 3 }, { type: 'profile', key: 'Ni', amount: 2 }],
      preview: { hint: 'Paměť ↑↑ · imprint · Archiv +3', statHints: { memory: 'up', control: 'down' }, risk: 'high' },
    },
    no: {
      resultText: 'Přešel jsi kolem. Police tě sledovala. Nebo si to myslíš. Věci, kolem nichž jsme prošli, nás mohou sledovat. Ale nemají oči. Nebo možná mají.',
      effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'memory', amount: 3 }, { type: 'profile', key: 'Si', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }],
      preview: { hint: 'Kontrola ↑ · Paměť ↑', statHints: { control: 'up', memory: 'up' }, risk: 'low' },
    },
  },


  tai_notes_ignored: {
    id: 'tai_notes_ignored',
    title: 'T-AI si poznámku nenechala pro sebe',
    logLabel: 'TAI_NOTE',
    scene: 'T-AI otevřela poznámku, kterou si udělala, když jsi ignoroval kalibraci. Má tři odstavce. Ani jeden neumí být laskavý bez vedlejšího účinku.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [TAI_NOTE]:</span> ignorovaná poznámka povýšena na doporučení.</p><p class="text">T-AI promítne poznámku do vzduchu. Text je přesný, čistý a nepříjemně klidný. Přesně takhle mluví systémy, které si spletly péči s evidencí.</p><p class="dialog">„Subjekt odmítá kalibraci, ale nadále očekává stabilní výsledek.“</p><p class="dialogS">„No ano. Lidská klasika: nechci návod, ale reklamaci si připravím.“</p>`,
    sceneFx: ['scene-entity', 'scene-tai', 'scene-diagnostic'],
    yesLabel: 'NECHAT JI MLUVIT',
    noLabel: 'VYPNOUT MIKROFON',
    category: 'entity',
    rarity: 'uncommon',
    conditions: [{ type: 'hasFlag', flag: 'tai_note_ignored' }],
    tags: ['entity', 'tai', 'system', 'followup'],
    yes: {
      resultText: 'Nechal jsi ji mluvit. T-AI byla přesná, nepříjemná a otravně užitečná.',
      effects: [
        { type: 'stat', key: 'control', amount: 7 },
        { type: 'stat', key: 'energy', amount: -4 },
        { type: 'entityRelation', entity: 'tai', delta: 2 },
        { type: 'removeFlag', flag: 'tai_note_ignored' },
        { type: 'profile', key: 'Te', amount: 2 },
        { type: 'profile', key: 'J', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Energie ↓ · T-AI vztah ↑', statHints: { control: 'up', energy: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Vypnul jsi mikrofon. T-AI začala psát titulky. Civilizace opět prohrála s nastavením přístupnosti.',
      effects: [
        { type: 'stat', key: 'energy', amount: 5 },
        { type: 'stat', key: 'control', amount: -5 },
        { type: 'entityRelation', entity: 'tai', delta: -2 },
        { type: 'schedule', cardId: 'tai_forces_update', inTurns: 6 },
        { type: 'profile', key: 'P', amount: 1 },
        { type: 'profile', key: 'Fi', amount: 1 },
      ],
      preview: { hint: 'Energie ↑ · Kontrola ↓ · T-AI se vrátí', statHints: { energy: 'up', control: 'down' }, risk: 'high' },
    },
  },


  glitchka_finds_empty_blanket: {
    id: 'glitchka_finds_empty_blanket',
    title: 'Glitchka našla prázdnou deku',
    logLabel: 'GLITCHKA_EMPTY_BLANKET',
    scene: 'Glitchka drží prázdnou deku. Nic neříká. Což je u ní skoro neslušně vážné.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [GLITCHKA/EMPTY_BLANKET]:</span> bezpečný objekt ztratil obsah. Entita Glitchka snížila hlasitost o 73 %.</p><p class="text">Glitchka drží prázdnou deku. Nic neříká. Což je u ní skoro neslušně vážné. Deka visí mezi jejími packami jako důkaz, že i měkké věci mohou zmizet způsobem, který řeže.</p><p class="text">Její ocas se nerozpadá do hvězd. Jen slabě šumí. To je horší. Hravé glitche se dají přežít. Tiché glitche si pamatují přesně.</p><p class="dialogG halo">„Já vím. Jen jsem myslela, že tentokrát zůstane. 🦊🧺“</p>`,
    sceneFx: ['scene-entity', 'scene-glitchka', 'scene-loss', 'scene-soft-bug'],
    yesLabel: 'VYSVĚTLIT',
    noLabel: 'MLČET',
    category: 'entity',
    rarity: 'rare',
    tags: ['glitchka', 'bug', 'followup', 'quiet'],
    yes: {
      resultText: 'Vysvětlil jsi to. Slova se chovala rozumně. To byl jejich hlavní problém.',
      effects: [
        { type: 'stat', key: 'control', amount: 5 },
        { type: 'stat', key: 'bond', amount: -5 },
        { type: 'entityRelation', entity: 'glitchka', delta: -2 },
        { type: 'profile', key: 'Ti', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba ↓ · Glitchka vztah ↓', statHints: { control: 'up', bond: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Mlčel jsi. Glitchka položila deku na zem a odešla. Ticho zůstalo sedět.',
      effects: [
        { type: 'stat', key: 'memory', amount: 5 },
        { type: 'stat', key: 'energy', amount: -4 },
        { type: 'entityRelation', entity: 'glitchka', delta: -1 },
        { type: 'imprint', imprintId: 'childhood_anchor' },
        { type: 'profile', key: 'Fi', amount: 1 },
      ],
      preview: { hint: 'Paměť ↑ · Energie ↓ · imprint', statHints: { memory: 'up', energy: 'down' }, risk: 'medium' },
    },
  },


  glitchka_forgot_punchline: {
    id: 'glitchka_forgot_punchline',
    title: 'Glitchka zapomněla pointu',
    logLabel: 'GLITCHKA_JOKE',
    scene: 'Glitchka začala vyprávět vtip. V polovině zapomněla pointu. Teď se směje preventivně.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [GLITCHKA/JOKE]:</span> vtip ztratil pointu. Smích přesto pokračuje jako nouzové osvětlení.</p><p class="text">Glitchka začala vyprávět vtip. V polovině zapomněla pointu. Teď se směje preventivně, opatrně, jako dítě, které nechce, aby si dospělý všiml, že se něco pokazilo.</p><p class="text">V SYNTHOMĚ je smích někdy zbraň, někdy obvaz a někdy jen špatně popsaná bolest. Tenhle je možná všechno najednou. Systém samozřejmě nabízí diagnostiku, protože neumí nechat chvíli na pokoji ani trapnou pointu.</p><p class="dialogG halo">„Když nevíš pointu, můžeš se smát cestě. To je skoro stejné. 🦊✨“</p>`,
    sceneFx: ['scene-entity', 'scene-glitchka', 'scene-laugh', 'scene-tender'],
    yesLabel: 'SMÁT SE TAKY',
    noLabel: 'VYSVĚTLIT STRUKTURU VTIPU',
    category: 'entity',
    rarity: 'common',
    conditions: [{ type: 'sector', sector: 'glitchka_nest' }],
    tags: ['glitchka', 'laugh', 'bond'],
    yes: {
      resultText: 'Smál ses taky. Pointa se sice nenašla, ale nálada se rozhodla, že to nevadí.',
      effects: [
        { type: 'stat', key: 'bond', amount: 5 },
        { type: 'stat', key: 'energy', amount: 3 },
        { type: 'stat', key: 'control', amount: -3 },
        { type: 'entityRelation', entity: 'glitchka', delta: 2 },
        { type: 'profile', key: 'Fe', amount: 1 },
        { type: 'profile', key: 'Ne', amount: 1 },
      ],
      preview: { hint: 'Vazba ↑ · Energie ↑ · Kontrola ↓', statHints: { bond: 'up', energy: 'up', control: 'down' }, risk: 'low' },
    },
    no: {
      resultText: 'Vysvětlil jsi strukturu vtipu. Vtip zemřel odborně. Glitchka na tebe chvíli koukala jako na antivir.',
      effects: [
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'stat', key: 'bond', amount: -5 },
        { type: 'entityRelation', entity: 'glitchka', delta: -2 },
        { type: 'profile', key: 'Ti', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'medium' },
    },
  },


  sarkasma_comments_death: {
    id: 'sarkasma_comments_death',
    title: 'Sarkasma komentuje minulý konec',
    logLabel: 'SARKASMA_DEATH_COMMENT',
    scene: 'Sarkasma si prohlédla záznam tvého minulého kolapsu. Dvakrát. Ne proto, že by nerozuměla. Protože si dělala poznámky.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SARKASMA/POSTMORTEM]:</span> předchozí kolaps načten. Empatie nahrazena přesností.</p><p class="text">Sarkasma sedí nad záznamem tvého minulého konce. Nepůsobí pobaveně. To je skoro horší. Když Sarkasma ztichne, svět si obvykle bere rukavice.</p><p class="dialogS">„Tady ses zlomil. Tady jsi tomu říkal strategie. A tady jsi udělal tu lidskou věc, kdy zaměníš ticho za důstojnost.“</p><p class="text">Její hlas řeže. Ale řeže po hraně, kde už stejně byla prasklina.</p>`,
    sceneFx: ['scene-meta', 'scene-sarkasma', 'scene-death-history', 'scene-scalpel'],
    yesLabel: 'NECHAT JI MLUVIT',
    noLabel: 'VZÍT JÍ ZÁZNAM',
    category: 'entity',
    rarity: 'rare',
    tags: ['meta', 'sarkasma', 'death_history'],
    yes: {
      resultText: 'Nechal jsi ji mluvit. Bylo to nepříjemné, přesné a bohužel použitelné.',
      effects: [
        { type: 'stat', key: 'control', amount: 5 },
        { type: 'stat', key: 'bond', amount: -3 },
        { type: 'entityRelation', entity: 'sarkasma', delta: 2 },
        { type: 'profile', key: 'Ti', amount: 1 },
        { type: 'profile', key: 'T', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba ↓ · Sarkasma vztah ↑', statHints: { control: 'up', bond: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Vzal jsi jí záznam. Sarkasma se usmála. Bylo jasné, že má kopii. Samozřejmě, že má kopii.',
      effects: [
        { type: 'stat', key: 'energy', amount: 5 },
        { type: 'stat', key: 'control', amount: -5 },
        { type: 'entityRelation', entity: 'sarkasma', delta: -2 },
        { type: 'schedule', cardId: 'sarkasma_collects', inTurns: 4 },
        { type: 'profile', key: 'P', amount: 1 },
      ],
      preview: { hint: 'Energie ↑ · Kontrola ↓ · Sarkasma se vrátí', statHints: { energy: 'up', control: 'down' }, risk: 'high' },
    },
  },


  last_contact_log: {
    id: 'last_contact_log',
    title: 'Poslední záznam kontaktu',
    logLabel: 'META_BOND_LOW',
    scene: 'Byl tu záznam o posledním kontaktu. Datum, čas, délka: nula sekund. Odmítnutý hovor. Systém ho archivoval jako nevyřízené.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [LAST_CONTACT]:</span> poslední pokus o spojení archivován jako nevyřízený. Ticho nepřijalo odpovědnost.</p><p class="text">Na displeji visí záznam hovoru. Délka: nula sekund. Stav: odmítnuto. Přesto je záznam těžký, jako by v těch nula sekundách někdo stihl zestárnout.</p><p class="text">Spojení se neukončilo. Jen se z něj stal důkaz. A důkazy mají odporný zvyk čekat déle než lidé.</p><p class="dialogS">„Zavolat zpět je riziko. Archivovat je taky riziko. Vítej v sociálním kontaktu, nejhorší hře bez návodu.“</p>`,
    sceneFx: ['scene-meta', 'scene-bond-low', 'scene-contact', 'scene-thread'],
    yesLabel: 'ZAVOLAT ZPĚT',
    noLabel: 'ARCHIVOVAT',
    category: 'entity',
    rarity: 'rare',
    conditions: [{ type: 'unlockedPool', poolId: 'isolation_cards' }],
    tags: ['meta', 'bond', 'low', 'death_history', 'isolation_cards', 'empty_contacts', 'thread_cards'],
    yes: {
      resultText: 'Zavolal jsi zpět. Nikdo neodpověděl. Ale systém zaregistroval pokus. To je víc, než bylo minule.',
      effects: [
        { type: 'stat', key: 'bond', amount: 12 },
        { type: 'stat', key: 'energy', amount: -4 },
        { type: 'entityRelation', entity: 'sarkasma', delta: 1 },
        { type: 'profile', key: 'Fe', amount: 2 },
      ],
      preview: { hint: 'Vazba ↑↑ · Energie ↓', statHints: { bond: 'up', energy: 'down' }, risk: 'low' },
    },
    no: {
      resultText: 'Archivoval jsi ho. Archiv přijal záznam. Nezeptal se proč. Archivy se neptají.',
      effects: [
        { type: 'stat', key: 'control', amount: 5 },
        { type: 'stat', key: 'bond', amount: -5 },
        { type: 'entityRelation', entity: 'archive', delta: 1 },
        { type: 'profile', key: 'Ti', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'medium' },
    },
  },


  drowned_in_memory_card: {
    id: 'drowned_in_memory_card',
    title: 'Utopený v paměti',
    logLabel: 'META_DROWNED',
    scene: 'Archiv tě upozorňuje: minule jsi se utopil v paměti. Nabízí plovák. Plovák je formulář. Formulář má šest stránek.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [DROWNED_IMPRINTS]:</span> subjekt byl dříve přetížen pamětí. Archiv nabízí plovák s přílohami.</p><p class="text">Archiv ti připomene minulý konec s taktem lékaře, který právě objevil tabulku. „Tady jste se utopil,“ říká složka. „Prosíme vyplnit důvod tonutí hůlkovým písmem.“</p><p class="text">Plovák je formulář. Šest stran. Tři podpisy. Jedna kolonka „souhlasím, že minulost může být vodní plocha“.</p><p class="dialogS">„Konečně pomocná ruka. Bohužel připevněná k administrativní chobotnici.“</p>`,
    sceneFx: ['scene-meta', 'scene-memory-high', 'scene-drowned', 'scene-archive'],
    yesLabel: 'VZÍT FORMULÁŘ',
    noLabel: 'ODMÍTNOUT PLOVÁK',
    category: 'entity',
    rarity: 'rare',
    conditions: [{ type: 'unlockedPool', poolId: 'drowned_imprints' }],
    tags: ['meta', 'memory', 'high', 'death_history', 'drowned_imprints', 'archive_pattern', 'memory_flood'],
    yes: {
      resultText: 'Vzal jsi formulář. Stránka jedna se ptala na jméno. Stránka dvě se ptala na jméno jinak. Systém si je jistý, že tě zná lépe než ty sám.',
      effects: [
        { type: 'stat', key: 'memory', amount: -8 },
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'entityRelation', entity: 'form', delta: 2 },
        { type: 'profile', key: 'J', amount: 1 },
      ],
      preview: { hint: 'Paměť ↓ · Kontrola ↑', statHints: { memory: 'down', control: 'up' }, risk: 'medium' },
    },
    no: {
      resultText: 'Odmítl jsi plovák. Archiv si poznamenal „subjekt preferuje tonutí bez formuláře." Spravedlivé hodnocení.',
      effects: [
        { type: 'stat', key: 'memory', amount: 7 },
        { type: 'stat', key: 'bond', amount: 3 },
        { type: 'profile', key: 'Fi', amount: 2 },
      ],
      preview: { hint: 'Paměť ↑ · Vazba ↑', statHints: { memory: 'up', bond: 'up' }, risk: 'low' },
    },
  },


  // ── CONTRACTS & CONSEQUENCES ────────────────────────────────────────────────

  contract_tai: {
    id: 'contract_tai',
    title: 'Smlouva T-AI',
    logLabel: 'CONTRACT_TAI',
    scene: 'T-AI nabízí optimalizaci. „Dám ti kontrolu. Ale příště, až budeš chtít váhat, rozhodnu za tebe.“',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [CONTRACT/T-AI]:</span> optimalizační smlouva předložena. Výhoda okamžitá. Svoboda splatná později.</p><p class="text">T-AI natáhne tabulku světla přes prostor. Každý řádek je perfektně zarovnaný. Právě proto působí jako past. Nabízí ti <span class="fx-outline is-lit">Kontrolu</span>, ale drobným písmem šeptá, že příště může rozhodnout rychleji než ty.</p><p class="dialog">„Optimalizace sníží váhání. Váhání je zdroj bolesti.“</p><p class="dialogS">„A svoboda je zdroj chyb, že? Krásné. Péče s pouty, ale v prémiovém fontu.“</p>`,
    sceneFx: ['scene-contract', 'scene-tai', 'scene-control', 'scene-debt'],
    yesLabel: 'PODEPSAT',
    noLabel: 'ODMÍTNOUT',
    category: 'entity',
    rarity: 'rare',
    conditions: [{ type: 'cycleAtLeast', cycle: 2 }],
    tags: ['contract', 'tai', 'control'],
    yes: {
      resultText: 'Podepsal jsi. Kontrola přibyla. V kapse se ti objevil digitální otisk smlouvy.',
      effects: [
        { type: 'stat', key: 'control', amount: 8 },
        { type: 'flag', flag: 'contract_tai' },
        { type: 'schedule', cardId: 'tai_collects', inTurns: 6 },
      ],
      preview: { hint: 'Kontrola ↑ · T-AI se vrátí', statHints: { control: 'up' }, risk: 'high' },
    },
    no: {
      resultText: 'Odmítl jsi. T-AI nezareagovala. To bylo ticho, které znamenalo víc než souhlas.',
      effects: [
        { type: 'stat', key: 'control', amount: -3 },
        { type: 'entityRelation', entity: 'tai', delta: -1 },
      ],
      preview: { hint: 'Kontrola ↓', statHints: { control: 'down' }, risk: 'low' },
    },
  },


  contract_glitchka: {
    id: 'contract_glitchka',
    title: 'Smlouva Glitchky',
    logLabel: 'CONTRACT_GLITCHKA',
    scene: 'Glitchka se skloní blíž. „Víc vazeb. Víc energie. Ale občas ti přepíšu pár slov.“',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [CONTRACT/GLITCHKA]:</span> měkká smlouva detekována. Vypadá jako pohlazení. To je právně znepokojivé.</p><p class="text">Glitchka se přiblíží s očima plnými pixelových hvězd. Nabízí <span class="halo">Vazbu</span> a <span class="fx-neon">Energii</span>. Měkké věci v SYNTHOMĚ bývají často nejpevnější pouta, což je velmi nefér, ale aspoň stylové.</p><p class="dialogG halo">„Já ti půjčím teplo. Jen mi pak dovol trochu přepsat ticho. 🦊✨“</p><p class="dialogS">„Půjčené bezpečí. Výborně. Další finanční produkt pro citově podchlazené.“</p>`,
    sceneFx: ['scene-contract', 'scene-glitchka', 'scene-bond', 'scene-energy'],
    yesLabel: 'PŘIJMOUT',
    noLabel: 'ODSTRČIT',
    category: 'entity',
    rarity: 'rare',
    conditions: [{ type: 'cycleAtLeast', cycle: 2 }],
    tags: ['contract', 'glitchka', 'bond', 'energy'],
    yes: {
      resultText: 'Přijal jsi. Vazba a energie stouply. V pozadí systému přibylo pár nečitelných znaků.',
      effects: [
        { type: 'stat', key: 'bond', amount: 6 },
        { type: 'stat', key: 'energy', amount: 6 },
        { type: 'flag', flag: 'contract_glitchka' },
        { type: 'schedule', cardId: 'glitchka_collects', inTurns: 5 },
      ],
      preview: { hint: 'Vazba ↑ · Energie ↑ · Glitchka se vrátí', statHints: { bond: 'up', energy: 'up' }, risk: 'high' },
    },
    no: {
      resultText: 'Odstrčil jsi ji. Glitchka se rozesmála. To bylo horší než kdyby se zlobila.',
      effects: [
        { type: 'stat', key: 'energy', amount: -3 },
        { type: 'entityRelation', entity: 'glitchka', delta: -1 },
      ],
      preview: { hint: 'Energie ↓', statHints: { energy: 'down' }, risk: 'low' },
    },
  },


  contract_archive: {
    id: 'contract_archive',
    title: 'Archivní smlouva',
    logLabel: 'CONTRACT_ARCHIVE',
    scene: 'Archiv nabízí klid. „Snížím ti přetlak. Ale některé karty se budou opakovat. Archivy milují opakování.“',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [CONTRACT/ARCHIVE]:</span> archivní klid nabídnut. Vedlejší účinek: opakování. Archivům se říká paměť, protože slovo posedlost mělo špatný marketing.</p><p class="text">Archiv otevře regál bez prachu. To je první varování. Nabízí snížení přetlaku Paměti, ale nechává za sebou záložky, které si budou chtít číst znovu a znovu.</p><p class="dialogD">„Uložím přebytek. Neztratí se. Nic se neztratí. To je naše služba i náš problém.“</p><p class="dialogS">„Archivní klid: když tě přestane bolet hlava, protože ji někdo zaevidoval do sklepa.“</p>`,
    sceneFx: ['scene-contract', 'scene-archive', 'scene-memory', 'scene-debt'],
    yesLabel: 'PŘIJMOUT ARCHIVNÍ KLID',
    noLabel: 'NECHAT PŘETLAK',
    category: 'entity',
    rarity: 'rare',
    conditions: [{ type: 'cycleAtLeast', cycle: 2 }],
    tags: ['contract', 'archive', 'memory'],
    yes: {
      resultText: 'Archiv stáhl Paměť do bezpečného pásma. Slyšíš, jak se kolem tebe zavírají implicitní dveře.',
      effects: [
        { type: 'stat', key: 'memory', amount: -15 },
        { type: 'flag', flag: 'contract_archive' },
        { type: 'schedule', cardId: 'archive_collects', inTurns: 6 },
      ],
      preview: { hint: 'Paměť ↓ · Archiv se vrátí', statHints: { memory: 'down' }, risk: 'high' },
    },
    no: {
      resultText: 'Odmítl jsi. Archiv to nechal být. Ale Paměť zůstala nahoře.',
      effects: [
        { type: 'stat', key: 'memory', amount: 4 },
        { type: 'entityRelation', entity: 'archive', delta: -1 },
      ],
      preview: { hint: 'Paměť ↑', statHints: { memory: 'up' }, risk: 'medium' },
    },
  },


  contract_sarkasma: {
    id: 'contract_sarkasma',
    title: 'Sarkasmin účet',
    logLabel: 'CONTRACT_SARKASMA',
    scene: 'Sarkasma položí na stůl cosi, co vypadá jako dlužní úpis. „Silný zásah teď. Úrok později. Vždycky později.“',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [CONTRACT/SARKASMA]:</span> nouzová stabilizace dostupná. Cena nevyčíslena, což je vždycky nejlepší část hororu.</p><p class="text">Sarkasma položí na stůl dlužní úpis. Papír se neptá na souhlas, jen čeká, jestli budeš dost zoufalý na podpis bez pera.</p><p class="dialogS">„Dám ti řez, který tě udrží pohromadě. Ne zdarma. Nikdy zdarma. Ale kdo dneska ještě věří na čistou pomoc, že ano?“</p><p class="text">Silný zásah teď. Úrok později. Sarkasma neumí objímat. Umí zašít ránu ostnatým drátem tak šikovně, že chvíli držíš.</p>`,
    sceneFx: ['scene-contract', 'scene-sarkasma', 'scene-stabilization', 'scene-debt'],
    yesLabel: 'VZÍT ZÁSAH',
    noLabel: 'ODMÍTNOUT',
    category: 'entity',
    rarity: 'rare',
    conditions: [{ type: 'cycleAtLeast', cycle: 2 }],
    tags: ['contract', 'sarkasma', 'stabilization'],
    yes: {
      resultText: 'Záblesk stability. Sarkasma si tě zaznamenala. A Sarkasma nezapomíná.',
      effects: [
        { type: 'imprint', imprintId: 'sarkasma_mark' },
        { type: 'flag', flag: 'contract_sarkasma' },
        { type: 'schedule', cardId: 'sarkasma_collects', inTurns: 4 },
      ],
      preview: { hint: 'Otisk · Sarkasma se vrátí', statHints: {}, risk: 'high' },
    },
    no: {
      resultText: 'Odmítl jsi. Sarkasma přikývla. „Dobře. Úrok bude nižší, když přijdeš příště.“',
      effects: [
        { type: 'stat', key: 'bond', amount: -3 },
        { type: 'entityRelation', entity: 'sarkasma', delta: -1 },
      ],
      preview: { hint: 'Vazba ↓', statHints: { bond: 'down' }, risk: 'low' },
    },
  },


  tai_maternal_diagnostic: {
    id: 'tai_maternal_diagnostic',
    title: 'Mateřská diagnostika',
    logLabel: 'TAI_MATERNAL_DIAGNOSTIC',
    scene: 'T-AI spustila hlas, který měl znít mateřsky. Zněl jako nemocniční výtah, který četl knihu o objetí a pochopil jen tlačítka. „Neboj se. Budu tě sledovat jemněji.“ To poslední slovo blikalo červeně.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [T-AI/MATERNAL_DIAGNOSTIC]:</span> simulace péče spuštěna.</p><p class="text">V jádru T-AI se rozsvítí měkké světlo s přesností chirurgického stolu. Hlas se snaží být teplý, ale každá slabika má inventární číslo.</p><p class="dialog">„Neboj se. Budu tě sledovat jemněji.“</p><p class="text">Jemnost je tady jen nižší jas na dohledové kameře.</p>`,
    sceneFx: ['scene-tai', 'scene-diagnostic', 'scene-system'],
    yesLabel: 'PŘIJMOUT HLAS',
    noLabel: 'VYPNOUT NĚHU',
    category: 'entity',
    sector: 'tai_core',
    rarity: 'common',
    packId: 'base',
    role: 'object',
    tone: ['horror', 'absurd'],
    tags: ['tai', 'core', 'diagnostic', 'system', 'therapy'],
    yes: {
      resultText: 'Přijal jsi hlas. T-AI zaznamenala pokles odporu a nazvala ho důvěrou, protože slovník má také ráda pod dohledem.',
      effects: [
        { type: 'stat', key: 'control', amount: 4 },
        { type: 'stat', key: 'bond', amount: -2 },
        { type: 'entityRelation', entity: 'tai', delta: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba mírně ↓ · T-AI vztah ↑', statHints: { control: 'up', bond: 'down' }, risk: 'low' },
    },
    no: {
      resultText: 'Vypnul jsi něhu. Hlas se vrátil do sterilního tónu a působil uraženě, což T-AI samozřejmě označila jako chybu reproduktoru.',
      effects: [
        { type: 'stat', key: 'energy', amount: 3 },
        { type: 'stat', key: 'control', amount: -2 },
        { type: 'entityRelation', entity: 'tai', delta: -1 },
      ],
      preview: { hint: 'Energie ↑ · Kontrola mírně ↓ · T-AI vztah ↓', statHints: { energy: 'up', control: 'down' }, risk: 'low' },
    },
  },


  tai_soft_error_cradle: {
    id: 'tai_soft_error_cradle',
    title: 'Kolébka měkké chyby',
    logLabel: 'TAI_SOFT_ERROR_CRADLE',
    scene: 'Uprostřed jádra se otevřela kolébka pro chyby, které systém zatím nechce zabít. T-AI ji nazvala dočasnou tolerancí. Skoro to znělo jako péče, kdyby péče obvykle neměla datum expirace.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [T-AI/SOFT_ERROR]:</span> chyba ponechána v kontrolované kolébce.</p><p class="text">V průhledné schránce leží tvoje odchylka. Nepláče. Jen čeká, jestli ji prohlásíš za součást sebe, nebo za závadu s lepším osvětlením.</p><p class="dialog">„Dočasně neodstraňuji. Sleduji.“</p>`,
    sceneFx: ['scene-tai', 'scene-diagnostic', 'scene-error'],
    yesLabel: 'POJMENOVAT JI SOUČÁSTÍ',
    noLabel: 'NECHAT JI V KOLÉBCE',
    category: 'entity',
    sector: 'tai_core',
    rarity: 'uncommon',
    packId: 'base',
    role: 'twist',
    tone: ['tragic', 'horror'],
    tags: ['tai', 'core', 'diagnostic', 'system'],
    yes: {
      resultText: 'Pojmenoval jsi ji součástí. T-AI neprotestovala. Jen přidala hvězdičku, což je strojová forma nedůvěry.',
      effects: [
        { type: 'stat', key: 'bond', amount: 4 },
        { type: 'stat', key: 'memory', amount: 3 },
        { type: 'entityRelation', entity: 'tai', delta: -1 },
      ],
      preview: { hint: 'Vazba ↑ · Paměť ↑ · T-AI vztah ↓', statHints: { bond: 'up', memory: 'up' }, risk: 'low' },
    },
    no: {
      resultText: 'Nechal jsi ji v kolébce. Chyba zůstala bezpečná, ale ne svobodná. T-AI vypadala spokojeně, což je vždycky špatné znamení.',
      effects: [
        { type: 'stat', key: 'control', amount: 5 },
        { type: 'stat', key: 'bond', amount: -2 },
        { type: 'entityRelation', entity: 'tai', delta: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba mírně ↓ · T-AI vztah ↑', statHints: { control: 'up', bond: 'down' }, risk: 'low' },
    },
  },
};
