import { createCardRegistry } from './createCardRegistry';
import { SYSTEM_CARDS } from './system.cards';
import { CHOICE_CARDS } from './choice.cards';
import { MEMORY_CARDS } from './memory.cards';
import { OBJECT_CARDS } from './object.cards';
import { FOLLOWUP_CARDS } from './followup.cards';
import { PATH_CARDS } from './path.cards';
import { ENTITY_CARDS } from './entity.cards';
import { CRISIS_CARDS } from './crisis.cards';
import { RESTART_CARDS } from './restart.cards';
import { TUTORIAL_CARDS } from './tutorial.cards';
import { SPECIAL_CARDS } from './special.cards';

export const CYKLUS_CARD_ORDER = [
  'first_boot',
  'emergency_calibration',
  'silent_mode',
  'overclock',
  'archive_compression',
  'noise_filter',
  'auto_repair_patch',
  'forbidden_log',
  'gravity_outage',
  'admin_access',
  'cache_of_pain',
  'faulty_update',
  'manual_mode',
  'disconnect_peripherals',
  'heart_diagnostic',
  'observer_mode',
  'hard_restart',
  'confession_challenge',
  'unknown_process',
  'power_save',
  'incoming_message',
  'rusty_token',
  'glitch_pebble',
  'archive_key',
  'rubber_seal',
  'blank_form',
  'mirror_shard',
  'childhood_spade',
  'acid_filter',
  'wrong_map',
  'black_folder',
  'noise_clump',
  'rusty_token_whispers',
  'glitch_pebble_multiplies',
  'sarkasma_account',
  'archive_key_warms',
  'mirror_shard_hums',
  'childhood_spade_digs',
  'wrong_map_leads',
  'black_folder_rustles',
  'noise_pet_calls',
  'pebble_with_glasses',
  'sarkasma_returns',
  'choose_archive',
  'choose_glitchka_nest',
  'choose_memory_sandbox',
  'choose_sarkasma_terminal',
  'choose_tai_core',
  'choose_acid_yellow',
  'choose_market',
  'choose_mirror',
  'choose_residuum',
  'choose_form_office',
  'crisis_energy_depletion',
  'crisis_energy_overload',
  'crisis_memory_loss',
  'crisis_memory_flood',
  'crisis_bond_abandonment',
  'crisis_bond_suffocation',
  'crisis_control_breakdown',
  'crisis_control_tyranny',
  'restart_0',
  'restart_1',
  'restart_2',
  'restart_3',
  'restart_4',
  'restart_5',
  'entity_sarkasma',
  'entity_glitchka',
  'entity_tai',
  'entity_archive',
  'entity_form',
  'entity_memory_beast',
  'pocket_breathes',
  'pocket_gets_heavy',
  'key_waits',
  'mirror_waits',
  'noise_pet_leaves',
  'memory_beast_returns',
  'unfinished_conversation',
  'rubber_stamp',
  'mirror_crack',
  'sarkasma_debt',
  'noise_resident',
  'childhood_anchor',
  'sarkasma_invoice',
  'token_market_door',
  'token_final_trade',
  'pebble_committee',
  'pebble_constellation',
  'rubber_seal_squeaks',
  'seal_wants_stamp_again',
  'key_in_wrong_office',
  'wrong_map_gives_direction',
  'noise_pet_sings',
  'archive_scent_path',
  'shadow_follows',
  'sarkasma_silent',
  'tai_shortcut_inside',
  'foreign_bookmark',
  'bookmark_knows_more',
  'sector_wrong_name',
  'failed_refusal',
  'two_hallways',
  'too_clean',
  'payment_required',
  'quiet_room',
  'two_explanations',
  'sarkasma_collects',
  'sarkasma_forgives',
  'archive_recognizes_key',
  'mirror_accepts',
  'folder_wrong_name',
  'forbidden_shelf',
  'portal_payment',
  'portal_waits',
  'portal_remembers',
  'mirror_in_archive',
  'form_in_mirror',
  'integrity_check_returns',
  'integrity_breaks_window',
  'tai_notes_ignored',
  'tai_forces_update',
  'silent_room_answer',
  'overclock_invoice',
  'system_overheat',
  'compressed_memory_leaks',
  'memory_files_complaint',
  'pain_cache_interest',
  'token_collector',
  'token_wants_name',
  'unnamed_token_resentment',
  'seal_squeaks',
  'seal_demands_stamp',
  'corridor_breathes',
  'door_refuses_no',
  'door_waits_politely',
  'quiet_room_coat',
  'wall_laughter',
  'wall_laughter_returns',
  'ownerless_shadow',
  'shadow_follows_card',
  'mirror_demands_apology',
  'mirror_shards_argue',
  'wrong_name',
  'wrong_name_returns',
  'market_sells_your_no',
  'someone_buys_your_no',
  'market_receipt_bleeds',
  'replacement_problem',
  'form_smiles',
  'form_misunderstands',
  'form_collects_signature',
  'audit_siren',
  'soft_bug',
  'soft_bug_grows',
  'glitchka_finds_empty_blanket',
  'glitchka_forgot_punchline',
  'energy_dim_light',
  'energy_too_fast',
  'memory_empty_label',
  'memory_flood',
  'bond_thin_signal',
  'bond_overflow',
  'control_unraveling',
  'control_crystal',
  'four_reactors_align',
  'stable_enough',
  'quiet_compromise',
  'seal_of_not_dying_today',
  'archive_recognizes_pattern',
  'sarkasma_comments_death',
  'subject_has_been_here',
  'diagnostic_finding_collector',
  'archive_scent_memory',
  'archive_scent_trace',
  'shutdown_echo',
  'dormant_signal',
  'empty_archive_page',
  'format_survivor_card',
  'last_contact_log',
  'dissolved_boundary_card',
  'perfect_room_card',
  'chaos_residue_card',
  'warm_token_memory',
  'drowned_in_memory_card',
  'tutorial_00_welcome',
  'tutorial_01_swipe',
  'tutorial_02_stats',
  'tutorial_03_balance',
  'tutorial_04_preview',
  'tutorial_04b_junction',
  'tutorial_05_profile',
  'tutorial_06_items',
  'tutorial_07_imprints',
  'tutorial_08_consequences',
  'tutorial_09_sectors',
  'tutorial_10_cycle',
  'tutorial_11_restart',
  'tutorial_12_void',
  'tutorial_13_progression',
  'tutorial_14_packs',
  'tutorial_15_ready',
  'contract_tai',
  'contract_glitchka',
  'contract_archive',
  'contract_sarkasma',
  'tai_collects',
  'glitchka_collects',
  'archive_collects',
  'soft_bug_followup',
  'archival_overload',
  'power_overload',
  'bond_overload',
  'mirror_shadow',
  'token_stamp_combo',
  'bug_pebble_nest',
  'control_overload',
  'memory_flood_echo',
  'acid_afterimage_card',
  'overburn_memorial_card',
  'overclock_memorial_card',
  'empty_contact_list_card',
  'thread_under_door_card',
  'merge_protocol_card',
  'statue_with_pulse_card',
  'audit_of_stillness_card',
  'shattered_protocol_card',
  'blackbox_aftermath_bridge',
  'desire_orgie_threshold',
  'detective_cold_case_folder',
  'tai_maternal_diagnostic',
  'tai_core_temperature',
  'tai_diagnostic_lullaby',
  'tai_soft_error_cradle',
  'tai_permission_mirror',
  'archive_loose_folder',
  'archive_record_margin',
  'archive_form_duplicate',
  'archive_folder_breathes',
  'archive_index_card',
] as const;

export const CYKLUS_CARDS = createCardRegistry(
  CYKLUS_CARD_ORDER,
  { name: 'system', cards: SYSTEM_CARDS },
  { name: 'choice', cards: CHOICE_CARDS },
  { name: 'memory', cards: MEMORY_CARDS },
  { name: 'object', cards: OBJECT_CARDS },
  { name: 'followup', cards: FOLLOWUP_CARDS },
  { name: 'path', cards: PATH_CARDS },
  { name: 'entity', cards: ENTITY_CARDS },
  { name: 'crisis', cards: CRISIS_CARDS },
  { name: 'restart', cards: RESTART_CARDS },
  { name: 'tutorial', cards: TUTORIAL_CARDS },
  { name: 'special', cards: SPECIAL_CARDS },
);
