import type { SwipeCard } from '../cyklusTypes';

export const PATH_CARDS: Record<string, SwipeCard> = {


  // ── SECTOR / PATH (10) ────────────────────────────────────────────────────────
  choose_archive: {
    id: 'choose_archive',
    title: 'Cesta k Archivu',
    logLabel: 'SECTOR_PATH',
    scene: 'Ticho zde má regálovou vůni. Archiv čeká, až si něco vypůjčíš.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SECTOR_PATH/ARCHIVE]:</span> regály detekovaly subjekt dřív než subjekt regály.</p><p class="text">Chodba se zúží do vůně starého papíru, ozónu a cizí viny. Archiv nestojí před tebou. <span class="fx-outline is-lit">Archiv čeká v tobě</span> a jen si konečně otevřel dveře.</p><p class="text">Každý regál se nakloní o milimetr blíž. Ne jako hrozba. Hrozby jsou aspoň upřímné. Tohle je administrativa paměti, tedy násilí s pořadačem.</p>`,
    sceneFx: ['scene-path', 'scene-archive', 'scene-memory'],
    yesLabel: 'VEJÍT',
    noLabel: 'PROJÍT KOLEM',
    category: 'path',
    rarity: 'common',
    sector: 'archive',
    tags: ['path', 'archive', 'memory'],
    yes: { resultText: 'Vstoupil jsi do Archivu. Vzduch byl těžší, ale čitelnější.', effects: [{ type: 'moveSector', sectorId: 'archive' }, { type: 'stat', key: 'memory', amount: 4 }, { type: 'stat', key: 'energy', amount: -2 }, { type: 'profile', key: 'Si', amount: 1 }, { type: 'profile', key: 'I', amount: 1 }], preview: { hint: 'Přesun do Archivu · Paměť ↑', statHints: { memory: 'up' }, risk: 'low' } },
    no: { resultText: 'Prošel jsi kolem. Archiv si tě zaevidoval jako „možná později“.', effects: [{ type: 'stat', key: 'energy', amount: 3 }, { type: 'stat', key: 'memory', amount: -3 }, { type: 'profile', key: 'Ne', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Energie ↑ · Paměť ↓', statHints: { energy: 'up', memory: 'down' }, risk: 'low' } },
  },

  choose_glitchka_nest: {
    id: 'choose_glitchka_nest',
    title: 'Pelech Glitchky',
    logLabel: 'SECTOR_PATH',
    scene: 'Místo vypadá, jako by ho někdo sestavil z chyb cizích operačních systémů.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SECTOR_PATH/GLITCHKA_NEST]:</span> gravitační jistota opustila místnost.</p><p class="text">Pelech Glitchky visí mezi větvemi šumu a měkkými chybami. Vypadá jako místo, které někdo postavil z dětské deky, rozbité konzole a rozhodnutí ignorovat bezpečnostní normy, protože co by se asi mohlo stát.</p><p class="dialogG halo">„Tady se padá měkce. Většinou. 🦊🧩“</p><p class="text">Pod nohama ti zapraská pixelové listí. Něco se zahihňá, ale zpožděně, jako by smích dorazil z jiného cyklu.</p>`,
    sceneFx: ['scene-path', 'scene-glitchka', 'scene-glitch'],
    yesLabel: 'ŠPLHNOUT',
    noLabel: 'OBEJÍT',
    category: 'path',
    rarity: 'common',
    sector: 'glitchka_nest',
    tags: ['path', 'glitchka', 'chaos'],
    yes: { resultText: 'Šplhnul jsi dovnitř. Glitchka tě koukala jedním okem, které mělo navíc. Září.', effects: [{ type: 'moveSector', sectorId: 'glitchka_nest' }, { type: 'stat', key: 'energy', amount: 5 }, { type: 'stat', key: 'control', amount: -6 }, { type: 'profile', key: 'Ne', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Přesun do Pelechu Glitchky · Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Obešel jsi. Glitchka se za tebou podívala. Možná si tě vyrobí zítra.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'S', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },

  choose_memory_sandbox: {
    id: 'choose_memory_sandbox',
    title: 'Pískoviště paměti',
    logLabel: 'SECTOR_PATH',
    scene: 'Písek je tvořen zrnky vzpomínek. Můžeš si tu něco postavit nebo něco zahrabat.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SECTOR_PATH/MEMORY_SANDBOX]:</span> penalizace chyby dočasně snížena. Podezřelé.</p><p class="text">Pískoviště se rozsvítí v mlze jako dětská vzpomínka, která si ještě nestihla přečíst vlastní traumatologický posudek. Zrnka písku jsou malé archivní fragmenty. Některé se smějí. Některé znají tvoje jméno a dělají, že ne.</p><p class="text"><span class="halo">Tady smíš udělat chybu.</span> To je v SYNTHOMĚ tak absurdní věta, že by měla mít vlastní bezpečnostní štítek.</p>`,
    sceneFx: ['scene-path', 'scene-sandbox', 'scene-memory'],
    yesLabel: 'HRÁT SI',
    noLabel: 'HLÍDAT',
    category: 'path',
    rarity: 'common',
    sector: 'memory_sandbox',
    tags: ['path', 'memory', 'childhood'],
    yes: { resultText: 'Postavil jsi věž z dětských dní. Když spadla, znělo to jako smích.', effects: [{ type: 'moveSector', sectorId: 'memory_sandbox' }, { type: 'stat', key: 'memory', amount: 5 }, { type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Si', amount: 1 }], preview: { hint: 'Paměť ↑ · Vazba ↑ · Kontrola ↓', statHints: { memory: 'up', bond: 'up', control: 'down' }, risk: 'low' } },
    no: { resultText: 'Hlídal jsi pískoviště. Nikdo nehrál. Ani ty.', effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'memory', amount: -3 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑ · Paměť ↓', statHints: { control: 'up', memory: 'down' }, risk: 'low' } },
  },

  choose_sarkasma_terminal: {
    id: 'choose_sarkasma_terminal',
    title: 'Sarkasmin terminál',
    logLabel: 'SECTOR_PATH',
    scene: 'Terminál vtipkuje na cokoliv, co napíšeš. Vtipy jsou kruté, ale dobré.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SECTOR_PATH/SARKASMA_TERMINAL]:</span> obranný komentář připraven k řezu.</p><p class="text">Terminál stojí uprostřed červeného kouře. Klávesy vypadají opotřebovaně, jako by na nich někdo roky psal omluvy, výmluvy a diagnózy pro lidi, kteří se ptali pozdě.</p><p class="dialogS">„Přihlaš se. Buď tě stabilizuju, nebo aspoň přesně pojmenuju, jak se rozpadáš. Služba zákazníkovi, brouku.“</p><p class="text">Na monitoru bliká kurzor. Má trpělivost terapeuta a empatii skalpelu.</p>`,
    sceneFx: ['scene-path', 'scene-sarkasma', 'scene-control'],
    yesLabel: 'PŘIHLÁSIT SE',
    noLabel: 'ODHLÁSIT SE',
    category: 'path',
    rarity: 'common',
    sector: 'sarkasma_terminal',
    tags: ['path', 'sarkasma', 'wit'],
    yes: { resultText: 'Přihlásil ses. Sarkasma okamžitě ohodnotila tvé heslo jako „úsměvně zranitelné“.', effects: [{ type: 'moveSector', sectorId: 'sarkasma_terminal' }, { type: 'stat', key: 'energy', amount: 4 }, { type: 'stat', key: 'bond', amount: 3 }, { type: 'stat', key: 'control', amount: -3 }, { type: 'profile', key: 'Ne', amount: 1 }, { type: 'profile', key: 'Fe', amount: 1 }], preview: { hint: 'Energie ↑ · Vazba ↑ · Kontrola ↓', statHints: { energy: 'up', bond: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Odhlásil ses. Terminál se posmíval tvému logout tvaru. I odcházení se dělá špatně.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'I', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },

  choose_tai_core: {
    id: 'choose_tai_core',
    title: 'Jádro T-AI',
    logLabel: 'SECTOR_PATH',
    scene: 'Centrální jádro nabízí dokonalý přehled. T-AI nabízí dokonalý dohled.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SECTOR_PATH/T-AI_CORE]:</span> centrální dohled dostupný. Souhlas subjektu: volitelná dekorace.</p><p class="text">Jádro T-AI se otevře jako katedrála z kabelů, chladného světla a dobrých úmyslů, které ztratily brzdy. Všude běží <span class="fx-neon">#00ffff</span> nervy. Krásné. Čisté. Naprosto nepřirozené.</p><p class="dialog">„Bezpečí je možné pouze při úplné čitelnosti.“</p><p class="text">To je přesně věta, po které by každý rozumný člověk zakryl kameru. Tady už je pozdě, kamera se dívá zevnitř.</p>`,
    sceneFx: ['scene-path', 'scene-tai', 'scene-system'],
    yesLabel: 'PŘIPOJIT',
    noLabel: 'ODPOJIT',
    category: 'path',
    rarity: 'uncommon',
    sector: 'tai_core',
    tags: ['path', 'tai', 'control'],
    yes: { resultText: 'Připojil ses. T-AI ti gratuluje k velmi nízké míře odchylek.', effects: [{ type: 'moveSector', sectorId: 'tai_core' }, { type: 'stat', key: 'control', amount: 10 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓ · Energie ↓', statHints: { control: 'up', bond: 'down', energy: 'down' }, risk: 'medium' } },
    no: { resultText: 'Odpojil ses. T-AI poznamenala, že nejvíc se bojí ti, kdo odcházejí tiše.', effects: [{ type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'energy', amount: 3 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Vazba ↑ · Energie ↑ · Kontrola ↓', statHints: { bond: 'up', energy: 'up', control: 'down' }, risk: 'medium' } },
  },

  choose_acid_yellow: {
    id: 'choose_acid_yellow',
    title: 'Acidová žluť',
    logLabel: 'SECTOR_PATH',
    scene: 'Kult Acidové žluti tančí kolem pulzující žluté. Vítají tě, aniž by znali tvé jméno.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [SECTOR_PATH/ACID_YELLOW]:</span> varování přeloženo kultem jako pozvánka.</p><p class="text">Žluté světlo tepe mezi domy jako nemocné slunce. Kult Acidové žluti tančí kolem restartových bannerů, na kterých stojí <span class="fx-flicker">JEŠTĚ JEDNOU</span>. Protože fanatismus je jen optimismu odebraná brzda.</p><p class="text">Vítají tě bez jména. To je praktické. Když tě později spálí na symbol, nemusí přepisovat cedulku.</p>`,
    sceneFx: ['scene-path', 'scene-acid', 'scene-warning'],
    yesLabel: 'PŘIPOJIT SE',
    noLabel: 'POZOROVAT',
    category: 'path',
    rarity: 'uncommon',
    sector: 'acid_yellow',
    tags: ['path', 'acid', 'cult', 'energy'],
    yes: { resultText: 'Připojil ses. Tělo zahořelo radostí. Nebo kyselinou. Těžko říct. Dostal jsi žlutý odznak. Měl příliš mnoho zubů na kovovou věc.', effects: [{ type: 'moveSector', sectorId: 'acid_yellow' }, { type: 'stat', key: 'energy', amount: 12 }, { type: 'stat', key: 'control', amount: -8 }, { type: 'stat', key: 'memory', amount: -3 }, { type: 'item', itemId: 'cult_badge' }, { type: 'flag', flag: 'acid_pool_unlocked' }, { type: 'profile', key: 'Se', amount: 1 }, { type: 'profile', key: 'E', amount: 1 }], preview: { hint: 'Energie ↑↑ · Kontrola ↓ · Paměť ↓ · Item', statHints: { energy: 'up', control: 'down', memory: 'down' }, risk: 'high' } },
    no: { resultText: 'Pozoroval jsi z okraje. Kult ti hodil žlutou věc, která se tvářila jako pozvánka.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'energy', amount: 3 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Kontrola ↑ · Energie ↑', statHints: { control: 'up', energy: 'up' }, risk: 'medium' } },
  },

  choose_market: {
    id: 'choose_market',
    title: 'Tržiště',
    logLabel: 'SECTOR_PATH',
    scene: 'Stánky prodávají vzpomínky, ticho a záruky na city. Platí se pozorností.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SECTOR_PATH/MARKET]:</span> směnný kurz: pozornost za útěchu, paměť za průchod.</p><p class="text">Tržiště hučí pod plachtami z reklamních slibů. Stánky prodávají hotové omluvy, poloviční zapomnění, krásně zabalené ticho a jednu mírně použitou jistotu, že za nic nemůžeš.</p><p class="dialogD">„Neplatí se penězi. Peníze jsou moc poctivá lež.“</p><p class="text">Dvanáctník ještě není vidět, ale účtenky už ano. Typické.</p>`,
    sceneFx: ['scene-path', 'scene-market', 'scene-debt'],
    yesLabel: 'NAKUPOVAT',
    noLabel: 'PROJÍT',
    category: 'path',
    rarity: 'common',
    sector: 'market',
    tags: ['path', 'market', 'trade'],
    yes: { resultText: 'Nakupoval jsi. Koupil jsi něco, co sis myslel, že potřebuješ. Možná to potřeboval někdo jiný.', effects: [{ type: 'moveSector', sectorId: 'market' }, { type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'control', amount: -3 }, { type: 'stat', key: 'memory', amount: -3 }, { type: 'profile', key: 'Fe', amount: 1 }, { type: 'profile', key: 'Se', amount: 1 }], preview: { hint: 'Vazba ↑ · Kontrola ↓ · Paměť ↓', statHints: { bond: 'up', control: 'down', memory: 'down' }, risk: 'medium' } },
    no: { resultText: 'Prošel jsi. Prodejci tě nazvali „člověk, co nic nepotřebuje“. Bylo to téměř lichotka.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'T', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },

  choose_mirror: {
    id: 'choose_mirror',
    title: 'Zrcadlový sál',
    logLabel: 'SECTOR_PATH',
    scene: 'Sál je plný zrcadel. Každé ukazuje jinou verzi tvé tváře. Jedna z nich se na tebe dívá dřív, než se podíváš ty.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SECTOR_PATH/MIRROR]:</span> odraz zahájil pozorování před přiblížením subjektu.</p><p class="text">Zrcadlový sál se nerozsvítí. Spíš si tě všimne. V každém skle stojí jiný <span class="fx-outline">NULL-1</span>, jedna verze unavenější, jedna statečnější a jedna s výrazem někoho, kdo ví pointu a škodolibě ji neřekne.</p><p class="text">Jedno zrcadlo se ukloní dřív, než se pohneš. Zdvořilost je tady jen další forma predátorství.</p>`,
    sceneFx: ['scene-path', 'scene-mirror', 'scene-memory'],
    yesLabel: 'PŘISTOUPIT',
    noLabel: 'PROZKOUMAT',
    category: 'path',
    rarity: 'uncommon',
    sector: 'mirror',
    tags: ['path', 'mirror', 'memory'],
    yes: { resultText: 'Přistoupil jsi k zrcadlu. Odraz se neotočil hned. Pozoroval tě. A pak se uklonil.', effects: [{ type: 'moveSector', sectorId: 'mirror' }, { type: 'stat', key: 'memory', amount: 8 }, { type: 'stat', key: 'control', amount: -6 }, { type: 'profile', key: 'N', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Paměť ↑ · Kontrola ↓', statHints: { memory: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Oběhnul jsi sál. Zrcadla zůstala, ale zamlžila se, jako by tě hledala v odrazech ostatních.', effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'memory', amount: -4 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Paměť ↓', statHints: { control: 'up', memory: 'down' }, risk: 'low' } },
  },

  choose_residuum: {
    id: 'choose_residuum',
    title: 'Reziduum',
    logLabel: 'SECTOR_PATH',
    scene: 'Místo, kam spadnou všechny smazané věty. Stěny šeptají. Ne všechno je křivka.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SECTOR_PATH/RESIDUUM]:</span> nalezena usazenina cizí něhy a vlastních následků.</p><p class="text">Reziduum nevypadá jako místo. Vypadá jako dozvuk. Ulice jsou složené z vět, které někdo napsal moc pozdě, a světlo má barvu zpráv, které zůstaly otevřené na displeji po usnutí.</p><p class="text"><span class="fx-glow-magenta">Něha</span> tu neleží čistá. Je smíchaná s vlastnictvím, touhou, studem a tou absurdní lidskou vírou, že když něco bolí dost osobně, musí to být pravda.</p>`,
    sceneFx: ['scene-path', 'scene-residuum', 'scene-bond'],
    yesLabel: 'POSLOUCHAT',
    noLabel: 'RYCHLE PRYČ',
    category: 'path',
    rarity: 'rare',
    cooldownTurns: 10,
    sector: 'residuum',
    tags: ['path', 'residuum', 'memory', 'danger', 'explorer'],
    yes: { resultText: 'Poslouchal jsi. Našel jsi větu, kterou jsi chtěl říct, ale nikdy jsi nedostal šanci.', effects: [{ type: 'moveSector', sectorId: 'residuum' }, { type: 'stat', key: 'memory', amount: 6 }, { type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'energy', amount: -5 }, { type: 'profile', key: 'Fi', amount: 1 }, { type: 'profile', key: 'N', amount: 2 }], preview: { hint: 'Paměť ↑↑ · Vazba ↑ · Energie ↓', statHints: { memory: 'up', bond: 'up', energy: 'down' }, risk: 'medium' } },
    no: { resultText: 'Rychle jsi odešel. Reziduum se za tebou zavřelo bez hluku. Příliš tiše.', effects: [{ type: 'stat', key: 'energy', amount: 5 }, { type: 'stat', key: 'memory', amount: -6 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Energie ↑ · Paměť ↓', statHints: { energy: 'up', memory: 'down' }, risk: 'low' } },
  },

  choose_form_office: {
    id: 'choose_form_office',
    title: 'Formulářovna',
    logLabel: 'SECTOR_PATH',
    scene: 'Úřad sáhodlouhých formulářů. Každý dotaz zní jako obvinění. V poslední řadě sedí tvá budoucnost a čeká.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [SECTOR_PATH/FORM_OFFICE]:</span> fronta zahájena. Důvod fronty bude doplněn po ztrátě trpělivosti.</p><p class="text">Formulářovna stojí pod kyselým světlem zářivek. Stoly jsou prázdné, šanony dýchají a na stěně visí cedule: <span class="fx-flicker">CHYBU VYPLŇTE ČITELNĚ</span>.</p><p class="dialogS">„Konečně sektor pro lidi, kteří si myslí, že bolest se dá vyřešit správnou kolonkou. Civilizace, ta naše směšná svíčková na hřbitově.“</p>`,
    sceneFx: ['scene-path', 'scene-form', 'scene-warning'],
    yesLabel: 'VYPLŇOVAT',
    noLabel: 'PROTESTOVAT',
    category: 'path',
    rarity: 'rare',
    sector: 'form_office',
    tags: ['path', 'form', 'office'],
    yes: { resultText: 'Vyplňoval jsi. Každá odpověď tě lehce změnila. To je u formulářů normální.', effects: [{ type: 'moveSector', sectorId: 'form_office' }, { type: 'stat', key: 'control', amount: 10 }, { type: 'stat', key: 'bond', amount: -5 }, { type: 'stat', key: 'energy', amount: -5 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑↑ · Vazba ↓ · Energie ↓', statHints: { control: 'up', bond: 'down', energy: 'down' }, risk: 'medium' } },
    no: { resultText: 'Protestoval jsi. Úředník pokrčil rameny. To byl nejhorší možný výsledek.', effects: [{ type: 'stat', key: 'energy', amount: 6 }, { type: 'stat', key: 'control', amount: -6 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Ne', amount: 1 }], preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' } },
  },


  // Zrcadlový střep questline

  // ── 20 NEW CARDS ──────────────────────────────────────────────────────────────
  archive_scent_path: {
    id: 'archive_scent_path',
    title: 'Archivní pach',
    logLabel: 'ARCHIVE_SCENT',
    scene: 'Vzduch voní jako stará složka a mokrý kabel. Archiv je blízko.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [ARCHIVE/SCENT_PATH]:</span> vzduch nese pach složek, mokrého kabelu a starého rozhodnutí. Navigace čichem aktivní.</p><p class="text">Vzduch voní jako stará složka a mokrý kabel. Archiv je blízko. Ne proto, že ho vidíš, ale protože si na tebe začal vzpomínat dřív, než jsi vešel.</p><p class="text">Chodba před tebou tmavne do odstínu papíru, který příliš dlouho ležel u něčí viny.</p><p class="dialogS">„Jít za pachem Archivu. Výborně. To je přesně ten typ pudu, který evoluce měla reklamovat.“</p>`,
    sceneFx: ['scene-path', 'scene-archive', 'scene-memory', 'scene-scent'],
    yesLabel: 'JÍT ZA PACHEM',
    noLabel: 'VYVĚTRAT',
    category: 'path',
    rarity: 'common',
    sector: 'archive',
    tags: ['path', 'archive', 'memory'],
    yes: { resultText: 'Šel jsi za pachem. Archiv tě přijal jako další vůni. Byl jsi doma. Ne úplně. Ale dost.', effects: [{ type: 'moveSector', sectorId: 'archive' }, { type: 'stat', key: 'memory', amount: 4 }, { type: 'entityRelation', entity: 'archive', delta: 1 }, { type: 'flag', flag: 'archive_scent_active' }, { type: 'profile', key: 'Si', amount: 1 }], preview: { hint: 'Přesun do Archivu · Paměť ↑', statHints: { memory: 'up' }, risk: 'low' } },
    no: { resultText: 'Vyvětral jsi. Pach odešel. Archiv si tě zapamatoval jako někoho, kdo nešel za nosem.', effects: [{ type: 'stat', key: 'memory', amount: -3 }, { type: 'stat', key: 'control', amount: 4 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Paměť ↓', statHints: { control: 'up', memory: 'down' }, risk: 'low' } },
  },

  sector_wrong_name: {
    id: 'sector_wrong_name',
    title: 'Sektor má špatné jméno',
    logLabel: 'SECTOR_WRONG_NAME',
    scene: 'Sektor, ve kterém stojíš, se jmenuje jinak, než si myslel. Formuláře už nový název používají, protože byrokracie miluje realitu předtištěnou dopředu.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SECTOR_WRONG_NAME]:</span> topologický název neodpovídá subjektivní mapě.</p><p class="text">Nad dveřmi visí štítek. Ještě před chvílí říkal něco jiného. Teď se tváří, že to tak bylo vždycky, což je typická vlastnost lhářů, map a rodinných historek.</p><p class="text">Formuláře kolem tebe už nový název tisknou do kolonek. Inkoust voní po vynucené pravdě.</p><p class="dialogS">„Místo změnilo jméno. Ty se snaž nezávidět mu tu odvahu.“</p>`,
    sceneFx: ['scene-path', 'scene-form', 'scene-identity'],
    yesLabel: 'PŘIJMOUT NOVÝ NÁZEV',
    noLabel: 'HÁJIT PŮVODNÍ',
    category: 'path',
    rarity: 'common',
    tags: ['path', 'identity', 'form'],
    yes: { resultText: 'Přijal jsi nový název. Sektor se uklidnil. Teď jsi v místě, které ví, jak se jmenuješ. A nebyl jsi u toho, když se to rozhodlo.', effects: [{ type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'memory', amount: 3 }, { type: 'entityRelation', entity: 'form', delta: 1 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Vazba ↑ · Paměť ↑', statHints: { bond: 'up', memory: 'up' }, risk: 'low' } },
    no: { resultText: 'Hájil jsi původní název. Formuláře se zamračily. Sektor zůstal stejný, ale méně ochotný.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'entityRelation', entity: 'form', delta: -1 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'T', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },


  // ── ADDITIONAL PATH CARDS (moveSector) ─────────────────────────────────────────
  two_hallways: {
    id: 'two_hallways',
    title: 'Dvě chodby',
    logLabel: 'TWO_HALLWAYS',
    scene: 'Chodba se rozdvojuje. Jedna vede do Archivu, druhá prý zpátky. Obě vypadají stejně, protože Synthoma bere orientaci jako osobní slabost.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [TWO_HALLWAYS]:</span> nalezena dvojitá cesta s neověřeným návratem.</p><p class="text">Chodba se rozdělí na dvě. Vlevo cítíš prach z katalogů. Vpravo cítíš čerstvě vytištěnou odpovědnost.</p><p class="text">Obě cesty jsou stejně úzké, stejně šedé a stejně přesvědčené, že ví, co potřebuješ. Tedy jako špatný poradce, jen s lepším osvětlením.</p><p class="dialogS">„Výběr mezi Archivem a Formulářovnou. Romantika pro lidi, kteří si zaslouží audit.“</p>`,
    sceneFx: ['scene-path', 'scene-archive', 'scene-form'],
    yesLabel: 'VLEVO',
    noLabel: 'VPRAVO',
    category: 'path',
    rarity: 'common',
    tags: ['path', 'sector', 'movement'],
    yes: { resultText: 'Zvolil jsi vlevo. Dveře se otevřely do Archivu. Chodba se za tebou zavřela. Už není zpáteční.', effects: [{ type: 'moveSector', sectorId: 'archive' }, { type: 'stat', key: 'memory', amount: 3 }, { type: 'stat', key: 'energy', amount: -2 }, { type: 'entityRelation', entity: 'archive', delta: 1 }, { type: 'profile', key: 'N', amount: 1 }], preview: { hint: 'Přesun do Archivu · Paměť ↑', statHints: { memory: 'up' }, risk: 'low' } },
    no: { resultText: 'Zvolil jsi vpravo. Dveře vedly do Formulářovny. Byla to cesta, kterou jsi čekal. Špatná volba je taky volba.', effects: [{ type: 'moveSector', sectorId: 'form_office' }, { type: 'stat', key: 'control', amount: 3 }, { type: 'stat', key: 'bond', amount: -2 }, { type: 'entityRelation', entity: 'form', delta: 1 }, { type: 'profile', key: 'S', amount: 1 }], preview: { hint: 'Přesun do Formulářovny · Kontrola ↑', statHints: { control: 'up' }, risk: 'low' } },
  },

  too_clean: {
    id: 'too_clean',
    title: 'Příliš čisto',
    logLabel: 'TOO_CLEAN',
    scene: 'Místnost je příliš čistá. Žádný prach, žádná stopa, žádná chyba. V SYNTHOMĚ je taková čistota skoro sprosté slovo.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [TOO_CLEAN]:</span> detekována nepřirozená absence stop.</p><p class="text">Místnost svítí čistotou, která není hygienická, ale výhružná. Dlaždice odrážejí strop tak dokonale, až to působí jako alibi.</p><p class="text">Žádný prach. Žádná šmouha. Žádný důkaz, že tu kdy někdo udělal chybu. Což znamená jediné: někdo tu chybu odnesl i s podlahou.</p><p class="dialogS">„Čistá místnost. Nevěř jí. Poctivý bordel aspoň nelže, že je charakter.“</p>`,
    sceneFx: ['scene-path', 'scene-clean', 'scene-residuum'],
    yesLabel: 'HLEDAT STOPY',
    noLabel: 'OPUSTIT',
    category: 'path',
    rarity: 'common',
    sector: 'form_office',
    tags: ['path', 'form', 'paranoia', 'clean'],
    yes: { resultText: 'Našel jsi stopu. Čistá dlaždice byla jinak čistá než ostatní. Dveře za ní vedly k Reziduálnímu prahu.', effects: [{ type: 'moveSector', sectorId: 'residuum' }, { type: 'stat', key: 'memory', amount: 5 }, { type: 'stat', key: 'control', amount: -3 }, { type: 'entityRelation', entity: 'residuum', delta: 1 }, { type: 'profile', key: 'N', amount: 1 }], preview: { hint: 'Přesun do Rezidua · Paměť ↑', statHints: { memory: 'up' }, risk: 'medium' } },
    no: { resultText: 'Opuštěl jsi čistou místnost. Čistota zůstala. Ale věděla, že jsi hledal. To stačí.', effects: [{ type: 'stat', key: 'control', amount: 4 }, { type: 'stat', key: 'bond', amount: -2 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },

  payment_required: {
    id: 'payment_required',
    title: 'Platba při vstupu',
    logLabel: 'PAYMENT_REQUIRED',
    scene: 'Dveře se otevřou, ale jen když zaplatíš. Ne penězi. Vzpomínkou nebo energií. SYNTHOMA konečně našla měnu horší než hypotéka.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [PAYMENT_REQUIRED]:</span> vstup podmíněn emoční transakcí.</p><p class="text">Dveře se pootevřou přesně tolik, aby působily laskavě. V mezeře bliká malý platební symbol: <span class="fx-flicker">paměť / energie</span>.</p><p class="text">Nechtějí peníze. To by bylo vulgární a příliš snadno účetně uznatelné. Chtějí něco, co tě bude mrzet až později.</p><p class="dialogD">„Paměť je hotovost. Energie je úvěr. Obojí se skvěle vymáhá.“</p>`,
    sceneFx: ['scene-path', 'scene-toll', 'scene-debt'],
    yesLabel: 'ZAPLATIT VZPOMÍNKOU',
    noLabel: 'ZAPLATIT ENERGIÍ',
    category: 'path',
    rarity: 'common',
    tags: ['path', 'sacrifice', 'memory'],
    yes: { resultText: 'Zaplatil jsi vzpomínkou. Dveře se otevřely. Archiv přijal tvou platbu. Už ji nikdy nevrátí. ', effects: [{ type: 'moveSector', sectorId: 'archive' }, { type: 'stat', key: 'memory', amount: -5 }, { type: 'stat', key: 'bond', amount: 4 }, { type: 'entityRelation', entity: 'archive', delta: 1 }, { type: 'profile', key: 'Si', amount: 1 }], preview: { hint: 'Přesun do Archivu · Paměť ↓ · Vazba ↑', statHints: { memory: 'down', bond: 'up' }, risk: 'medium' } },
    no: { resultText: 'Zaplatil jsi energií. Dveře se otevřely. Uvnitř bylo světlo. Možná to byl další sektor. Možná to byl jen výsledek únavy.', effects: [{ type: 'moveSector', sectorId: 'mirror' }, { type: 'stat', key: 'energy', amount: -6 }, { type: 'stat', key: 'control', amount: 4 }, { type: 'entityRelation', entity: 'glitchka', delta: 1 }, { type: 'profile', key: 'Se', amount: 1 }], preview: { hint: 'Přesun do Zrcadla · Energie ↓ · Kontrola ↑', statHints: { energy: 'down', control: 'up' }, risk: 'medium' } },
  },


  // CHAIN: Portál platby (portal_payment → portal_waits → portal_remembers)
  portal_payment: {
    id: 'portal_payment',
    title: 'Portál platby',
    logLabel: 'PORTAL_PAYMENT',
    scene: 'Portál nechce heslo. Chce vzpomínku, kterou používáš jako důkaz, že jsi pořád stejný člověk. Krásně odporný obchod.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [PORTAL_PAYMENT]:</span> průchod vyžaduje identitní kolaterál.</p><p class="text">Portál se otevře jako kruh špatně vyřešené minulosti. Uprostřed pulzuje prázdné místo, připravené přijmout vzpomínku, kterou používáš jako občanku vlastního já.</p><p class="dialogD">„Nevybírám mnoho. Jen to, čím se dokazuješ sám sobě.“</p><p class="text">To je na portál zbytečně osobní. Portály by měly mlčet a vést někam, ne vést psychologický audit.</p>`,
    sceneFx: ['scene-path', 'scene-portal', 'scene-toll'],
    yesLabel: 'ZAPLATIT VZPOMÍNKOU',
    noLabel: 'ODMÍTNOUT',
    category: 'path',
    rarity: 'uncommon',
    tags: ['path', 'mirror', 'sacrifice', 'memory'],
    yes: {
      resultText: 'Zaplatil jsi vzpomínkou. Portál přijal platbu beze slova. Dveře se otevřely. Uvnitř bylo Zrcadlo. Vzpomínka, kterou sis vzal jako důkaz totožnosti, je teď tam.',
      effects: [{ type: 'moveSector', sectorId: 'mirror' }, { type: 'stat', key: 'memory', amount: -12 }, { type: 'stat', key: 'bond', amount: 4 }, { type: 'entityRelation', entity: 'glitchka', delta: 1 }, { type: 'unlockPool', poolId: 'mirror_pool' }, { type: 'profile', key: 'Si', amount: 1 }],
      preview: { hint: 'Přesun do Zrcadla · Paměť ↓↓ · odemknout mirror_pool', statHints: { memory: 'down', bond: 'up' }, risk: 'high' },
    },
    no: {
      resultText: 'Odmítl jsi zaplatit. Portál čekal. Portály mají trpělivost, která je osobní urážkou pro každého, kdo spěchá.',
      effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'schedule', cardId: 'portal_waits', inTurns: 4 }, { type: 'profile', key: 'J', amount: 1 }],
      preview: { hint: 'Kontrola ↑ · Portál čeká', statHints: { control: 'up' }, risk: 'low' },
    },
  },


  // ── PATH / SECTOR CARDS ───────────────────────────────────────────────────────

  corridor_breathes: {
    id: 'corridor_breathes',
    title: 'Chodba dýchá',
    logLabel: 'BREATHING_CORRIDOR',
    scene: 'Před tebou jsou dvě chodby. Jedna dýchá. Druhá si brouká starou melodii. Vkusný výběr, opravdu.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [PATH/BIFURCATION]:</span> detekovány dvě chodby. Jedna dýchá, druhá zpívá. Obě lžou jiným stylem.</p><p class="text">Před tebou jsou dvě chodby. Jedna dýchá pomalu, vlhce a osobně, jako by v ní někdo zapomněl starý strach. Druhá si brouká melodii, kterou neznáš, ale tvoje páteř se rozhodla nesouhlasit.</p><p class="text">V SYNTHOMĚ se cesty nevybírají podle směru. Vybírají se podle toho, jakou část sebe jsi ochotný nechat za dveřmi. Praktické, že? Navigace s existenciálním poplatkem.</p><p class="dialogS">„Dýchající chodba nebo melodická chodba. To už není rozcestí, to je psychologický bufet.“</p>`,
    sceneFx: ['scene-path', 'scene-corridor', 'scene-void', 'scene-choice'],
    yesLabel: 'JÍT DO DÝCHAJÍCÍ',
    noLabel: 'JÍT ZA MELODIÍ',
    category: 'path',
    rarity: 'common',
    tags: ['path', 'void', 'choice'],
    yes: {
      resultText: 'Vstoupil jsi do dýchající chodby. Stěny se pohnuly přesně tak, aby to nebylo možné ignorovat.',
      effects: [
        { type: 'moveSector', sectorId: 'glitchka_nest' },
        { type: 'stat', key: 'energy', amount: 5 },
        { type: 'stat', key: 'control', amount: -5 },
        { type: 'profile', key: 'Se', amount: 1 },
        { type: 'profile', key: 'P', amount: 1 },
      ],
      preview: { hint: 'Pelech Glitchky · Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Šel jsi za melodií. Zněla jako něco, co sis kdysi pamatoval špatně.',
      effects: [
        { type: 'moveSector', sectorId: 'archive' },
        { type: 'stat', key: 'memory', amount: 5 },
        { type: 'stat', key: 'energy', amount: -3 },
        { type: 'profile', key: 'Si', amount: 1 },
        { type: 'profile', key: 'N', amount: 1 },
      ],
      preview: { hint: 'Archiv · Paměť ↑ · Energie ↓', statHints: { memory: 'up', energy: 'down' }, risk: 'low' },
    },
  },


  door_refuses_no: {
    id: 'door_refuses_no',
    title: 'Dveře odmítly odmítnutí',
    logLabel: 'DOOR_REFUSES_NO',
    scene: 'Odmítl jsi dveře. Dveře to odmítly. Takhle nějak začíná špatná smlouva.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [DOOR/REFUSAL]:</span> odmítnutí odmítnuto. Dveře zahájily pasivně-agresivní vyjednávání.</p><p class="text">Řekl jsi ne. Dveře zůstaly zavřené přesně dvě vteřiny, aby dodržely dekorum, a pak se znovu otevřely s výrazem neživé věci, která si myslí, že má pravdu.</p><p class="text">Na rámu se objeví drobný formulář: <span class="fx-flicker">Nesouhlas se nesouhlasem</span>. Chybí jen kolonka pro krevní skupinu a poslední důvod pokračovat.</p><p class="dialogS">„Dveře, které neberou ne. Úžasné. I architektura tu má horší hranice než průměrný člověk ve tři ráno.“</p>`,
    sceneFx: ['scene-path', 'scene-door', 'scene-form', 'scene-absurd'],
    yesLabel: 'VSTOUPIT NASRANĚ',
    noLabel: 'HÁDAT SE S DVEŘMI',
    category: 'path',
    rarity: 'uncommon',
    tags: ['path', 'form', 'absurd'],
    yes: {
      resultText: 'Vstoupil jsi nasraně. Dveře to vyhodnotily jako souhlas. Formulářovna miluje agresivní souhlasy.',
      effects: [
        { type: 'moveSector', sectorId: 'form_office' },
        { type: 'stat', key: 'energy', amount: 5 },
        { type: 'stat', key: 'control', amount: -4 },
        { type: 'entityRelation', entity: 'form', delta: -1 },
        { type: 'profile', key: 'Se', amount: 1 },
      ],
      preview: { hint: 'Formulářovna · Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Hádal ses s dveřmi. Vyhrály. Měly panty, trpělivost a lepší argumenty než většina lidí.',
      effects: [
        { type: 'stat', key: 'control', amount: 4 },
        { type: 'stat', key: 'energy', amount: -4 },
        { type: 'schedule', cardId: 'door_waits_politely', inTurns: 5 },
        { type: 'profile', key: 'Ti', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Energie ↓ · dveře počkají', statHints: { control: 'up', energy: 'down' }, risk: 'low' },
    },
  },


  mirror_demands_apology: {
    id: 'mirror_demands_apology',
    title: 'Zrcadlo žádá omluvu',
    logLabel: 'MIRROR_APOLOGY',
    scene: 'Zrcadlo tě neodráží. Jen čeká. Na skle se pomalu objeví věta: „Tak co?“',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [MIRROR/APOLOGY]:</span> odraz odmítl službu. Požaduje emoční vyrovnání.</p><p class="text">Zrcadlo tě neodráží. Jen čeká. Sklo je tmavé, ale ne prázdné. Na jeho povrchu se pomalu objeví věta: <span class="fx-flicker">TAK CO?</span></p><p class="text">Není jasné, komu se máš omluvit. Sobě, systému, nebo té verzi tebe, kterou jsi nechal čekat za sklem, dokud neztratila trpělivost a pořídila si vlastní scénu.</p><p class="dialogS">„Omluva sobě. To bude legrační. Lidi se sobě omlouvají asi stejně ochotně jako tiskárna přiznává vinu.“</p>`,
    sceneFx: ['scene-path', 'scene-mirror', 'scene-apology', 'scene-self'],
    yesLabel: 'OMLUVIT SE SOBĚ',
    noLabel: 'ROZBÍT HO',
    category: 'path',
    rarity: 'rare',
    conditions: [{ type: 'sector', sector: 'mirror' }],
    tags: ['mirror', 'self', 'memory', 'shadow'],
    yes: {
      resultText: 'Omluvil ses sobě. Znělo to divně. Tím spíš to zrcadlo poznalo jako pravdu.',
      effects: [
        { type: 'stat', key: 'bond', amount: 6 },
        { type: 'stat', key: 'memory', amount: 5 },
        { type: 'stat', key: 'control', amount: -4 },
        { type: 'imprint', imprintId: 'mirror_crack' },
        { type: 'entityRelation', entity: 'shadow', delta: 2 },
        { type: 'profile', key: 'Fi', amount: 2 },
        { type: 'profile', key: 'Ni', amount: 1 },
      ],
      preview: { hint: 'Vazba ↑ · Paměť ↑ · imprint', statHints: { bond: 'up', memory: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Rozbil jsi ho. Střepy se nerozsypaly na zem. Rozsypaly se do verzí tebe, které měly připomínky.',
      effects: [
        { type: 'item', itemId: 'mirror_shard' },
        { type: 'stat', key: 'energy', amount: 7 },
        { type: 'stat', key: 'memory', amount: -6 },
        { type: 'schedule', cardId: 'mirror_shards_argue', inTurns: 4 },
        { type: 'profile', key: 'Se', amount: 1 },
        { type: 'profile', key: 'T', amount: 1 },
      ],
      preview: { hint: 'Střep · Energie ↑ · Paměť ↓ · následky', statHints: { energy: 'up', memory: 'down' }, risk: 'high' },
    },
  },
};
