import type { SwipeCard } from '../cyklusTypes';

export const RESTART_CARDS: Record<string, SwipeCard> = {


  // ── RESTARTS (6) ────────────────────────────────────────────────────────────
  restart_0: {
    id: 'restart_0',
    title: '0 [RESTART]',
    logLabel: 'RESTART',
    scene: 'Prázdnota se otevře jako úvodní obrazovka, která už tě zná. Systém se ptá, jestli jsi připraven, a tváří se, že odpověď není jen další položka v diagnostice.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [RESTART/0]:</span> dotaz na připravenost nebyl položen subjektu. Byl položen jeho reflexům.</p><p class="text">Prázdnota se otevře jako úvodní obrazovka, která už tě zná. <span class="fx-outline is-lit">NULL-1</span> stojí před volbou tak základní, až je podezřelá.</p><p class="dialog">„Jsi připraven?“</p><p class="text">Otázka visí ve vzduchu jako špatně napsaná smlouva. Kapitola nula. Nekonečná. Volba je dveře, ne výklad, což je milé, protože dveře aspoň předstírají, že vedou ven.</p>`,
    sceneFx: ['scene-restart', 'scene-prologue', 'scene-void'],
    yesLabel: 'ANO',
    noLabel: 'NE',
    category: 'restart',
    rarity: 'unique',
    tags: ['restart', 'diagnostic', 'intro'],
    yes: { resultText: 'Zvolil jsi. Systém si to poznamenal jako jemný posun doprava.', effects: [{ type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }, { type: 'stat', key: 'control', amount: 2 }, { type: 'stat', key: 'energy', amount: -1 }], preview: { hint: 'Diagnostika', risk: 'low' } },
    no: { resultText: 'Zvolil jsi. Systém si to poznamenal jako jemný posun doleva.', effects: [{ type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Fi', amount: 1 }, { type: 'stat', key: 'bond', amount: 1 }, { type: 'stat', key: 'control', amount: -1 }], preview: { hint: 'Diagnostika', risk: 'low' } },
  },

  restart_1: {
    id: 'restart_1',
    title: '1 [RESTART]',
    logLabel: 'RESTART',
    scene: 'V šumu se vrátí věta, kterou jsi jednou chtěl říct. Ještě nemá adresáta, ale už má následky. Synthoma samozřejmě fakturuje i za neodeslané věci.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [RESTART/UNSENT_SENTENCE]:</span> nalezena věta bez příjemce. Emoční clo čeká.</p><p class="text">V šumu se vrátí věta, kterou jsi jednou chtěl říct. Je měkká, těžká a trochu živá, jako kdyby ji někdo držel příliš dlouho pod jazykem.</p><p class="text">Můžeš ji schovat. Můžeš ji nechat viset ve vzduchu. Obě možnosti jsou směšně lidské, takže je systém uloží s patřičným znechucením.</p>`,
    sceneFx: ['scene-restart', 'scene-memory', 'scene-bond'],
    yesLabel: 'SCHOVAT',
    noLabel: 'NECHAT',
    category: 'restart',
    rarity: 'unique',
    tags: ['restart', 'memory', 'emotion'],
    yes: { resultText: 'Schoval jsi větu. Paměť si ji uložila jako nevyužitý kód. Čeká na patch.', effects: [{ type: 'profile', key: 'Si', amount: 1 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'stat', key: 'memory', amount: 3 }, { type: 'stat', key: 'bond', amount: -1 }], preview: { hint: 'Paměť ↑', statHints: { memory: 'up' }, risk: 'low' } },
    no: { resultText: 'Nechal jsi větu viset. Vzduch ji převedl do jiné místnosti. Někdo ji tam najde.', effects: [{ type: 'profile', key: 'Ne', amount: 1 }, { type: 'profile', key: 'E', amount: 1 }, { type: 'stat', key: 'bond', amount: 2 }, { type: 'stat', key: 'control', amount: -1 }], preview: { hint: 'Vazba ↑', statHints: { bond: 'up' }, risk: 'low' } },
  },

  restart_2: {
    id: 'restart_2',
    title: '2 [RESTART]',
    logLabel: 'RESTART',
    scene: 'Objeví se dveře, které neumí slíbit nic kromě pohybu. Jistota nepřichází. V Synthomě by stejně měla zpoždění, vyplněný formulář a špatnou adresu.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [RESTART/THRESHOLD]:</span> dveře aktivní. Jistota nenalezena. Náhradní iluze připravena.</p><p class="text">Objeví se dveře. Nejsou krásné. Nejsou hrozivé. Jsou horší: <span class="fx-outline is-lit">jsou použitelné</span>.</p><p class="text">Říkáš si, že je otevřeš, až budeš mít jistotu. Jistota nepřichází. V Synthomě by stejně dorazila pozdě, s razítkem a poznámkou, že subjekt nepřiložil přílohu č. 7.</p>`,
    sceneFx: ['scene-restart', 'scene-path', 'scene-control'],
    yesLabel: 'OTEVŘÍT',
    noLabel: 'ČEKAT',
    category: 'restart',
    rarity: 'unique',
    tags: ['restart', 'choice', 'future'],
    yes: { resultText: 'Otevřel jsi dveře. Za nimi byla chodba. Nic zvláštního. Ale byla tvoje.', effects: [{ type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Se', amount: 1 }, { type: 'stat', key: 'control', amount: 2 }, { type: 'stat', key: 'energy', amount: -1 }], preview: { hint: 'Kontrola ↑', statHints: { control: 'up' }, risk: 'low' } },
    no: { resultText: 'Čekal jsi. Dveře se zavřely samy. Alespoň ses nemusel rozhodovat.', effects: [{ type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }, { type: 'stat', key: 'energy', amount: 1 }, { type: 'stat', key: 'control', amount: -1 }], preview: { hint: 'Energie ↑', statHints: { energy: 'up' }, risk: 'low' } },
  },

  restart_3: {
    id: 'restart_3',
    title: '3 [RESTART]',
    logLabel: 'RESTART',
    scene: 'V kapse je předmět, který sis nevzal. Přesto tam dýchá. Paměť si opět plete vlastnictví s následkem, protože proč by se svět choval slušně.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [RESTART/UNCLAIMED_OBJECT]:</span> objekt nalezen v kapse subjektu. Historie převzetí chybí. Pocit odpovědnosti přítomen.</p><p class="text">V kapse je předmět, který sis nevzal. Přesto tam leží, těžký a uraženě tichý.</p><p class="text"><span class="fx-outline">Vlastnictví</span> je v SYNTHOMĚ jen optimistický název pro věc, která tě už nějak změnila. Můžeš ji uznat. Můžeš ji zapřít. Předmět si mezitím zapisuje obě možnosti, protože drobné věci bývají největší svině.</p>`,
    sceneFx: ['scene-restart', 'scene-object', 'scene-memory'],
    yesLabel: 'UZNAT',
    noLabel: 'ZAPŘÍT',
    category: 'restart',
    rarity: 'unique',
    tags: ['restart', 'object', 'memory'],
    yes: { resultText: 'Uznal jsi předmět. Paměť si to převedla do kategorie „vlastní“. Systém to zapsal jako anomálii.', effects: [{ type: 'profile', key: 'Si', amount: 1 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'stat', key: 'memory', amount: 3 }, { type: 'stat', key: 'bond', amount: 1 }], preview: { hint: 'Paměť ↑ · Vazba ↑', statHints: { memory: 'up', bond: 'up' }, risk: 'low' } },
    no: { resultText: 'Zapřel jsi. Předmět zůstal v kapse, ale teď už nemá majitele. Bude chodit sám.', effects: [{ type: 'profile', key: 'Ne', amount: 1 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'stat', key: 'control', amount: 2 }, { type: 'stat', key: 'bond', amount: -1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },

  restart_4: {
    id: 'restart_4',
    title: '4 [RESTART]',
    logLabel: 'RESTART',
    scene: 'Někdo tě zavolá jménem, které není v systému. Protokol zbledne. Kdyby měl tvář, právě by dělal, že neslyšel vůbec nic.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [RESTART/NAME_DRIFT]:</span> neregistrované oslovení proniklo do bezpečné vrstvy. Bezpečná vrstva se urazila.</p><p class="text">Někdo tě zavolá jménem, které není v systému. Zvuk neprojde ušima. Projde přímo místem, kde by kdysi mohla být jistota.</p><p class="text">Protokol zbledne. Kdyby měl tvář, dělal by, že neslyšel. Jenže i ticho má tady auditní stopu a tahle právě začala svítit.</p>`,
    sceneFx: ['scene-restart', 'scene-identity', 'scene-bond'],
    yesLabel: 'OTOČIT SE',
    noLabel: 'ZŮSTAT',
    category: 'restart',
    rarity: 'unique',
    tags: ['restart', 'relation', 'identity'],
    yes: { resultText: 'Otočil ses. Za tebou nikdo nebyl. Ale jméno zůstalo. To stačí.', effects: [{ type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }, { type: 'stat', key: 'bond', amount: 3 }, { type: 'stat', key: 'memory', amount: 1 }], preview: { hint: 'Vazba ↑', statHints: { bond: 'up' }, risk: 'low' } },
    no: { resultText: 'Zůstal jsi čelem k protokolu. Jméno zhaslo. Systém pokračoval, jako by se nic nestalo.', effects: [{ type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'Si', amount: 1 }, { type: 'stat', key: 'control', amount: 2 }, { type: 'stat', key: 'bond', amount: -1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },

  restart_5: {
    id: 'restart_5',
    title: '5 [RESTART]',
    logLabel: 'RESTART',
    scene: 'Poslední restart se netváří posledně. To je na něm nejhorší. Systém se ptá, jestli chceš pokračovat, i když už nejsi stejný kus chyby jako na začátku.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [RESTART/5]:</span> hranice prologu dosažena. Subjekt vykazuje známky opakované identity. Podezřelé.</p><p class="text">Poslední restart se netváří posledně. To je na něm nejhorší. V SYNTHOMĚ i konec stojí u dveří a ptá se, jestli náhodou nechceš ještě jeden běh, když už ses tak pěkně poškodil.</p><p class="text">Systém se ptá, jestli chceš pokračovat, i když už nejsi stejný. <span class="fx-flicker">Možná právě proto.</span></p>`,
    sceneFx: ['scene-restart', 'scene-warning', 'scene-restart-fatigue'],
    yesLabel: 'POKRAČOVAT',
    noLabel: 'ZASTAVIT',
    category: 'restart',
    rarity: 'unique',
    tags: ['restart', 'end', 'meta'],
    yes: { resultText: 'Rozhodl ses pokračovat. Systém to přijal jako nový začátek. A možná jako konec.', effects: [{ type: 'stat', key: 'energy', amount: 2 }, { type: 'stat', key: 'bond', amount: 2 }, { type: 'profile', key: 'N', amount: 1 }, { type: 'profile', key: 'Fi', amount: 1 }], preview: { hint: 'Všechno mírně ↑', risk: 'low' } },
    no: { resultText: 'Zastavil ses. Systém se nezlobil. Jen počkal. A pak začal znova. I bez tvého svolení.', effects: [{ type: 'stat', key: 'control', amount: 3 }, { type: 'stat', key: 'bond', amount: -2 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'Ti', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },
};
