import type { SwipeCard } from '../cyklusTypes';

export const SPECIAL_CARDS: Record<string, SwipeCard> = {


  // ── SILENT / SCHEDULED (6) ────────────────────────────────────────────────────
  pocket_breathes: {
    id: 'pocket_breathes',
    title: 'Kapsa dýchá',
    logLabel: 'SILENT',
    scene: 'Kapsa se zvedá a klesá, jako by v ní někdo spal. Nebo čekal.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [POCKET/BREATH]:</span> inventář vykazuje známky metabolismu. Gratulujeme, kapsa postoupila z textilu na problém.</p><p class="text">Kapsa se zvedá a klesá. Pomalu. Opatrně. Jako by v ní někdo spal v poloze, kterou schvalují jen noční můry a špatně navržené bundy.</p><p class="text">Nevidíš dovnitř. Přesto máš pocit, že něco uvnitř vidí ven.</p><p class="dialogS">„Jestli ti dýchá kapsa, nejsi dobrodruh. Jsi nájemní byt pro vedlejší účinky.“</p>`,
    sceneFx: ['scene-silent', 'scene-pocket', 'scene-noise', 'scene-mystery'],
    yesLabel: 'PODÍVAT SE',
    noLabel: 'NEPODÍVAT SE',
    category: 'silent',
    rarity: 'common',
    tags: ['silent', 'noise', 'mystery', 'pocket'],
    yes: { resultText: 'Podíval ses. Nic tam nebylo. Kapsa si to poznamenala jako důkaz důvěry.', effects: [{ type: 'stat', key: 'bond', amount: 3 }, { type: 'stat', key: 'control', amount: -2 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Vazba ↑ · Kontrola ↓', statHints: { bond: 'up', control: 'down' }, risk: 'low' } },
    no: { resultText: 'Nepodíval ses. Kapsa si to poznamenala jako důkaz opatrnosti. Nebo zbabělosti.', effects: [{ type: 'stat', key: 'control', amount: 4 }, { type: 'stat', key: 'bond', amount: -2 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },

  pocket_gets_heavy: {
    id: 'pocket_gets_heavy',
    title: 'Kapsa ztěžkla',
    logLabel: 'SILENT',
    scene: 'Kapsa je najednou těžká. Víš, že jsi do ní nic nedával. A přesto.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [POCKET/MASS_ANOMALY]:</span> detekována hmotnost bez příčiny. Fyzika podala stížnost a odešla na pauzu.</p><p class="text">Kapsa je najednou těžká. Ne tak, jak těžkne látka. Spíš tak, jak těžkne slovo, které někdo neřekl, a ono si mezitím našlo vlastní gravitaci.</p><p class="text">Víš, že jsi do ní nic nedával. V SYNTHOMĚ je to tradičně nejrychlejší způsob, jak něco vlastnit.</p><p class="dialogS">„Výborně. Inventář se ti plní morálními předměty. To se v e-shopu špatně reklamuje.“</p>`,
    sceneFx: ['scene-silent', 'scene-pocket', 'scene-object', 'scene-token'],
    yesLabel: 'VYPRÁZDNIT',
    noLabel: 'NECHAT',
    category: 'silent',
    rarity: 'uncommon',
    tags: ['silent', 'item', 'void'],
    yes: { resultText: 'Vyprázdnil jsi kapsu. Vypadl z ní žeton, který sis nevzal. Zmizel, než dopadl.', effects: [{ type: 'stat', key: 'control', amount: 4 }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Ti', amount: 1 }], preview: { hint: 'Kontrola ↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'medium' } },
    no: { resultText: 'Nechal jsi kapsu těžkou. Žeton se usadil. Bude chtít nájem.', effects: [{ type: 'stat', key: 'bond', amount: -4 }, { type: 'stat', key: 'memory', amount: 4 }, { type: 'profile', key: 'N', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Paměť ↑ · Vazba ↓', statHints: { memory: 'up', bond: 'down' }, risk: 'medium' } },
  },

  key_waits: {
    id: 'key_waits',
    title: 'Klíč čeká',
    logLabel: 'SILENT',
    scene: 'Archivní klíč leží na dně kapsy. Nehýbe se. Ale není mrtvý.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [ARCHIVE_KEY/IDLE]:</span> klíč čeká. Pasivita objektu je pouze právní fikce.</p><p class="text">Archivní klíč leží na dně kapsy. Kov je chladný, ale ne mrtvý. V jeho zubech se drží prach dveří, které se zatím tváří jako nábytek.</p><p class="text">Kdykoli se pohneš, klíč lehce cinkne. Ne dost nahlas pro ucho. Dost nahlas pro Archiv.</p><p class="dialogS">„Klíče jsou roztomilé. Předstírají, že otvírají dveře, a přitom většinou otvírají problémy.“</p>`,
    sceneFx: ['scene-silent', 'scene-key', 'scene-archive', 'scene-object'],
    yesLabel: 'ZAHŘÁT HO',
    noLabel: 'NECHAT CHLADNÝ',
    category: 'silent',
    rarity: 'uncommon',
    tags: ['silent', 'archive', 'item'],
    yes: { resultText: 'Zahřál jsi klíč. Archiv na dálku zareagoval. Zapsal to jako „zájem“.', effects: [{ type: 'stat', key: 'memory', amount: 4 }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Si', amount: 1 }], preview: { hint: 'Paměť ↑ · Energie ↓', statHints: { memory: 'up', energy: 'down' }, risk: 'low' } },
    no: { resultText: 'Nechal jsi klíč chladný. Stal se z něj obyčejný předmět. To je vlastně vítězství.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },

  mirror_waits: {
    id: 'mirror_waits',
    title: 'Zrcadlo čeká',
    logLabel: 'SILENT',
    scene: 'Střep v kapse je chladný. Ale když ho nechytíš, cítíš, jak se na tebe dívá.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [MIRROR_SHARD/OBSERVE]:</span> odraz čeká na vizuální kontakt. Což je jen slušný výraz pro přepadení pohledem.</p><p class="text">Střep v kapse je chladný. Nechytíš ho, a přesto cítíš dotek. Jako by se zrcadlo naučilo dívat i bez skla.</p><p class="text">Někde v něm stojí odraz, který tě nepředbíhá ani neopakuje. Jen čeká, až uděláš chybu jako první.</p><p class="dialogS">„Zrcadla jsou nejlevnější forma soudu. Stačí se podívat a hned je po obhajobě.“</p>`,
    sceneFx: ['scene-silent', 'scene-mirror', 'scene-memory', 'scene-object'],
    yesLabel: 'POHLEDNOUT',
    noLabel: 'ODLOŽIT',
    category: 'silent',
    rarity: 'uncommon',
    tags: ['silent', 'mirror', 'memory'],
    yes: { resultText: 'Podíval ses na střep. Odraz se pohnul o zlomek vteřiny dřív. To je všechno, co potřeboval.', effects: [{ type: 'stat', key: 'memory', amount: 5 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'profile', key: 'N', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Paměť ↑ · Kontrola ↓', statHints: { memory: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Odložil jsi střep. Zrcadlo se přestěhovalo do zapomenutého šuplíku. Najdeš ho až budeš starší.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'memory', amount: -3 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Paměť ↓', statHints: { control: 'up', memory: 'down' }, risk: 'low' } },
  },

  noise_pet_leaves: {
    id: 'noise_pet_leaves',
    title: 'Chomáč odchází',
    logLabel: 'SILENT',
    scene: 'Chomáč šumu v kapse se zmenšuje. Už se ho téměř nedotýkáš.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [NOISE/PET_EXIT]:</span> šumový organismus zvažuje odchod. Emoční inventář hlásí drobnou ztrátu a velké přehrávání.</p><p class="text">Chomáč šumu v kapse se zmenšuje. Už neškrábe. Už nezpívá. Jen občas zašustí, jako by skládal dopis, který neumí napsat.</p><p class="text">Je divné truchlit po poruše signálu. Ještě divnější je, že SYNTHOMA to pochopí dřív než ty.</p><p class="dialogS">„Ano, smutníš po kapesním bordelu z dat. Lidská vazba je opravdu software bez QA týmu.“</p>`,
    sceneFx: ['scene-silent', 'scene-noise', 'scene-loss', 'scene-bond'],
    yesLabel: 'POCHOVAT',
    noLabel: 'NECHAT ODEJÍT',
    category: 'silent',
    rarity: 'uncommon',
    tags: ['silent', 'noise', 'loss'],
    yes: { resultText: 'Pochoval jsi chomáč. Zahrabal jsi ho pod vrstvu ticha. Bude tam klidnější.', effects: [{ type: 'stat', key: 'memory', amount: 4 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'stat', key: 'energy', amount: -2 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'Si', amount: 1 }], preview: { hint: 'Paměť ↑ · Vazba ↓ · Energie ↓', statHints: { memory: 'up', bond: 'down', energy: 'down' }, risk: 'medium' } },
    no: { resultText: 'Nechal jsi chomáč odejít. Odešel do šumu, ze kterého přišel. Možná se tam zase uvidíte.', effects: [{ type: 'stat', key: 'energy', amount: 4 }, { type: 'stat', key: 'control', amount: -3 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Ne', amount: 1 }], preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'low' } },
  },

  memory_beast_returns: {
    id: 'memory_beast_returns',
    title: 'Šelma se vrací',
    logLabel: 'ITEM_TRIGGER',
    scene: 'Značka na tvé ruce se zahřála. Šelma se blíží. Ne žere. Pozoruje.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [MARK/BEAST_RETURN]:</span> značka aktivní. Paměťová šelma je v dosahu. Doporučení: nebýt křupavý.</p><p class="text">Značka na ruce se zahřeje. Ne jako rána. Jako tlama, která si tě pamatuje jemněji, než by měla. Vzduch kolem zhoustne do chlupaté tmy.</p><p class="text">Šelma se nevrací pro maso. Maso je v SYNTHOMĚ nudné. Vrací se pro tón, kterým jsi kdysi něco přiznal.</p><p class="dialogS">„Hlavně klid. Když tě olízne tvoje vlastní paměť, nedělej prudké pohyby. Vypadá to nedůstojně.“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-beast', 'scene-memory', 'scene-danger'],
    yesLabel: 'UKLONIT SE',
    noLabel: 'ČELOM PROTI',
    category: 'item_trigger',
    rarity: 'rare',
    conditions: [{ type: 'hasItem', itemId: 'memory_beast_mark' }],
    tags: ['item_trigger', 'memory', 'beast'],
    yes: { resultText: 'Uklonil ses. Šelma přišla blíž a položila ti hlavu na klín. To bylo těžší, než to vypadalo.', effects: [{ type: 'stat', key: 'bond', amount: 6 }, { type: 'stat', key: 'memory', amount: 4 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Vazba ↑ · Paměť ↑ · Kontrola ↓', statHints: { bond: 'up', memory: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Postavil ses čelem. Šelma tě obešla a odešla. Značka zbledla. Stal ses z ní příběh, než majitele.', effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'stat', key: 'memory', amount: -3 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓ · Paměť ↓', statHints: { control: 'up', bond: 'down', memory: 'down' }, risk: 'medium' } },
  },

  mirror_crack: {
    id: 'mirror_crack',
    title: 'Zrcadlová trhlina',
    logLabel: 'MIRROR',
    scene: 'Ve vzduchu visí prasklina. Nevede nikam. Ukazuje tebe. Tedy horší varianta nikam.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [MIRROR/CRACK]:</span> trhlina ve vzduchu vykazuje vlastnosti odrazu. Realita se opět snaží být dramatická.</p><p class="text">Ve vzduchu visí prasklina. Nevede nikam. Ukazuje tebe. Což je horší varianta nikam, protože nikam se aspoň netváří zklamaně.</p><p class="text">Hrany trhliny svítí studeně. V odrazu stojíš o půl vteřiny starší a o jeden kompromis unavenější.</p><p class="dialogS">„Dotkni se toho a dostaneš odpověď. Nedotkni se toho a odpověď si tě najde sama. Fantastický výběr, opravdu.“</p>`,
    sceneFx: ['scene-silent', 'scene-mirror', 'scene-glitch', 'scene-memory'],
    yesLabel: 'DOTKNOUT SE',
    noLabel: 'ODVRÁTIT SE',
    category: 'silent',
    rarity: 'rare',
    tags: ['mirror', 'memory', 'glitch', 'silent'],
    yes: { resultText: 'Dotkl ses trhliny. Nebyla studená. Byla zrcadlová. Odraz tě pustil dřív, než ty jeho.', effects: [{ type: 'imprint', imprintId: 'mirror_crack' }, { type: 'item', itemId: 'mirror_shard' }, { type: 'unlockPool', poolId: 'mirror_pool' }, { type: 'stat', key: 'memory', amount: 6 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'profile', key: 'Ni', amount: 2 }], preview: { hint: 'Item · Paměť ↑ · Kontrola ↓', statHints: { memory: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Odvrátil ses. Trhlina zůstala. Ale teď už víš, že ví, že ses odvrátil. To je vlastně horší.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'memory', amount: -3 }], preview: { hint: 'Kontrola ↑ · Paměť ↓', statHints: { control: 'up', memory: 'down' }, risk: 'low' } },
  },

  noise_resident: {
    id: 'noise_resident',
    title: 'Šumový nájemník',
    logLabel: 'NOISE',
    scene: 'V rohu sektoru sedí malý chumel Šumu. Netváří se nepřátelsky. Což je přesně způsob, jakým začíná většina problémů.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [NOISE/RESIDENCY]:</span> šum žádá o trvalý pobyt. Kolonka důvod obsahuje: píp.</p><p class="text">V rohu sektoru sedí malý chumel Šumu. Netváří se nepřátelsky. Vlastně se netváří nijak. To je u šumu buď nevinnost, nebo právní strategie.</p><p class="text">Když se pohneš, posune se o centimetr blíž ke kapse. Jako domácí mazlíček, který ještě nepochopil rozdíl mezi láskou a parazitismem.</p><p class="dialogS">„Nechat si šum v kapse. Jistě. A pak se divit, že ti myšlenky chrastí jako modem v roce 1998.“</p>`,
    sceneFx: ['scene-silent', 'scene-noise', 'scene-energy', 'scene-comic'],
    yesLabel: 'NECHAT HO ZŮSTAT',
    noLabel: 'VYHNAT HO',
    category: 'silent',
    rarity: 'uncommon',
    tags: ['noise', 'energy', 'glitch', 'silent'],
    yes: { resultText: 'Nechal jsi ho zůstat. Usadil se v kapse. Tváří se, že tam bydlí. Možná tam opravdu bydlí.', effects: [{ type: 'imprint', imprintId: 'noise_resident' }, { type: 'item', itemId: 'noise_clump' }, { type: 'flag', flag: 'noise_resident_active' }, { type: 'unlockPool', poolId: 'noise_pool' }, { type: 'stat', key: 'energy', amount: 4 }, { type: 'stat', key: 'control', amount: -5 }], preview: { hint: 'Item · Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Vyhnal jsi ho. Chumel se rozptýlil do rohů. Ale teď se v každém rohu něco šeptá.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'schedule', cardId: 'noise_pet_leaves', inTurns: 4 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },


  // ── QUESTLINES & EXTENDED ITEMS ─────────────────────────────────────────────
  // Rezavý žeton questline
  token_market_door: {
    id: 'token_market_door',
    title: 'Tržiště poznalo žeton',
    logLabel: 'TOKEN_MARKET',
    scene: 'Jeden ze stánků ztuhl. Prodavač se na tebe podíval a řekl: „Ten žeton nepatří na pult. Patří dovnitř.“',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [TOKEN/MARKET_GATE]:</span> rezavý žeton rozpoznán tržištěm. Hodnota: nepříjemně osobní.</p><p class="text">Jeden ze stánků ztuhl. Plachty přestaly šumět, mince přestaly cinkat a prodavač se na tebe podíval tak, jako se dívají lidé, kteří už znají cenu, ale baví je nechat tě hádat.</p><p class="dialogD">„Ten žeton nepatří na pult. Patří dovnitř.“</p><p class="text">Za stánkem se otevřely dveře z účtenek, odmítnutých omluv a kovu, který už jednou prošel rukou někoho, kdo nechtěl platit.</p>`,
    sceneFx: ['scene-item-trigger', 'scene-token', 'scene-market', 'scene-debt'],
    yesLabel: 'VEJÍT',
    noLabel: 'ODEJÍT',
    category: 'item_trigger',
    rarity: 'uncommon',
    conditions: [{ type: 'hasItem', itemId: 'warm_token' }],
    tags: ['item_trigger', 'token', 'market'],
    yes: { resultText: 'Vešel jsi dozadu. Žeton se zahřál až k bolesti. Měl jsi ho. Teď ho má někdo jiný.', effects: [{ type: 'removeItem', itemId: 'warm_token' }, { type: 'item', itemId: 'named_token' }, { type: 'stat', key: 'memory', amount: 5 }, { type: 'stat', key: 'control', amount: -3 }, { type: 'entityRelation', entity: 'glitchka', delta: 1 }, { type: 'unlockPool', poolId: 'token_market_pool' }, { type: 'profile', key: 'N', amount: 1 }], preview: { hint: 'Předmět se mění · Paměť ↑ · Kontrola ↓', statHints: { memory: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Odešel jsi. Žeton v kapse zasténal. Ne hlasitě. Dostatečně na to, aby sis to pamatoval.', effects: [{ type: 'stat', key: 'control', amount: 4 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'schedule', cardId: 'token_collector', inTurns: 7 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓ · budoucí následek', statHints: { control: 'up', bond: 'down' }, risk: 'medium' } },
  },

  token_final_trade: {
    id: 'token_final_trade',
    title: 'Poslední obchod žetonu',
    logLabel: 'TOKEN_FINAL',
    scene: 'Utržený žeton se už nehřeje. Leží v dlani jako mince bez měny. Stánek před tebou je otevřený, ale nikdo v něm není.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [TOKEN/FINAL_TRADE]:</span> tržiště nabízí výměnu. Varování: konečné obchody málokdy končí účtenkou.</p><p class="text">Žeton se rozpadl na dvě poloviny. V jedné je slyšet cizí smích. V druhé tvoje ticho. Prodavač je položí na váhu, která měří spíš výmluvy než kov.</p><p class="dialogD">„Můžeš získat průchod. Nebo si ponechat důvod, proč se bojíš projít.“</p><p class="dialogS">„Skvělé. Dokonce i tvoje mince mají hlubší charakterový oblouk než průměrný člověk na poradě.“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-token', 'scene-market', 'scene-debt', 'scene-critical'],
    yesLabel: 'PRODAT',
    noLabel: 'NECHAT SI HO',
    category: 'item_trigger',
    rarity: 'rare',
    conditions: [{ type: 'hasItem', itemId: 'spent_token' }],
    tags: ['item_trigger', 'token', 'loss'],
    yes: { resultText: 'Prodal jsi utržený žeton. Koupil sis za něj klid. Byl to dobrý obchod, i když ti po něm zůstala prázdná kapsa.', effects: [{ type: 'removeItem', itemId: 'spent_token' }, { type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: 2 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↑', statHints: { control: 'up', bond: 'up' }, risk: 'low' } },
    no: { resultText: 'Nechal jsi si žeton. Utržený. Neplatný. Tvůj. Někdy je držení bezcenné věci dražší než prodej.', effects: [{ type: 'stat', key: 'memory', amount: 6 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'unlockPool', poolId: 'mirror_pool' }, { type: 'schedule', cardId: 'token_wants_name', inTurns: 6 }, { type: 'profile', key: 'Ni', amount: 1 }, { type: 'profile', key: 'F', amount: 1 }], preview: { hint: 'Paměť ↑ · budoucí následek · odemkne Zrcadlo', statHints: { memory: 'up' }, risk: 'medium' } },
  },


  // Glitchový kamínek questline
  pebble_committee: {
    id: 'pebble_committee',
    title: 'Výbor kamínků',
    logLabel: 'ITEM_TRIGGER',
    scene: 'Kamínky se sešly bez pozvání. Jeden s brýlemi předsedal. Diskutovali tvé nastavení. Nebyl jsi přizván.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [PEBBLE/COMMITTEE]:</span> kamínek svolal výbor. Agenda: proč ho bereš málo vážně.</p><p class="text">Kamínek se přes noc rozmnožil. Ne biologicky. Díkybohu. Na zemi teď leží malý kruh glitchových oblázků a každý z nich se tváří jako zástupce problému, který nemá kalendář.</p><p class="dialogG halo">„Říkali, že chtějí hlasovat. Já jim řekla, že jsi zatím nerozbitý dost demokraticky. 🦊🪨“</p><p class="dialogS">„Výbor kamínků. Konečně instituce, která odpovídá úrovni situace.“</p>`,
    sceneFx: ['scene-followup', 'scene-pebble', 'scene-glitchka', 'scene-comic'],
    yesLabel: 'POSLOUCHAT',
    noLabel: 'VZPLÝVAT',
    category: 'item_trigger',
    rarity: 'uncommon',
    conditions: [{ type: 'hasItem', itemId: 'glitch_pebble' }],
    tags: ['item_trigger', 'glitchka', 'chaos'],
    yes: { resultText: 'Poslouchal jsi. Kamínky měly připomínky. Většina byla konstruktivní. Žádná nebyla pro tebe.', effects: [{ type: 'stat', key: 'bond', amount: 3 }, { type: 'stat', key: 'memory', amount: 4 }, { type: 'entityRelation', entity: 'glitchka', delta: 1 }, { type: 'profile', key: 'Ne', amount: 1 }], preview: { hint: 'Vazba ↑ · Paměť ↑', statHints: { bond: 'up', memory: 'up' }, risk: 'medium' } },
    no: { resultText: 'Vzplýval jsi kamínky. Kamínky to zapsaly do zápisu. Bude se o tom jednou. Tady. Znovu.', effects: [{ type: 'stat', key: 'control', amount: 4 }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'schedule', cardId: 'pebble_constellation', inTurns: 5 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Energie ↓ · budoucí následek', statHints: { control: 'up', energy: 'down' }, risk: 'medium' } },
  },


  // Gumový tuleň questline
  rubber_seal_squeaks: {
    id: 'rubber_seal_squeaks',
    title: 'Tuleň pískl',
    logLabel: 'SEAL_SIGNAL',
    scene: 'Gumový tuleň v kapse pískl. Ne hlasitě. Jen dostatečně na to, aby systém znejistěl.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SEAL/SIGNAL]:</span> gumový tuleň vyslal akustickou anomálii. Překlad: písk.</p><p class="text">Gumový tuleň v kapse pískl. Ne hlasitě. Jen dostatečně na to, aby systém znejistěl, formuláře narovnaly hřbety a někde v dálce spadlo jedno razítko ze stolu.</p><p class="text">Tuleň se nehýbe. Přesto z něj vyzařuje ten druh autority, kterou mají jen absurdní předměty a lidé, kteří nikdy nečetli vlastní směrnice.</p><p class="dialogS">„Poslechni tuleně. V téhle realitě má pravděpodobně vyšší kvalifikaci než bezpečnostní modul.“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-seal', 'scene-glitchka', 'scene-comic'],
    yesLabel: 'POSLECHNOUT',
    noLabel: 'IGNOROVAT',
    category: 'item_trigger',
    rarity: 'uncommon',
    conditions: [{ type: 'hasItem', itemId: 'rubber_seal' }],
    tags: ['item_trigger', 'seal', 'glitchka'],
    yes: { resultText: 'Poslechl jsi tuleň. Pískání přestalo. Někde v systému se otevřela malá, důležitá závorka.', effects: [{ type: 'stat', key: 'bond', amount: 3 }, { type: 'stat', key: 'control', amount: -2 }, { type: 'entityRelation', entity: 'glitchka', delta: 1 }, { type: 'schedule', cardId: 'seal_demands_stamp', inTurns: 5 }, { type: 'profile', key: 'F', amount: 1 }], preview: { hint: 'Vazba ↑ · budoucí následek', statHints: { bond: 'up' }, risk: 'medium' } },
    no: { resultText: 'Ignoroval jsi tuleň. Pískání utichlo. Tuleň se tím nepohoršil. Jen si to zapamatoval.', effects: [{ type: 'stat', key: 'control', amount: 3 }, { type: 'stat', key: 'bond', amount: -2 }, { type: 'flag', flag: 'seal_ignored' }, { type: 'profile', key: 'T', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },


  // Archivní klíč questline
  key_in_wrong_office: {
    id: 'key_in_wrong_office',
    title: 'Klíč v špatné kanceláři',
    logLabel: 'KEY_WRONG_OFFICE',
    scene: 'Archivní klíč se v kanceláři rozklepal. Formuláře si ho všimly. To je špatné. Formuláře si nemají všímat věcí.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [KEY/WRONG_CONTEXT]:</span> archivní klíč detekován ve Formulářovně. Interdisciplinární nebezpečí potvrzeno.</p><p class="text">Archivní klíč se v kanceláři rozklepal. Formuláře si ho všimly. To je špatné. Formuláře si nemají všímat věcí. Formuláře mají ležet, žloutnout a pasivně ničit lidem chuť žít.</p><p class="text">Nejbližší šuplík se pootevře. Uvnitř není papír. Je tam tma ve tvaru regálu.</p><p class="dialogS">„Použít archivní klíč na úřední šuplík. Krásné. Přesně takhle vznikají audity s krví.“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-key', 'scene-archive', 'scene-form', 'scene-danger'],
    yesLabel: 'SCHOVAT KLÍČ',
    noLabel: 'POUŽÍT HO NA ŠUPLÍK',
    category: 'item_trigger',
    rarity: 'uncommon',
    conditions: [{ type: 'hasItem', itemId: 'archive_key' }, { type: 'sector', sector: 'form_office' }],
    tags: ['item_trigger', 'archive', 'form', 'key'],
    yes: { resultText: 'Schoval jsi klíč. Formuláře si ho sice zapamatovaly, ale alespoň ho neotevřely. Zatím.', effects: [{ type: 'stat', key: 'control', amount: 4 }, { type: 'stat', key: 'bond', amount: -2 }, { type: 'schedule', cardId: 'key_waits', inTurns: 4 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓ · budoucí následek', statHints: { control: 'up', bond: 'down' }, risk: 'medium' } },
    no: { resultText: 'Použil jsi klíč na šuplík. Šuplík nebyl archiv. Ale klíč si to nepamatuje. Přesunul tě do Archivu a odemkl něco, co nechtělo být nalezeno.', effects: [{ type: 'moveSector', sectorId: 'archive' }, { type: 'stat', key: 'memory', amount: 6 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'unlockPool', poolId: 'archive_forbidden_pool' }, { type: 'entityRelation', entity: 'form', delta: -2 }, { type: 'profile', key: 'N', amount: 1 }], preview: { hint: 'Přesun do Archivu · Paměť ↑ · odemkne Zakázaný archiv', statHints: { memory: 'up' }, risk: 'high' } },
  },


  // Špatná mapa questline
  wrong_map_gives_direction: {
    id: 'wrong_map_gives_direction',
    title: 'Mapa ukazuje správně',
    logLabel: 'MAP_DIRECTION',
    scene: 'Špatná mapa se pořádně otočila. Teď ukazuje směr, který na správné mapě neexistuje. Ale vypadá důvěryhodně.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [MAP/IMPOSSIBLE_DIRECTION]:</span> špatná mapa ukazuje správně. Tato věta byla označena jako trestný čin proti navigaci.</p><p class="text">Špatná mapa se pořádně otočila. Teď ukazuje směr, který na správné mapě neexistuje. Čára vede přes roh místnosti, pak skrz starý smích a nakonec do místa, kde se ztrácí jména.</p><p class="text">Vypadá důvěryhodně. Což je u špatné mapy skoro urážka.</p><p class="dialogG halo">„Někdy je špatně jen směr, který už všichni znají. 🦊🗺️“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-map', 'scene-glitchka', 'scene-path', 'scene-residuum'],
    yesLabel: 'JÍT TÍM SMĚREM',
    noLabel: 'OTOČIT ZPĚT',
    category: 'item_trigger',
    rarity: 'uncommon',
    conditions: [{ type: 'hasItem', itemId: 'wrong_map' }],
    tags: ['item_trigger', 'map', 'path'],
    yes: { resultText: 'Šel jsi směrem, který nebyl na mapě. Dostal ses k Reziduálnímu prahu. Vzduch tam voněl po smazaných větách.', effects: [{ type: 'moveSector', sectorId: 'residuum' }, { type: 'stat', key: 'memory', amount: 5 }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'entityRelation', entity: 'glitchka', delta: 1 }, { type: 'profile', key: 'Ne', amount: 1 }], preview: { hint: 'Přesun do Rezidua · Paměť ↑ · Energie ↓', statHints: { memory: 'up', energy: 'down' }, risk: 'medium' } },
    no: { resultText: 'Otočil jsi mapu zpátky. Správný svět se vrátil. Ale špatná mapa se usmívala. Ví, že se vrátíš.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: -2 }, { type: 'schedule', cardId: 'wrong_map_leads', inTurns: 5 }, { type: 'profile', key: 'S', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓ · budoucí následek', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },


  // Chomáč šumu questline
  noise_pet_sings: {
    id: 'noise_pet_sings',
    title: 'Chomáč zpívá',
    logLabel: 'NOISE_SINGS',
    scene: 'Chomáč v kapse začal zpívat. Ne melodii. Zpíval statiku. Byla to nejupřímnější píseň, jakou jsi slyšel.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [NOISE/SONG]:</span> šumový mazlíček produkuje melodickou statiku. Hudební vkus systému utrpěl, ale přežil.</p><p class="text">Chomáč v kapse začal zpívat. Ne melodii. Zpíval statiku. Přeskakující, špinavou a upřímnou, jako rádio naladěné na stanici, kde moderátor dávno odešel a zbyl jen pocit.</p><p class="text">Kupodivu to není otravné. Nebo možná jen začínáš rozumět věcem, kterým by zdravý subjekt rozumět neměl.</p><p class="dialogS">„Zpívat s kapesním šumem je buď poezie, nebo akutní selhání hranic. V SYNTHOMĚ rozdíl evidujeme dodatečně.“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-noise', 'scene-bond', 'scene-comic'],
    yesLabel: 'ZPÍVAT S NÍM',
    noLabel: 'UTOPIŠT',
    category: 'item_trigger',
    rarity: 'uncommon',
    conditions: [{ type: 'hasItem', itemId: 'noise_clump' }],
    tags: ['item_trigger', 'noise', 'bond'],
    yes: { resultText: 'Zpíval jsi s chomáčem. Někde v systému se něco rozeznělo. Znělo to jako souhlas. Nebo varování. Nebo obojí.', effects: [{ type: 'stat', key: 'bond', amount: 5 }, { type: 'stat', key: 'energy', amount: 4 }, { type: 'stat', key: 'control', amount: -5 }, { type: 'entityRelation', entity: 'glitchka', delta: 1 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Fe', amount: 1 }], preview: { hint: 'Vazba ↑ · Energie ↑ · Kontrola ↓', statHints: { bond: 'up', energy: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Utopil jsi zpěv v tichu. Chomáč zmlkl. Kapsa byla prázdnější. Ne prázdná. Jen méně hudby.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'schedule', cardId: 'noise_pet_leaves', inTurns: 4 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓ · budoucí následek', statHints: { control: 'up', bond: 'down' }, risk: 'medium' } },
  },

  shadow_follows: {
    id: 'shadow_follows',
    title: 'Stín tě následuje',
    logLabel: 'SHADOW_FOLLOWS',
    scene: 'Stín je za tebou. Ne tvůj. Tvůj by tě neposlouchal takhle pozorně.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SHADOW/FOLLOW]:</span> detekován stín bez vlastníka. Pokouší se přilepit k subjektu. Jak společenské.</p><p class="text">Stín je za tebou. Ne tvůj. Tvůj by tě neposlouchal takhle pozorně. Tenhle má vlastní tempo, vlastní ticho a vlastní důvod, proč se ještě nerozpadl.</p><p class="text">Když zastavíš, zastaví taky. O půl vteřiny později. Jako špatná omluva, která dorazila po letech.</p><p class="dialogS">„Nechat si cizí stín. Praktické. Aspoň už nebudeš sám, až budeš dělat špatná rozhodnutí.“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-shadow', 'scene-memory', 'scene-residuum'],
    yesLabel: 'NECHAT HO',
    noLabel: 'ROZSVÍTIT',
    category: 'item_trigger',
    rarity: 'uncommon',
    conditions: [{ type: 'hasItem', itemId: 'ownerless_shadow' }],
    tags: ['item_trigger', 'shadow', 'memory'],
    yes: { resultText: 'Nechal jsi stín. Přilepil se k tvému. Teď máš větší stín. Ne silnější. Jen víc historie.', effects: [{ type: 'stat', key: 'bond', amount: 3 }, { type: 'stat', key: 'memory', amount: 4 }, { type: 'entityRelation', entity: 'residuum', delta: 1 }, { type: 'unlockPool', poolId: 'shadow_pool' }, { type: 'profile', key: 'F', amount: 1 }], preview: { hint: 'Vazba ↑ · Paměť ↑ · odemkne Stín', statHints: { bond: 'up', memory: 'up' }, risk: 'medium' } },
    no: { resultText: 'Rozsvítil jsi. Stín se zmenšil. Nezmizel. Jen se přestal tvářit, že je tvůj.', effects: [{ type: 'stat', key: 'energy', amount: 5 }, { type: 'stat', key: 'control', amount: 3 }, { type: 'stat', key: 'memory', amount: -5 }, { type: 'profile', key: 'Te', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Energie ↑ · Kontrola ↑ · Paměť ↓', statHints: { energy: 'up', control: 'up', memory: 'down' }, risk: 'medium' } },
  },

  failed_refusal: {
    id: 'failed_refusal',
    title: 'Neúspěšné odmítnutí',
    logLabel: 'FAILED_REFUSAL',
    scene: 'Odmítl jsi. Systém to zaznamenal. Jenže realita nepohnula ani pixelem. Odmítnutí, které nefunguje, je jen prosba v kostýmu hrdosti.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [FAILED_REFUSAL]:</span> odmítnutí nebylo přijato jako platný vstup.</p><p class="text">Řekl jsi ne. Slovo dopadlo na zem, odrazilo se a vrátilo se ti k nohám jako míček pro zoufalé.</p><p class="text"><span class="fx-outline hollow">NE</span> tady ještě neznamená hranici. Jen návrh. A návrhy systém čte jako materiál k připomínkování, protože očividně nestačilo, že lidstvo vynalezlo úřady.</p><p class="dialogS">„Zkus to znovu. Hranice bez opakování jsou v tomhle světě jen dekorativní provázek.“</p>`,
    sceneFx: ['scene-trap', 'scene-boundary', 'scene-warning'],
    yesLabel: 'ODMÍTNOUT ZNOVA',
    noLabel: 'PŘIJMOUT NAVZDORY',
    category: 'trap',
    rarity: 'common',
    tags: ['trap', 'routine', 'break'],
    yes: { resultText: 'Odmítl jsi znovu. Tentokrát to fungovalo. Alespoň na papíře. Systém má rád, když to zkusíš dvakrát.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: -3 }, { type: 'stat', key: 'memory', amount: 2 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'medium' } },
    no: { resultText: 'Přijal jsi navzdory odmítnutí. Byl to kompromis. Špatně definovaný. Ale fungoval. Zatím.', effects: [{ type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'energy', amount: 2 }, { type: 'stat', key: 'control', amount: -3 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'F', amount: 1 }], preview: { hint: 'Vazba ↑ · Energie ↑ · Kontrola ↓', statHints: { bond: 'up', energy: 'up', control: 'down' }, risk: 'medium' } },
  },

  quiet_room: {
    id: 'quiet_room',
    title: 'Tichá místnost',
    logLabel: 'QUIET_ROOM',
    scene: 'Nalezl jsi místnost bez signálu. Ticho tu neleží ve vzduchu, ale stojí uprostřed jako nábytek, který někdo zapomněl pojmenovat.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [QUIET_ROOM]:</span> lokální signál potlačen na minimum.</p><p class="text">Místnost nemá ozvěnu. Když uděláš krok, podlaha ho nepředá dál. Jen ho uloží někam dolů, do šedého měkkého místa.</p><p class="text"><span class="static-noise">Ticho</span> tu není prázdné. Má tvar. Přibližně tvar židle, na kterou si nemáš sedat, pokud máš ještě nějaké plány.</p><p class="dialogS">„Odpočinek bez signálu. Krásné. Izolace si konečně koupila aromalampu.“</p>`,
    sceneFx: ['scene-silent', 'scene-void', 'scene-rest'],
    yesLabel: 'ODPOČÍVAT',
    noLabel: 'HLEDAT VÝCHOD',
    category: 'silent',
    rarity: 'common',
    tags: ['silent', 'rest', 'pacing'],
    yes: { resultText: 'Odpočíval jsi v tichu. Ničeho jsi si neuvědomil. To bylo to nejlepší. Ticho tě vrátilo zpět do sektoru.', effects: [{ type: 'stat', key: 'energy', amount: 6 }, { type: 'stat', key: 'bond', amount: 2 }, { type: 'stat', key: 'memory', amount: 2 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'S', amount: 1 }], preview: { hint: 'Energie ↑ · Vazba ↑ · Paměť ↑', statHints: { energy: 'up', bond: 'up', memory: 'up' }, risk: 'low' } },
    no: { resultText: 'Hledal jsi východ. Místnost tě pustila do sektoru, který jsi nečekal. Bylo to dárek, nebo vtip?', effects: [{ type: 'moveSector', sectorId: 'mirror' }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'stat', key: 'memory', amount: 4 }, { type: 'profile', key: 'N', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Přesun do Zrcadla · Paměť ↑', statHints: { memory: 'up' }, risk: 'medium' } },
  },


  silent_room_answer: {
    id: 'silent_room_answer',
    title: 'Ticho odpovědělo',
    logLabel: 'SILENCE_REPLY',
    scene: 'Tichý režim fungoval. Pak ticho odpovědělo. Ne slovy. Horší. Souhlasem, který zněl jako zhasnutý pokoj.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SILENCE_REPLY]:</span> detekována odezva bez signálu.</p><p class="text">Ticho se nepohne. Jen přestane být pasivní. V místnosti se usadí souhlas, tak těžký, až se mu podlaha začne přizpůsobovat.</p><p class="text">Nikdo nemluví. Přesto je jasné, že odpověď přišla. To je na samotě nejhorší: občas ti začne dávat za pravdu.</p><p class="dialogS">„Slyšíš? Ne? Přesně. A stejně tě to právě odsoudilo.“</p>`,
    sceneFx: ['scene-silent', 'scene-followup', 'scene-void'],
    yesLabel: 'POSLOUCHAT TICHO',
    noLabel: 'ZAPNOUT SIGNÁLY',
    category: 'silent',
    rarity: 'uncommon',
    conditions: [{ type: 'hasFlag', flag: 'silent_mode_active' }],
    tags: ['silent', 'isolation', 'shadow'],
    yes: {
      resultText: 'Poslouchal jsi ticho. Bylo v něm pohodlí. A přesně tolik chladu, aby začalo být návykové.',
      effects: [
        { type: 'stat', key: 'bond', amount: -8 },
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'entityRelation', entity: 'shadow', delta: 2 },
        { type: 'unlockPool', poolId: 'shadow_pool' },
        { type: 'profile', key: 'I', amount: 2 },
        { type: 'profile', key: 'Ni', amount: 1 },
      ],
      preview: { hint: 'Vazba ↓ · Kontrola ↑ · Stín se přiblíží', statHints: { bond: 'down', control: 'up' }, risk: 'high' },
    },
    no: {
      resultText: 'Zapnul jsi signály. Svět se vrátil. Hlučný, protivný, ale aspoň ne mrtvý.',
      effects: [
        { type: 'stat', key: 'bond', amount: 7 },
        { type: 'stat', key: 'energy', amount: -4 },
        { type: 'removeFlag', flag: 'silent_mode_active' },
        { type: 'profile', key: 'Fe', amount: 1 },
        { type: 'profile', key: 'E', amount: 1 },
      ],
      preview: { hint: 'Vazba ↑ · Energie ↓', statHints: { bond: 'up', energy: 'down' }, risk: 'medium' },
    },
  },


  token_wants_name: {
    id: 'token_wants_name',
    title: 'Žeton chce jméno',
    logLabel: 'TOKEN_NAME',
    scene: 'Žeton se v kapse otočil. Na jedné straně se objevil prázdný řádek. Chce jméno. Ne nutně svoje.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [TOKEN/NAME]:</span> předmět žádá identifikátor. Nedoporučuje se dávat věcem jména, pokud už znají tvoji kapsu.</p><p class="text">Žeton se v kapse otočil sám. Ne cinknutím. Spíš malým rozhodnutím. Na jeho rezavém břiše se objevil prázdný řádek, tenký jako rána po něčem, co nikdy nebylo vysloveno.</p><p class="text">Chce <span class="fx-outline hollow">JMÉNO</span>. Ne nutně svoje. SYNTHOMA miluje situace, kdy se vlastnictví tváří jako něha a účet přijde až za šest tahů.</p><p class="dialogD">„Pojmenovat znamená přiznat vztah. Nepojmenovat znamená přiznat strach. Obě možnosti jsou zdanitelné.“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-token', 'scene-name', 'scene-memory'],
    yesLabel: 'DÁT MU JMÉNO',
    noLabel: 'NEPOJMENOVAT',
    category: 'item_trigger',
    rarity: 'rare',
    conditions: [{ type: 'hasItem', itemId: 'rusty_token' }],
    tags: ['item_trigger', 'token', 'memory', 'name'],
    yes: {
      resultText: 'Dal jsi mu jméno. Žeton přestal být předmětem a začal být problémem s osobností.',
      effects: [
        { type: 'removeItem', itemId: 'rusty_token' },
        { type: 'item', itemId: 'named_token' },
        { type: 'stat', key: 'bond', amount: 5 },
        { type: 'stat', key: 'memory', amount: 5 },
        { type: 'unlockPool', poolId: 'residuum_pool' },
        { type: 'profile', key: 'Fi', amount: 1 },
      ],
      preview: { hint: 'Žeton se změní · Vazba ↑ · Paměť ↑', statHints: { bond: 'up', memory: 'up' }, risk: 'medium' },
    },
    no: {
      resultText: 'Nepojmenoval jsi ho. Žeton zůstal věcí. Některé věci to berou jako urážku.',
      effects: [
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'stat', key: 'bond', amount: -4 },
        { type: 'schedule', cardId: 'unnamed_token_resentment', inTurns: 4 },
        { type: 'profile', key: 'Ti', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba ↓ · urážka později', statHints: { control: 'up', bond: 'down' }, risk: 'medium' },
    },
  },


  seal_squeaks: {
    id: 'seal_squeaks',
    title: 'Tuleň pískl',
    logLabel: 'SEAL_SIGNAL',
    scene: 'Gumový tuleň v kapse pískl. Ne hlasitě. Jen dostatečně na to, aby systém znejistěl.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SEAL/SIGNAL]:</span> gumový tuleň vydal zvuk. Systém žádá vysvětlení. Tuleň ho neposkytl, protože má úroveň.</p><p class="text">Gumový tuleň v kapse pískl. Ne hlasitě. Jen přesně tak, aby to slyšela část světa, která rozhoduje, jestli dneska přežiješ, nebo se staneš poučnou tabulkou.</p><p class="text">Na jeho břiše se na okamžik rozsvítí maličké razítko. Vypadá jako varování, které se stydí být užitečné.</p><p class="dialogG halo">„Tuleň někdy ví dřív než my. A není z toho tak dramatický. 🦊🦭“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-seal', 'scene-relic', 'scene-glitchka'],
    yesLabel: 'POSLECHNOUT',
    noLabel: 'UTIŠIT',
    category: 'item_trigger',
    rarity: 'uncommon',
    conditions: [{ type: 'hasItem', itemId: 'rubber_seal' }],
    tags: ['item_trigger', 'seal', 'glitchka', 'bond'],
    yes: {
      resultText: 'Poslechl jsi tuleně. Ukázal ploutví na místo, kde se realita tvářila příliš rovně.',
      effects: [
        { type: 'stat', key: 'bond', amount: 4 },
        { type: 'stat', key: 'control', amount: -3 },
        { type: 'entityRelation', entity: 'glitchka', delta: 2 },
        { type: 'schedule', cardId: 'seal_demands_stamp', inTurns: 4 },
        { type: 'profile', key: 'Fe', amount: 1 },
      ],
      preview: { hint: 'Vazba ↑ · Kontrola ↓ · tuleň něco chce', statHints: { bond: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Utišil jsi tuleně. Přestal pískat. Začal soudit. To je na gumovou věc dost ambiciózní.',
      effects: [
        { type: 'stat', key: 'control', amount: 5 },
        { type: 'stat', key: 'bond', amount: -4 },
        { type: 'flag', flag: 'seal_ignored' },
        { type: 'profile', key: 'Ti', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'medium' },
    },
  },


  // ── QUIET / ATMOSPHERIC CARDS ────────────────────────────────────────────────

  quiet_room_coat: {
    id: 'quiet_room_coat',
    title: 'Kabát na židli',
    logLabel: 'QUIET_ROOM',
    scene: 'Místnost je prázdná. Na židli leží kabát, který nikdo nepoznává. Přesto se mu všichni vyhýbají.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [QUIET/ROOM]:</span> místnost eviduje cizí oděv. Vlastník nedohledán. Nepřítomnost se chová aktivně.</p><p class="text">Místnost je prázdná takovým způsobem, který se musí udržovat. Na židli leží kabát. Není starý, není nový, není tvůj. A přesto se mu vyhýbáš, jako by v něm seděl někdo, kdo jen na chvíli odešel z těla.</p><p class="text">Látka se nehne. Jen drží tvar ramen. Občas je nejhorší přítomnost ta, která si dala pauzu.</p><p class="dialogS">„Kabát bez člověka. Skoro poetické. Nebo jen inventář po útěku, což je tady tradiční interiérový styl.“</p>`,
    sceneFx: ['scene-silent', 'scene-room', 'scene-coat', 'scene-memory'],
    yesLabel: 'SEDNOUT SI',
    noLabel: 'ODEJÍT',
    category: 'silent',
    rarity: 'common',
    tags: ['silent', 'memory', 'bond'],
    yes: {
      resultText: 'Sedl sis vedle kabátu. Nepromluvil. To bylo od něj ohleduplné a podezřelé.',
      effects: [
        { type: 'stat', key: 'memory', amount: 4 },
        { type: 'stat', key: 'energy', amount: -3 },
        { type: 'profile', key: 'I', amount: 1 },
        { type: 'profile', key: 'Ni', amount: 1 },
      ],
      preview: { hint: 'Paměť ↑ · Energie ↓', statHints: { memory: 'up', energy: 'down' }, risk: 'low' },
    },
    no: {
      resultText: 'Odešel jsi. Kabát zůstal. Některé věci přežijí právě proto, že se jich nikdo nedotkne.',
      effects: [
        { type: 'stat', key: 'control', amount: 3 },
        { type: 'stat', key: 'bond', amount: -2 },
        { type: 'profile', key: 'J', amount: 1 },
        { type: 'profile', key: 'Ti', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' },
    },
  },


  wall_laughter: {
    id: 'wall_laughter',
    title: 'Zeď se směje',
    logLabel: 'WALL_LAUGHTER',
    scene: 'Za zdí se někdo zasmál. Ne tobě. To by bylo jednodušší.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [WALL/LAUGHTER]:</span> akustická anomálie detekována za pevnou překážkou. Pevnost překážky je emocionálně nejistá.</p><p class="text">Za zdí se někdo zasmál. Ne tobě. To by bylo jednodušší, protože posměch má aspoň směr. Tohle byl smích někoho, kdo si pamatuje pointu události, kterou jsi ještě nezažil.</p><p class="text">Omítka je studená. Když se přiblížíš, zdá se, že zeď zadržuje dech, aby neprozradila další větu.</p><p class="dialogS">„Smějící se zeď. Interiérový design pro lidi, kterým obyčejná úzkost připadala málo prostorová.“</p>`,
    sceneFx: ['scene-silent', 'scene-wall', 'scene-laugh', 'scene-mystery'],
    yesLabel: 'PŘILOŽIT UCHO',
    noLabel: 'ODEJÍT',
    category: 'silent',
    rarity: 'common',
    tags: ['silent', 'wall', 'laugh', 'mystery'],
    yes: {
      resultText: 'Přiložil jsi ucho. Smích ztichl. Pak se přesunul blíž.',
      effects: [
        { type: 'flag', flag: 'heard_wall_laughter' },
        { type: 'schedule', cardId: 'wall_laughter_returns', inTurns: 5 },
        { type: 'stat', key: 'memory', amount: 2 },
        { type: 'profile', key: 'N', amount: 1 },
      ],
      preview: { hint: 'Něco sis poslechl · vrátí se', statHints: { memory: 'up' }, risk: 'unknown' },
    },
    no: {
      resultText: 'Odešel jsi. Zeď se zasmála znovu, tentokrát trochu víc jako někdo, kdo vyhrál.',
      effects: [
        { type: 'stat', key: 'control', amount: 3 },
        { type: 'flag', flag: 'ignored_wall_laughter' },
        { type: 'profile', key: 'J', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · zeď si to pamatuje', statHints: { control: 'up' }, risk: 'low' },
    },
  },


  mirror_shards_argue: {
    id: 'mirror_shards_argue',
    title: 'Střepy se hádají',
    logLabel: 'MIRROR_SHARDS_ARGUE',
    scene: 'Střepy v kapse se hádají, která verze tebe byla nejméně trapná. Hlasování zatím nikam nevede.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [MIRROR/DEBATE]:</span> střepy zahájily interní komisi. Téma: nejméně trapná verze subjektu.</p><p class="text">Střepy v kapse se hádají. Jeden tvrdí, že jsi byl nejlepší, když jsi mlčel. Druhý namítá, že to nebyla kvalita, jen výpadek signálu. Třetí se snaží najít kompromis a krvácí odrazem.</p><p class="text">Hlasování zatím nikam nevede. Demokracie mezi částmi identity je přesně tak produktivní, jak zní.</p><p class="dialogS">„Nech střepy mluvit. Třeba konečně vznikne týmová porada, kde se rozbije i zápis.“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-mirror', 'scene-identity', 'scene-comic'],
    yesLabel: 'NECHAT JE MLUVIT',
    noLabel: 'ZATŘÁST KAPSOU',
    category: 'item_trigger',
    rarity: 'uncommon',
    conditions: [{ type: 'hasItem', itemId: 'mirror_shard' }],
    tags: ['item_trigger', 'mirror', 'identity'],
    yes: {
      resultText: 'Nechal jsi je mluvit. Některé verze se mýlily. Některé bohužel ne.',
      effects: [
        { type: 'stat', key: 'memory', amount: 7 },
        { type: 'stat', key: 'bond', amount: -3 },
        { type: 'unlockPool', poolId: 'mirror_pool' },
        { type: 'profile', key: 'Ni', amount: 2 },
      ],
      preview: { hint: 'Paměť ↑ · Vazba ↓ · Zrcadlo', statHints: { memory: 'up', bond: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Zatřásl jsi kapsou. Střepy zmlkly. To nebylo vítězství, jen technické umlčení.',
      effects: [
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'stat', key: 'memory', amount: -5 },
        { type: 'profile', key: 'Ti', amount: 1 },
        { type: 'profile', key: 'J', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Paměť ↓', statHints: { control: 'up', memory: 'down' }, risk: 'low' },
    },
  },


  soft_bug_grows: {
    id: 'soft_bug_grows',
    title: 'Měkká chyba vyrostla',
    logLabel: 'SOFT_BUG_GROWS',
    scene: 'Měkká chyba vyrostla. Už má nožičky, názor a malý odpor k optimalizaci.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SOFT/BUG/GROWTH]:</span> chyba získala nožičky, názor a odpor k optimalizaci. Vývoj softwaru se cítí dotčen.</p><p class="text">Měkká chyba vyrostla. Už má nožičky, názor a malý odpor k optimalizaci. Leze po okraji kapsy a tváří se, že patří do rodiny. Což je trik, který používají jak chyby, tak některé vzpomínky.</p><p class="text">Na dece se objevilo jméno, které nikdo nenapsal. Zatím jen první písmeno. Zbytek čeká, jestli budeš dost nerozumný.</p><p class="dialogS">„Pojmenovat chybu. Jasně. Takhle vznikají mazlíčci, závislosti a většina legacy kódu.“</p>`,
    sceneFx: ['scene-item-trigger', 'scene-soft-bug', 'scene-glitchka', 'scene-growth'],
    yesLabel: 'POJMENOVAT JI',
    noLabel: 'ODINSTALOVAT',
    category: 'item_trigger',
    rarity: 'uncommon',
    conditions: [{ type: 'hasItem', itemId: 'soft_bug' }],
    tags: ['item_trigger', 'glitch', 'glitchka', 'bug'],
    yes: {
      resultText: 'Pojmenoval jsi ji. Teď už není chyba. Je to člen domácnosti, což je technicky mnohem horší.',
      effects: [
        { type: 'removeItem', itemId: 'soft_bug' },
        { type: 'item', itemId: 'named_soft_bug' },
        { type: 'stat', key: 'bond', amount: 7 },
        { type: 'stat', key: 'control', amount: -5 },
        { type: 'unlockPool', poolId: 'glitchka_pool' },
        { type: 'entityRelation', entity: 'glitchka', delta: 2 },
        { type: 'profile', key: 'Fi', amount: 1 },
        { type: 'profile', key: 'Ne', amount: 1 },
      ],
      preview: { hint: 'Pojmenovaná chyba · Vazba ↑ · Kontrola ↓ · Glitchka pool', statHints: { bond: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Odinstaloval jsi ji. Systém oznámil úspěch. Glitchka oznámila ticho. To druhé bolelo víc.',
      effects: [
        { type: 'removeItem', itemId: 'soft_bug' },
        { type: 'stat', key: 'control', amount: 8 },
        { type: 'stat', key: 'bond', amount: -6 },
        { type: 'entityRelation', entity: 'glitchka', delta: -3 },
        { type: 'schedule', cardId: 'glitchka_finds_empty_blanket', inTurns: 5 },
        { type: 'profile', key: 'Te', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑↑ · Vazba ↓ · Glitchka vztah ↓', statHints: { control: 'up', bond: 'down' }, risk: 'high' },
    },
  },


    // ── RARE STABILIZATION CARDS ────────────────────────────────────────────────

  four_reactors_align: {
    id: 'four_reactors_align',
    title: 'Čtyři reaktory se srovnaly',
    logLabel: 'STABILIZATION_HINT',
    scene: 'Čtyři reaktory na chvíli blikly stejným rytmem. Systém se tvářil, že to plánoval. Neplánoval.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [STABILIZATION]:</span> čtyři reaktory zachytily společný rytmus. Pravděpodobnost náhody: urážlivě vysoká.</p><p class="text">Energie, Paměť, Vazba a Kontrola bliknou ve stejném tempu. Ne harmonicky. Ne krásně. Spíš jako čtyři unavení lidé, kteří se na vteřinu shodli, že dneska neumřou.</p><p class="text">Střed není triumf. Je to příměří. A příměří v SYNTHOMĚ má hodnotu malého zázraku, jen s horším pojištěním.</p><p class="dialogS">„Nepřeháněj nadšení. Rovnováha není osvícení. Je to jen stav, kdy žádná část tebe právě netříská hlavou o server.“</p>`,
    sceneFx: ['scene-stabilization', 'scene-balance', 'scene-reactors', 'scene-rare'],
    yesLabel: 'UDRŽET RYTMUS',
    noLabel: 'VYUŽÍT OKNO',
    category: 'rare',
    rarity: 'rare',
    tags: ['stabilization', 'balance', 'rare'],
    yes: {
      resultText: 'Udržel jsi rytmus. Ne dokonale. Dostatečně. Což je v SYNTHOMĚ skoro provokace.',
      effects: [
        { type: 'stat', key: 'energy', amount: -3 },
        { type: 'stat', key: 'memory', amount: -3 },
        { type: 'stat', key: 'bond', amount: 3 },
        { type: 'stat', key: 'control', amount: 3 },
        { type: 'profile', key: 'J', amount: 1 },
      ],
      preview: { hint: 'Jemné dorovnání · stabilizace', risk: 'low' },
    },
    no: {
      resultText: 'Využil jsi okno. Získal jsi pohyb, ale rytmus se rozpadl. Samozřejmě, že i rovnováha má náklady.',
      effects: [
        { type: 'stat', key: 'energy', amount: 6 },
        { type: 'stat', key: 'control', amount: -5 },
        { type: 'moveSector', sectorId: 'void' },
        { type: 'profile', key: 'P', amount: 1 },
      ],
      preview: { hint: 'Energie ↑ · Kontrola ↓ · návrat do Prázdnoty', statHints: { energy: 'up', control: 'down' }, risk: 'medium' },
    },
  },


  stable_enough: {
    id: 'stable_enough',
    title: 'Dostatečně stabilní',
    logLabel: 'STABLE_ENOUGH',
    scene: 'Systém hledal dokonalost. Nenašel ji. Pak neochotně připustil, že dostatečné možná stačí. Historický okamžik pro všechny perfekcionisty v sále.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [STABLE_ENOUGH]:</span> dokonalost nenalezena. Funkčnost s odporem přijata.</p><p class="text">Systém projede kontrolní seznam třikrát. Něco nesedí. Něco chybí. Něco má emocionální vlhkost na místech, kde by normální software měl suchou dokumentaci.</p><p class="text">A přesto se nerozpadáš. Což je znepokojivé hlavně pro všechny moduly, které si myslely, že přežití musí vypadat elegantně.</p><p class="dialogS">„Dostatečně stabilní. Krásná fráze pro subjekt, který stojí na jedné noze a tvrdí, že je to design.“</p>`,
    sceneFx: ['scene-stabilization', 'scene-enough', 'scene-control', 'scene-soft-win'],
    yesLabel: 'PŘIJMOUT NEDOKONALOST',
    noLabel: 'DOLADIT DETAILY',
    category: 'rare',
    rarity: 'rare',
    tags: ['stabilization', 'control', 'self'],
    yes: {
      resultText: 'Přijal jsi nedokonalost. Něco v systému prasklo. Nebyla to chyba. Byla to úleva.',
      effects: [
        { type: 'stat', key: 'control', amount: -8 },
        { type: 'stat', key: 'bond', amount: 5 },
        { type: 'imprint', imprintId: 'unfinished_conversation' },
        { type: 'profile', key: 'Fi', amount: 2 },
      ],
      preview: { hint: 'Kontrola ↓ · Vazba ↑ · imprint', statHints: { control: 'down', bond: 'up' }, risk: 'medium' },
    },
    no: {
      resultText: 'Doladil jsi detaily. Detaily přivedly další detaily. Některé měly děti.',
      effects: [
        { type: 'stat', key: 'control', amount: 9 },
        { type: 'stat', key: 'energy', amount: -5 },
        { type: 'schedule', cardId: 'audit_siren', inTurns: 4 },
        { type: 'profile', key: 'J', amount: 2 },
      ],
      preview: { hint: 'Kontrola ↑ · Energie ↓ · audit', statHints: { control: 'up', energy: 'down' }, risk: 'high' },
    },
  },


  quiet_compromise: {
    id: 'quiet_compromise',
    title: 'Tichý kompromis',
    logLabel: 'QUIET_COMPROMISE',
    scene: 'Prázdnota nabídla kompromis. Ne hezký. Ne čistý. Jen takový, který by možná přežil do rána.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [VOID/COMPROMISE]:</span> Prázdnota nabízí dočasné urovnání. Důvěra není součástí balíčku.</p><p class="text">Prázdnota neotevře dveře. Jen trochu povolí tlak ve zdech. V rohu se objeví židle, která nevypadá bezpečně, ale aspoň nevypadá aktivně zlomyslně.</p><p class="text">Kompromis není kapitulace. Někdy je to jen způsob, jak nepřijít o poslední funkční kus sebe kvůli estetice hrdinství.</p><p class="dialogS">„Chceš víc. Samozřejmě. Lidská duše dostane deku a hned vyjednává o ústředním topení.“</p>`,
    sceneFx: ['scene-stabilization', 'scene-void', 'scene-compromise', 'scene-quiet'],
    yesLabel: 'PŘIJMOUT',
    noLabel: 'CHTÍT VÍC',
    category: 'rare',
    rarity: 'rare',
    tags: ['stabilization', 'void', 'rare'],
    yes: {
      resultText: 'Přijal jsi kompromis. Systém si oddechl tónem, který okamžitě popřel.',
      effects: [
        { type: 'stat', key: 'energy', amount: -5 },
        { type: 'stat', key: 'memory', amount: -5 },
        { type: 'stat', key: 'bond', amount: 5 },
        { type: 'stat', key: 'control', amount: 5 },
        { type: 'profile', key: 'F', amount: 1 },
        { type: 'profile', key: 'J', amount: 1 },
        { type: 'flag', flag: 'compromise_taken' },
      ],
      preview: { hint: 'Dorovnání k přežití', risk: 'low' },
    },
    no: {
      resultText: 'Chtěl jsi víc. Prázdnota se zasmála. Ambice je krásná věc, dokud nemá zuby.',
      effects: [
        { type: 'stat', key: 'energy', amount: 8 },
        { type: 'stat', key: 'control', amount: -6 },
        { type: 'profile', key: 'E', amount: 1 },
        { type: 'profile', key: 'P', amount: 1 },
      ],
      preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' },
    },
  },


  seal_of_not_dying_today: {
    id: 'seal_of_not_dying_today',
    title: 'Razítko dnešního neumření',
    logLabel: 'SEAL_NOT_DYING',
    scene: 'Gumové razítko dopadlo na prázdný formulář. Text zněl: „DNES NEUMŘÍT“. Byrokracie poprvé zněla skoro laskavě.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SEALARIUM]:</span> razítko dnešního neumření připraveno. Ano, i naděje má kolonku.</p><p class="text">Gumové razítko dopadne na formulář s takovou vážností, až se úřední prach na stole postaví do pozoru. Text se vpálí do papíru: <span class="fx-neon">DNES NEUMŘÍT</span>.</p><p class="text">Je to směšné. Je to byrokratické. Je to skoro něžné. SYNTHOMA objevila péči ve tvaru razítka, takže civilizace může klidně zhasnout.</p><p class="dialogS">„Neoslavuj. Máš papírovou výjimku ze smrti, ne životní plán.“</p>`,
    sceneFx: ['scene-stabilization', 'scene-seal', 'scene-office', 'scene-not-dying'],
    yesLabel: 'PŘIJMOUT RAZÍTKO',
    noLabel: 'ODMÍTNOUT PAPÍROVOU NADĚJI',
    category: 'rare',
    rarity: 'rare',
    conditions: [{ type: 'hasItem', itemId: 'rubber_stamp' }],
    tags: ['stabilization', 'rubber_stamp', 'sealarium'],
    yes: {
      resultText: 'Přijal jsi razítko. Nikdo netvrdí, že tě zachrání navždy. Dnešek je ale taky jednotka času, bohužel.',
      effects: [
        { type: 'stat', key: 'bond', amount: 6 },
        { type: 'stat', key: 'control', amount: 4 },
        { type: 'unlockPool', poolId: 'sealarium_pool' },
        { type: 'profile', key: 'Fe', amount: 1 },
        { type: 'profile', key: 'J', amount: 1 },
      ],
      preview: { hint: 'Vazba ↑ · Kontrola ↑ · Tulenárium', statHints: { bond: 'up', control: 'up' }, risk: 'low' },
    },
    no: {
      resultText: 'Odmítl jsi papírovou naději. Slušné. Hloupé. Působivé. Lidské rozhodování v kostce.',
      effects: [
        { type: 'stat', key: 'energy', amount: 5 },
        { type: 'stat', key: 'control', amount: -5 },
        { type: 'entityRelation', entity: 'form', delta: -1 },
        { type: 'profile', key: 'Fi', amount: 1 },
      ],
      preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' },
    },
  },


  diagnostic_finding_collector: {
    id: 'diagnostic_finding_collector',
    title: 'Diagnostický nález: sběrač podezřelých věcí',
    logLabel: 'DIAGNOSTIC_FINDING',
    scene: 'Systém zaznamenal, že bereš podezřelé předměty s důvěrou člověka, který nikdy neviděl horor. Působivé. Smutné. Užitečné.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [DIAGNOSTIC/FINDING]:</span> sběr podezřelých předmětů překročil hranici roztomilé patologie.</p><p class="text">Systém promítne seznam věcí, které sis vzal, i když každá z nich křičela „následek“. Žeton. Střep. Formulář. Možná i něco, co mělo oči a nemělo účtenku.</p><p class="text">Diagnóza zní: <span class="fx-outline is-lit">Sběrač podezřelých věcí</span>. V běžném světě by to byl problém. V SYNTHOMĚ je to životopis.</p><p class="dialogS">„Nevím, jestli jsi odvážný, zvědavý, nebo jen magnet na vedlejší účinky. Pravděpodobně ano.“</p>`,
    sceneFx: ['scene-meta', 'scene-diagnostic', 'scene-object', 'scene-finding'],
    yesLabel: 'PŘIJMOUT NÁLEZ',
    noLabel: 'ZPOCHYBNIT STATISTIKU',
    category: 'rare',
    rarity: 'rare',
    tags: ['meta', 'diagnostic', 'object'],
    yes: {
      resultText: 'Přijal jsi nález. Kapsa se zavrtěla, jako by byla pyšná. To je znepokojivě mnoho emocí na kapsu.',
      effects: [
        { type: 'imprint', imprintId: 'noise_resident' },
        { type: 'stat', key: 'bond', amount: 4 },
        { type: 'stat', key: 'control', amount: -3 },
        { type: 'unlockPool', poolId: 'market_pool' },
        { type: 'profile', key: 'P', amount: 1 },
      ],
      preview: { hint: 'Imprint · Market pool · Vazba ↑', statHints: { bond: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Zpochybnil jsi statistiku. Systém ukázal účtenky. Všechny. To bylo podlé i na systém.',
      effects: [
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'stat', key: 'memory', amount: 4 },
        { type: 'profile', key: 'Ti', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Paměť ↑', statHints: { control: 'up', memory: 'up' }, risk: 'medium' },
    },
  },


  dormant_signal: {
    id: 'dormant_signal',
    title: 'Spící signál',
    logLabel: 'META_DORMANT',
    scene: 'V prázdnotě je signál, který čekal. Ne na tebe. Jen čekal. Ale přišel jsi, tak.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [DORMANT_SIGNAL]:</span> neaktivní signál vykazuje trpělivost. Podezřelé.</p><p class="text">V Prázdnotě bliká malý bod. Nevolá tě. Neprosí. Jen čeká s typem klidu, který nemívají bezpečné věci. Spící procesy jsou jako staré zprávy: vypadají mrtvě, dokud je neotevřeš.</p><p class="text"><span class="fx-outline hollow">Probudit</span> znamená přiznat, že něco v tobě ještě reaguje. Nechat spát znamená přiznat totéž, jen zbaběleji.</p><p class="dialogS">„Signál, který nespěchá, je buď moudrý, nebo ví, že nemáš kam utéct.“</p>`,
    sceneFx: ['scene-meta', 'scene-dormant', 'scene-signal', 'scene-energy-low'],
    yesLabel: 'PROBUDIT HO',
    noLabel: 'NECHAT SPÁT',
    category: 'silent',
    rarity: 'rare',
    conditions: [{ type: 'unlockedPool', poolId: 'dormant' }],
    qualityHint: 'narrative_pause',
    tags: ['meta', 'energy', 'low', 'death_history', 'dormant', 'post_shutdown'],
    yes: {
      resultText: 'Probudil jsi ho. Něco začalo vypadávat ze stínů. Nebyl to monster. Byl to plán.',
      effects: [
        { type: 'stat', key: 'energy', amount: 8 },
        { type: 'stat', key: 'control', amount: -5 },
        { type: 'unlockPool', poolId: 'glitch_pool' },
        { type: 'profile', key: 'Ne', amount: 2 },
      ],
      preview: { hint: 'Energie ↑ · Kontrola ↓ · Glitch pool', statHints: { energy: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Nechal jsi ho spát. Signál se pohnul ve spánku. Někdy jsou sny hlasitější než probuzení.',
      effects: [
        { type: 'stat', key: 'memory', amount: 4 },
        { type: 'stat', key: 'bond', amount: 3 },
        { type: 'profile', key: 'Si', amount: 1 },
      ],
      preview: { hint: 'Paměť ↑ · Vazba ↑', statHints: { memory: 'up', bond: 'up' }, risk: 'low' },
    },
  },
};
