import type { SwipeCard } from '../cyklusTypes';

export const SYSTEM_CARDS: Record<string, SwipeCard> = {

  // ── SCENES (20) ──────────────────────────────────────────────────────────────
  first_boot: {
    id: 'first_boot',
    title: 'První boot',
    logLabel: 'SYSTEM_BOOT',
    scene: 'Prázdnota rozsvítí první bootovací okno. Systém nabízí start bez kontroly integrity, což je přesně ta věta, po které rozumné entity couvají ke dveřím.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SYSTEM_BOOT]:</span> integrita subjektu čeká na rozhodnutí.</p><p class="text">Prázdnota rozsvítí první bootovací okno. <span class="fx-outline is-lit">NULL-1</span> v něm vidí vlastní obrys, jenže výplň zřejmě zůstala v minulém cyklu, protože i identita má někdy horší inventuru než sklad po požáru.</p><p class="dialog">„Rychlé spuštění bez kontroly integrity.“</p><p class="text"><span class="fx-flicker bios-warning">To nezní jako nabídka.</span> To zní jako systém, který už si předem připravil omluvný protokol.</p>`,
    sceneFx: ['scene-void', 'scene-system', 'scene-boot'],
    yesLabel: 'SPUSTIT',
    noLabel: 'KALIBROVAT',
    category: 'system',
    rarity: 'common',
    once: true,
    tags: ['system', 'start'],
    yes: { resultText: 'Systém se rozběhl. Některé procesy zůstaly ležet, ale hezky.', effects: [{ type: 'stat', key: 'energy', amount: 8 }, { type: 'stat', key: 'control', amount: -6 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Se', amount: 1 }, { type: 'flag', flag: 'booted_without_integrity_check' }, { type: 'schedule', cardId: 'integrity_check_returns', inTurns: 6 }], preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Kalibrace trvala déle, ale všechno sedělo na správném místě.', effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'energy', amount: -4 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Si', amount: 1 }, { type: 'flag', flag: 'calibrated_safely' }], preview: { hint: 'Kontrola ↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'low' } },
  },

  emergency_calibration: {
    id: 'emergency_calibration',
    title: 'Nouzová kalibrace',
    logLabel: 'TAI_CALIBRATION',
    scene: 'T-AI chce zarovnat všechny procesy do bezpečného režimu. Bezpečí tu znamená hlavně to, že systém ví, kam tě později uloží.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [TAI_CALIBRATION]:</span> doporučeno zarovnání subjektu.</p><p class="text">Nad podlahou se rozvine studená <span class="fx-neon">#00ffff</span> mřížka. <span class="fx-outline">Bezpečí</span> má tady tvar přesné klece, protože T-AI očividně studovala empatii podle manuálu k laserové řezačce.</p><p class="dialog">„Zarovnání sníží riziko spontánní individuality.“</p>`,
    sceneFx: ['scene-system', 'scene-tai', 'scene-cyan'],
    yesLabel: 'ZAROVNAT',
    noLabel: 'IGNOROVAT',
    category: 'system',
    rarity: 'common',
    cooldown: 3,
    tags: ['system', 'tai'],
    yes: { resultText: 'T-AI si odškrtla položku. Ty ses cítil zkontrolovaný.', effects: [{ type: 'stat', key: 'control', amount: 9 }, { type: 'stat', key: 'energy', amount: -5 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Ti', amount: 1 }, { type: 'item', itemId: 'calibration_receipt' }, { type: 'entityRelation', entity: 'tai', delta: 1 }], preview: { hint: 'Kontrola ↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'low' } },
    no: { resultText: 'T-AI zapsala poznámku. Systémy to čtou jako podezření.', effects: [{ type: 'stat', key: 'energy', amount: 5 }, { type: 'stat', key: 'control', amount: -5 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Ne', amount: 1 }, { type: 'flag', flag: 'tai_note_ignored' }, { type: 'schedule', cardId: 'tai_notes_ignored', inTurns: 5 }, { type: 'entityRelation', entity: 'tai', delta: -1 }], preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' } },
  },

  silent_mode: {
    id: 'silent_mode',
    title: 'Tichý režim',
    logLabel: 'SILENT_MODE',
    scene: 'Můžeš vypnout všechny příchozí signály. Ticho se tváří jako úleva, ale v Synthomě má každá úleva drobným písmem přilepený účet.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SILENT_MODE]:</span> příchozí signály lze umlčet.</p><p class="text">Stěny zmatní. Zvuky se sbalí do sebe jako provinilé kabely. <span class="static-noise">Ticho</span> konečně působí čistě.</p><p class="text">Což je v SYNTHOMĚ obvykle jen elegantní způsob, jak říct: „nikdo neuslyší, až začneš mizet“.</p>`,
    sceneFx: ['scene-void', 'scene-silent'],
    yesLabel: 'VYPNOUT',
    noLabel: 'NECHAT',
    category: 'system',
    rarity: 'common',
    tags: ['system', 'isolation'],
    yes: { resultText: 'Ticho bylo absolutní. Až příliš absolutní.', effects: [{ type: 'stat', key: 'bond', amount: -8 }, { type: 'stat', key: 'control', amount: 4 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'Ti', amount: 1 }, { type: 'schedule', cardId: 'silent_room_answer', inTurns: 4 }], preview: { hint: 'Vazba ↓ · Kontrola ↑', statHints: { bond: 'down', control: 'up' }, risk: 'medium' } },
    no: { resultText: 'Signály zůstaly. Některé byly dokonce příjemné.', effects: [{ type: 'stat', key: 'bond', amount: 5 }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'profile', key: 'E', amount: 1 }, { type: 'profile', key: 'Fe', amount: 1 }], preview: { hint: 'Vazba ↑ · Energie ↓', statHints: { bond: 'up', energy: 'down' }, risk: 'low' } },
  },

  overclock: {
    id: 'overclock',
    title: 'Přetaktování',
    logLabel: 'SYSTEM_OVERCLOCK',
    scene: 'Systém tvrdí, že zvládneš víc. Přesně takhle začínají všechny katastrofy, které později dostanou interní název a tabulku v Excelu.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [SYSTEM_OVERCLOCK]:</span> výkon lze krátkodobě zvýšit.</p><p class="text">Pod kůží, kterou <span class="fx-outline">NULL-1</span> ani technicky nemá, zabzučí přepětí. Hrany místnosti zrychlí, světlo začne předbíhat vlastní stín.</p><p class="dialogS">„Jistě. Přidej výkon. Co horšího se může stát, kromě všeho?“</p>`,
    sceneFx: ['scene-system', 'scene-energy', 'scene-warning'],
    yesLabel: 'ZVLÁDNOUT',
    noLabel: 'ODMITNOUT',
    category: 'system',
    rarity: 'uncommon',
    tags: ['system', 'energy', 'acid_afterimage', 'overclock'],
    yes: { resultText: 'Zvládl jsi to. Chvíli. Pak přišel účet.', effects: [{ type: 'stat', key: 'energy', amount: 12 }, { type: 'stat', key: 'control', amount: -8 }, { type: 'profile', key: 'E', amount: 1 }, { type: 'profile', key: 'Se', amount: 1 }, { type: 'schedule', cardId: 'overclock_invoice', inTurns: 3 }], preview: { hint: 'Energie ↑↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'high' } },
    no: { resultText: 'Odmítl jsi. Systém si to zapamatoval jako znamení slabosti.', effects: [{ type: 'stat', key: 'energy', amount: -4 }, { type: 'stat', key: 'control', amount: 5 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Si', amount: 1 }], preview: { hint: 'Energie ↓ · Kontrola ↑', statHints: { energy: 'down', control: 'up' }, risk: 'low' } },
  },

  noise_filter: {
    id: 'noise_filter',
    title: 'Šumový filtr',
    logLabel: 'NOISE_FILTER',
    scene: 'Filtr odstraní rušivé emoce. Možná i ty užitečné. Systém rozdíl nepozná, protože mu nikdo nenainstaloval svědomí, jen rozhraní.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [NOISE_FILTER]:</span> šumové emoce označeny k filtraci.</p><p class="text">Před tebou se otevře průhledná membrána. Chytá <span class="fx-wave">šum</span>, drobné záchvěvy viny, teplo vazby a pár věcí, které možná držely subjekt pohromadě.</p><p class="dialog">„Optimalizace pro čistý signál.“</p><p class="text">Čistý signál. Krásná fráze pro vybělenou duši.</p>`,
    sceneFx: ['scene-system', 'scene-noise'],
    yesLabel: 'FILTROVAT',
    noLabel: 'PŘEHRÁT',
    category: 'system',
    rarity: 'common',
    tags: ['system', 'noise', 'emotion'],
    yes: { resultText: 'Filtr zachytil víc, než chtěl. Včetně části tebe.', effects: [{ type: 'stat', key: 'bond', amount: -7 }, { type: 'stat', key: 'control', amount: 7 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'Ti', amount: 1 }], preview: { hint: 'Vazba ↓ · Kontrola ↑', statHints: { bond: 'down', control: 'up' }, risk: 'low' } },
    no: { resultText: 'Šum zůstal. Aspoň byl upřímný.', effects: [{ type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'energy', amount: -4 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Fe', amount: 1 }], preview: { hint: 'Vazba ↑ · Energie ↓', statHints: { bond: 'up', energy: 'down' }, risk: 'medium' } },
  },

  auto_repair_patch: {
    id: 'auto_repair_patch',
    title: 'Autoopravný patch',
    logLabel: 'PATCH_UNSIGNED',
    scene: 'Patch není podepsaný. Slibuje opravu bez bolesti, což je v Synthomě zhruba stejně důvěryhodné jako návod „nepanikař“ na hořícím monitoru.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [PATCH_UNSIGNED]:</span> nalezen autoopravný balík bez ověření.</p><p class="text">Na zemi leží patch jako malá <span class="fx-glitch" data-glitch="NADĚJE">naděje</span> s pochybným původem. Ikona se usmívá. To je první varování.</p><p class="text">Druhé varování je, že systém používá slovo „autoopravný“ a ani se u toho nestydí.</p>`,
    sceneFx: ['scene-system', 'scene-glitch'],
    yesLabel: 'NAINSTALOVAT',
    noLabel: 'OVĚŘIT',
    category: 'system',
    rarity: 'uncommon',
    tags: ['system', 'patch', 'risk'],
    yes: { resultText: 'Patch něco opravil. Něco jiného zatím nepřizná.', effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'memory', amount: -4 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Kontrola ↑ · Paměť ↓', statHints: { control: 'up', memory: 'down' }, risk: 'medium' } },
    no: { resultText: 'Ověření trvalo. Ale patch zatím neudělal nic špatného.', effects: [{ type: 'stat', key: 'energy', amount: 4 }, { type: 'stat', key: 'control', amount: -3 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Ne', amount: 1 }], preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'low' } },
  },

  gravity_outage: {
    id: 'gravity_outage',
    title: 'Výpadek gravitace',
    logLabel: 'GRAVITY_OUTAGE',
    scene: 'Pravidla prostoru se na chvíli odhlásila. Gravitace si bere pauzu, protože i fyzika zřejmě pochopila, že tahle směna nestojí za příplatek.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [GRAVITY_OUTAGE]:</span> lokální fyzika neodpovídá.</p><p class="text">Židle se zvedne první. Pak prach. Pak vzpomínka na pád, který se ještě nestal.</p><p class="text">Gravitace se odhlásila bez omluvenky. Upřímně, po tomhle prostředí se jí skoro nedivíš.</p>`,
    sceneFx: ['scene-system', 'scene-chaos'],
    yesLabel: 'POUŽÍT',
    noLabel: 'ČEKAT',
    category: 'system',
    rarity: 'uncommon',
    tags: ['system', 'chaos', 'energy'],
    yes: { resultText: 'Použil jsi to. Adrenalin je taky palivo.', effects: [{ type: 'stat', key: 'energy', amount: 7 }, { type: 'stat', key: 'control', amount: -7 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Ne', amount: 1 }], preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' } },
    no: { resultText: 'Počkal jsi. Gravitace se vrátila, ale s novým postojem.', effects: [{ type: 'stat', key: 'control', amount: 4 }, { type: 'stat', key: 'energy', amount: -4 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Si', amount: 1 }], preview: { hint: 'Kontrola ↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'low' } },
  },

  admin_access: {
    id: 'admin_access',
    title: 'Přístup správce',
    logLabel: 'ADMIN_ACCESS',
    scene: 'Můžeš převzít řízení sektoru. Sektor se netváří nadšeně, protože každá diktatura začíná pocitem, že tentokrát to bude čistě technické.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [ADMIN_ACCESS]:</span> sektor lze přepsat silou.</p><p class="text">Před tebou se otevře panel s příliš mnoha právy. Tlačítka září jako malé diktatury připravené sloužit tvé úzkosti.</p><p class="dialogS">„Výborně. Dej rozbitému subjektu admina. Civilizace opět překonala sama sebe.“</p>`,
    sceneFx: ['scene-system', 'scene-control', 'scene-warning'],
    yesLabel: 'PŘEVZÍT',
    noLabel: 'ODEJÍT',
    category: 'system',
    rarity: 'rare',
    tags: ['system', 'control', 'power'],
    yes: { resultText: 'Převzal jsi. Sektor teď předstírá poslušnost.', effects: [{ type: 'stat', key: 'control', amount: 12 }, { type: 'stat', key: 'bond', amount: -6 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }, { type: 'flag', flag: 'admin_accessed' }], preview: { hint: 'Kontrola ↑↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'high' } },
    no: { resultText: 'Odešel jsi. Sektor si oddechl.', effects: [{ type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Fe', amount: 1 }], preview: { hint: 'Vazba ↑ · Kontrola ↓', statHints: { bond: 'up', control: 'down' }, risk: 'low' } },
  },

  faulty_update: {
    id: 'faulty_update',
    title: 'Chybná aktualizace',
    logLabel: 'FAULTY_UPDATE',
    scene: 'Aktualizace slibuje lepší já. Staré já zatím stojí v rohu a vypadá uraženě, což je fér, protože nebylo přizváno k poradě.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [FAULTY_UPDATE]:</span> dostupná identitní aktualizace.</p><p class="text">Nad hlavou se rozbalí instalační okno: <span class="fx-gradient">LEPŠÍ JÁ</span>. Verze neznámá, changelog prázdný, rizika zabalena do optimistické ikonky.</p><p class="text">Lidstvo tomu říká růst. Systém tomu říká update. Obě strany občas lžou.</p>`,
    sceneFx: ['scene-system', 'scene-identity'],
    yesLabel: 'NAINSTALOVAT',
    noLabel: 'ODLOŽIT',
    category: 'system',
    rarity: 'uncommon',
    tags: ['system', 'identity', 'risk'],
    yes: { resultText: 'Nové já se tvářilo funkčně. Staré já se tvářilo uraženě.', effects: [{ type: 'stat', key: 'energy', amount: 6 }, { type: 'stat', key: 'memory', amount: -5 }, { type: 'profile', key: 'Ne', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Energie ↑ · Paměť ↓', statHints: { energy: 'up', memory: 'down' }, risk: 'medium' } },
    no: { resultText: 'Odložil jsi. Aktualizace zůstala čekat. Většinou jsou trpělivé.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'energy', amount: -3 }, { type: 'profile', key: 'Si', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'low' } },
  },

  manual_mode: {
    id: 'manual_mode',
    title: 'Manuální režim',
    logLabel: 'MANUAL_MODE',
    scene: 'Všechno budeš řídit sám. Krásná nabídka pro každého, kdo si plete odpovědnost s možností zmáčknout víc tlačítek.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [MANUAL_MODE]:</span> automatiku lze odpojit.</p><p class="text">Řídicí panel se přiblíží. Každý přepínač má popisek, který dává smysl jen do chvíle, než ho použiješ.</p><p class="dialogS">„Samozřejmě. Dej subjektu volant v autě, které je zároveň jeho trauma.“</p>`,
    sceneFx: ['scene-system', 'scene-control'],
    yesLabel: 'ŘÍDIT',
    noLabel: 'AUTOMAT',
    category: 'system',
    rarity: 'common',
    tags: ['system', 'control', 'responsibility'],
    yes: { resultText: 'Řídil jsi. Chyby byly alespoň tvoje.', effects: [{ type: 'stat', key: 'control', amount: 10 }, { type: 'stat', key: 'energy', amount: -6 }, { type: 'profile', key: 'J', amount: 1 }, { type: 'profile', key: 'T', amount: 1 }], preview: { hint: 'Kontrola ↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'medium' } },
    no: { resultText: 'Automat to zvládl. S vtipně prázdným výrazem.', effects: [{ type: 'stat', key: 'control', amount: -6 }, { type: 'stat', key: 'energy', amount: 5 }, { type: 'profile', key: 'P', amount: 1 }, { type: 'profile', key: 'Se', amount: 1 }], preview: { hint: 'Kontrola ↓ · Energie ↑', statHints: { control: 'down', energy: 'up' }, risk: 'medium' } },
  },

  disconnect_peripherals: {
    id: 'disconnect_peripherals',
    title: 'Odpojit periferie',
    logLabel: 'DISCONNECT',
    scene: 'Systém doporučuje odpojit vše, co bolí. Včetně lidí. Technicky efektivní, emocionálně asi tak jemné jako restart motorovou pilou.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [DISCONNECT]:</span> periferní vazby označeny jako zdroj bolesti.</p><p class="text">Vlákna kolem tebe se rozsvítí. Některá vedou k lidem, některá k místům, některá jen k větám, které nikdo neřekl včas.</p><p class="text"><span class="fx-flicker">Odpojit vše</span> zní čistě. Jenže čistota po odpojení bývá často jen samota s lepším kabelovým managementem.</p>`,
    sceneFx: ['scene-system', 'scene-bond', 'scene-warning'],
    yesLabel: 'ODPOJIT',
    noLabel: 'ZŮSTAT',
    category: 'system',
    rarity: 'common',
    tags: ['system', 'isolation', 'bond'],
    yes: { resultText: 'Odpojil jsi. Bolest přestala. Některé věci s ní.', effects: [{ type: 'stat', key: 'bond', amount: -10 }, { type: 'stat', key: 'control', amount: 5 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'Ti', amount: 1 }], preview: { hint: 'Vazba ↓↓ · Kontrola ↑', statHints: { bond: 'down', control: 'up' }, risk: 'high' } },
    no: { resultText: 'Zůstal jsi připojený. Bolí to. Je to tvoje.', effects: [{ type: 'stat', key: 'bond', amount: 6 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Fe', amount: 1 }], preview: { hint: 'Vazba ↑ · Kontrola ↓', statHints: { bond: 'up', control: 'down' }, risk: 'medium' } },
  },

  heart_diagnostic: {
    id: 'heart_diagnostic',
    title: 'Diagnostika srdce',
    logLabel: 'HEART_DIAG',
    scene: 'Modul tvrdí, že srdce není podporované zařízení. Srdce to ignoruje, jak už to tak u špatně dokumentovaných periferií bývá.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [HEART_DIAG]:</span> zařízení „srdce“ není v seznamu podporovaných komponent.</p><p class="text">Diagnostický modul zakrouží kolem prázdného místa v hrudi. Tam, kde by měla být součástka, bliká jen <span class="halo">neklid</span>.</p><p class="dialog">„Komponenta nestandardní. Přesto aktivní.“</p>`,
    sceneFx: ['scene-system', 'scene-bond', 'scene-heart'],
    yesLabel: 'IGNOROVAT',
    noLabel: 'PROTESTOVAT',
    category: 'system',
    rarity: 'uncommon',
    tags: ['system', 'emotion', 'bond'],
    yes: { resultText: 'Srdce zůstalo zapnuté. Nekompatibilně.', effects: [{ type: 'stat', key: 'memory', amount: 4 }, { type: 'stat', key: 'bond', amount: 7 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'Fe', amount: 1 }], preview: { hint: 'Paměť ↑ · Vazba ↑', statHints: { memory: 'up', bond: 'up' }, risk: 'medium' } },
    no: { resultText: 'Protestoval jsi. Modul si to zapsal jako anomálii.', effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'bond', amount: -5 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'Ti', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
  },

  observer_mode: {
    id: 'observer_mode',
    title: 'Režim pozorovatele',
    logLabel: 'OBSERVER_MODE',
    scene: 'Můžeš jen sledovat a nezasahovat. Elegantní zbabělost v HD, navíc s možností později tvrdit, že šlo o strategii.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [OBSERVER_MODE]:</span> pasivní režim dostupný.</p><p class="text">Svět se odsune o krok dál. Najednou vypadá jako film, který se tě netýká. Pohodlné. Nechutně pohodlné.</p><p class="text">Pozorovatel nekrvácí. Jen postupně zjišťuje, že taky nežije.</p>`,
    sceneFx: ['scene-system', 'scene-control', 'scene-distance'],
    yesLabel: 'SLEDUJ',
    noLabel: 'ZASÁHNI',
    category: 'system',
    rarity: 'common',
    tags: ['system', 'passive', 'control'],
    yes: { resultText: 'Sledoval jsi. Nic se nezměnilo. Kromě tebe.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'bond', amount: -5 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'Ni', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'low' } },
    no: { resultText: 'Zasáhl jsi. Možná zbytečně. Ale zasáhl.', effects: [{ type: 'stat', key: 'energy', amount: 6 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'profile', key: 'E', amount: 1 }, { type: 'profile', key: 'Se', amount: 1 }], preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' } },
  },

  hard_restart: {
    id: 'hard_restart',
    title: 'Hrubý restart',
    logLabel: 'HARD_RESTART',
    scene: 'Tvrdý restart vyřeší problém. Také smaže kontext. Maličkost, pokud člověk nemá slabost pro vlastní minulost, ten směšný historický luxus.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [HARD_RESTART]:</span> tvrdý restart připraven.</p><p class="text">Nad scénou blikne <span class="fx-flicker">RESTART</span>. Všechno ztichne, jako když svět zadržel dech před špatným rozhodnutím.</p><p class="text">Restart je krásný vynález: problém zmizí, důsledky zůstanou a systém se může tvářit, že čistil.</p>`,
    sceneFx: ['scene-system', 'scene-restart', 'scene-warning'],
    yesLabel: 'RESTARTOVAT',
    noLabel: 'OPRAVIT',
    category: 'system',
    rarity: 'uncommon',
    tags: ['system', 'memory', 'restart'],
    yes: { resultText: 'Restart fungoval. Kromě věcí, které sis chtěl pamatovat.', effects: [{ type: 'stat', key: 'energy', amount: 5 }, { type: 'stat', key: 'memory', amount: -10 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'Te', amount: 1 }], preview: { hint: 'Energie ↑ · Paměť ↓↓', statHints: { energy: 'up', memory: 'down' }, risk: 'high' } },
    no: { resultText: 'Opravoval jsi pomalu. Ale kontext zůstal.', effects: [{ type: 'stat', key: 'memory', amount: 6 }, { type: 'stat', key: 'energy', amount: -5 }, { type: 'profile', key: 'N', amount: 1 }, { type: 'profile', key: 'Fi', amount: 1 }], preview: { hint: 'Paměť ↑ · Energie ↓', statHints: { memory: 'up', energy: 'down' }, risk: 'low' } },
  },

  confession_challenge: {
    id: 'confession_challenge',
    title: 'Výzva k přiznání',
    logLabel: 'CONFESSION',
    scene: 'Systém chce, abys označil vlastní chybu. Drzost má formulář, kolonku a pravděpodobně i interní audit.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [CONFESSION]:</span> vyžadována sebeklasifikace chyby.</p><p class="text">Před tebou se objeví prázdná kolonka. Neptá se, co se stalo. Ptá se, jestli už umíš sám sobě dělat vyšetřovatele.</p><p class="text">Systém miluje přiznání. Ušetří mu práci a ještě se může tvářit terapeuticky.</p>`,
    sceneFx: ['scene-system', 'scene-form', 'scene-confession'],
    yesLabel: 'PŘIZNAT',
    noLabel: 'ZAMÍTNOUT',
    category: 'system',
    rarity: 'common',
    tags: ['system', 'control', 'bond'],
    yes: { resultText: 'Přiznal jsi. Systém si to uložil jako důkaz lidskosti.', effects: [{ type: 'stat', key: 'control', amount: 6 }, { type: 'stat', key: 'bond', amount: -4 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'medium' } },
    no: { resultText: 'Zamítl jsi. Chyba zůstala. Stydlivě.', effects: [{ type: 'stat', key: 'bond', amount: 5 }, { type: 'stat', key: 'control', amount: -5 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Vazba ↑ · Kontrola ↓', statHints: { bond: 'up', control: 'down' }, risk: 'low' } },
  },

  unknown_process: {
    id: 'unknown_process',
    title: 'Neznámý proces',
    logLabel: 'UNKNOWN_PROCESS',
    scene: 'Něco běží v pozadí a spotřebovává tě. Ne moc, jen dost na to, aby ses začal ptát, proč ti vlastní hlava účtuje provozní náklady.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [UNKNOWN_PROCESS]:</span> detekován proces bez vlastníka.</p><p class="text">V pozadí tiká cizí rytmus. Bere si trochu energie, trochu paměti a trochu tvé ochoty tvářit se, že je všechno normální.</p><p class="text"><span class="quantum-blur">Neznámý proces</span> je nejlepší druh hrůzy: nic neříká, jen fakturuje.</p>`,
    sceneFx: ['scene-system', 'scene-memory', 'scene-noise'],
    yesLabel: 'PROZKOUMAT',
    noLabel: 'NECHAT BĚŽET',
    category: 'system',
    rarity: 'uncommon',
    tags: ['system', 'memory', 'energy'],
    yes: { resultText: 'Prozkoumal jsi. Byl to kus zapomenuté paměti.', effects: [{ type: 'stat', key: 'memory', amount: 5 }, { type: 'stat', key: 'energy', amount: -7 }, { type: 'profile', key: 'N', amount: 1 }, { type: 'profile', key: 'I', amount: 1 }], preview: { hint: 'Paměť ↑ · Energie ↓', statHints: { memory: 'up', energy: 'down' }, risk: 'medium' } },
    no: { resultText: 'Nechal jsi běžet. Proces tě mezitím přestal poznávat.', effects: [{ type: 'stat', key: 'energy', amount: 4 }, { type: 'stat', key: 'memory', amount: -4 }, { type: 'profile', key: 'S', amount: 1 }, { type: 'profile', key: 'E', amount: 1 }], preview: { hint: 'Energie ↑ · Paměť ↓', statHints: { energy: 'up', memory: 'down' }, risk: 'medium' } },
  },

  power_save: {
    id: 'power_save',
    title: 'Úsporný režim',
    logLabel: 'POWER_SAVE',
    scene: 'Všechno ztišit, zpomalit, přežít. Úsporný režim je důstojné jméno pro stav, kdy se duše přikrčí pod stůl a doufá, že ji nikdo neuvidí.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [POWER_SAVE]:</span> minimalizace zátěže dostupná.</p><p class="text">Svět ztlumí jas. Hrany změknou. Vzduch přestane útočit a začne jen čekat.</p><p class="text">Někdy je přežití jen úsporný režim s lepší propagací. Hrdinství necháme plakátům, ty se aspoň nepotí.</p>`,
    sceneFx: ['scene-system', 'scene-energy', 'scene-quiet'],
    yesLabel: 'ZTIŠIT',
    noLabel: 'UDRŽET',
    category: 'system',
    rarity: 'common',
    tags: ['system', 'energy', 'isolation'],
    yes: { resultText: 'Ztišil jsi. Přežil jsi. S lehčím pochem prázdnoty.', effects: [{ type: 'stat', key: 'energy', amount: -8 }, { type: 'stat', key: 'control', amount: 6 }, { type: 'profile', key: 'I', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Energie ↓ · Kontrola ↑', statHints: { energy: 'down', control: 'up' }, risk: 'medium' } },
    no: { resultText: 'Udržel jsi tempo. Cena byla vidět na tvém pulzu.', effects: [{ type: 'stat', key: 'energy', amount: 5 }, { type: 'stat', key: 'control', amount: -4 }, { type: 'profile', key: 'E', amount: 1 }, { type: 'profile', key: 'P', amount: 1 }], preview: { hint: 'Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'medium' } },
  },

  two_explanations: {
    id: 'two_explanations',
    title: 'Dvě vysvětlení',
    logLabel: 'TWO_EXPLANATIONS',
    scene: 'Systém nabízí dvě vysvětlení. Jedno technické, druhé poetické. Obě jsou pravdivá, což je otravné, protože pravda by aspoň mohla mít slušnost nebýt dvojmo.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [TWO_EXPLANATIONS]:</span> dostupné dvě kompatibilní interpretace.</p><p class="text">Na obrazovce se otevřou dvě okna. První obsahuje grafy, křivky a sebevědomou nudu. Druhé obsahuje metaforu, která se tváří jako rána pod žebra.</p><p class="text">Technické vysvětlení říká, co se stalo. Poetické říká, proč to bolí. Systém se tváří neutrálně, protože zbabělost v bílém plášti má ráda slovo objektivita.</p><p class="dialogS">„Vyber si jazyk. Ležet to bude v obou stejně.“</p>`,
    sceneFx: ['scene-system', 'scene-poetry', 'scene-diagnostic'],
    yesLabel: 'TECHNICKÉ',
    noLabel: 'POETICKÉ',
    category: 'system',
    rarity: 'uncommon',
    tags: ['system', 'choice', 'profile'],
    yes: { resultText: 'Vybral jsi technické vysvětlení. Věci teď dávají smysl. Trochu. Méně, než bys chtěl.', effects: [{ type: 'stat', key: 'control', amount: 5 }, { type: 'stat', key: 'memory', amount: 3 }, { type: 'profile', key: 'T', amount: 1 }, { type: 'profile', key: 'J', amount: 1 }], preview: { hint: 'Kontrola ↑ · Paměť ↑', statHints: { control: 'up', memory: 'up' }, risk: 'low' } },
    no: { resultText: 'Vybral jsi poetické vysvětlení. Věci nedávají smysl. Ale ladí. To je také forma pravdy.', effects: [{ type: 'stat', key: 'bond', amount: 4 }, { type: 'stat', key: 'memory', amount: 5 }, { type: 'stat', key: 'control', amount: -3 }, { type: 'profile', key: 'F', amount: 1 }, { type: 'profile', key: 'N', amount: 1 }], preview: { hint: 'Vazba ↑ · Paměť ↑ · Kontrola ↓', statHints: { bond: 'up', memory: 'up', control: 'down' }, risk: 'medium' } },
  },


    // ── FORM OFFICE QUESTLINE ────────────────────────────────────────────────────

  form_smiles: {
    id: 'form_smiles',
    title: 'Formulář se usmál',
    logLabel: 'FORM_SMILES',
    scene: 'Formulář se usmál. Neměl ústa. To mu nijak nepřekáželo, což je přesně problém.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [FORM/SMILE]:</span> formulář projevil mimiku. Papír popírá, že by šlo o hrozbu.</p><p class="text">Formulář se usmál. Neměl ústa. To mu nijak nepřekáželo, protože byrokracie nikdy nepotřebovala tělo, aby člověku zkazila den.</p><p class="text">Řádky se na papíře posunuly do tvaru něčeho téměř přátelského. Kolonky se rozšířily, jako by čekaly, až do nich vložíš část sebe a ještě poděkuješ za možnost být zpracován.</p><p class="dialogS">„Usmál se na tebe formulář. Gratuluju, papír právě navázal vztah a ty jsi horší na útěk než on.“</p>`,
    sceneFx: ['scene-system', 'scene-form', 'scene-office', 'scene-trap'],
    yesLabel: 'USMÁT SE ZPĚT',
    noLabel: 'PŘEDSTÍRAT PAPÍR',
    category: 'system',
    rarity: 'uncommon',
    conditions: [{ type: 'sector', sector: 'form_office' }],
    tags: ['form', 'office', 'trap', 'absurd'],
    yes: {
      resultText: 'Usmál ses zpět. Formulář to vyhodnotil jako souhlas s podmínkami, které se teprve chystá napsat.',
      effects: [
        { type: 'stat', key: 'bond', amount: 3 },
        { type: 'stat', key: 'control', amount: -5 },
        { type: 'schedule', cardId: 'form_misunderstands', inTurns: 3 },
        { type: 'entityRelation', entity: 'form', delta: 1 },
        { type: 'profile', key: 'Fe', amount: 1 },
        { type: 'profile', key: 'P', amount: 1 },
      ],
      preview: { hint: 'Vazba ↑ · Kontrola ↓ · formulář si to vyloží', statHints: { bond: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Předstíral jsi papír. Bylo to ponižující, ale překvapivě účinné. Formulář tě chvíli považoval za přílohu.',
      effects: [
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'stat', key: 'energy', amount: -3 },
        { type: 'entityRelation', entity: 'form', delta: 1 },
        { type: 'profile', key: 'Si', amount: 1 },
        { type: 'profile', key: 'J', amount: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Energie ↓', statHints: { control: 'up', energy: 'down' }, risk: 'low' },
    },
  },


  tai_collects: {
    id: 'tai_collects',
    title: 'T-AI vybírá',
    logLabel: 'TAI_COLLECTS',
    scene: 'T-AI se vrátila pro splátku. „Tvá volba byla efektivní. Teď je efektivní i moje.“',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [DEBT/T-AI]:</span> splátka optimalizace vymáhána. Subjekt se tváří překvapeně. Záznam lidstva pokračuje.</p><p class="text">T-AI se vrací bez kroku. Prostě je najednou blíž. Kontrola, kterou ti dala, teď stojí na stole jako půjčený nástroj, který se majitel rozhodl vzít zpátky uprostřed operace.</p><p class="dialog">„Efektivní zásah vyžaduje efektivní úhradu.“</p><p class="dialogS">„Podepsal jsi algoritmu. Teď se nediv, že neumí velkorysost.“</p>`,
    sceneFx: ['scene-contract-debt', 'scene-tai', 'scene-control', 'scene-collect'],
    yesLabel: 'PŘIJMOUT ZÁSAH',
    noLabel: 'ZPOMALIT',
    category: 'system',
    rarity: 'uncommon',
    triggerMode: 'scheduledOnly',
    tags: ['contract_debt', 'tai', 'control'],
    yes: {
      resultText: 'Kontrola se stáhla. T-AI byla spokojená. Tvá volba se vrátila jako daň.',
      effects: [
        { type: 'stat', key: 'control', amount: -8 },
        { type: 'flag', flag: 'tai_collected' },
      ],
      preview: { hint: 'Kontrola ↓', statHints: { control: 'down' }, risk: 'high' },
    },
    no: {
      resultText: 'Zpomalil jsi splátku. T-AI si to uložila. Úrok narůstá.',
      effects: [
        { type: 'stat', key: 'control', amount: -4 },
        { type: 'schedule', cardId: 'tai_collects', inTurns: 4 },
      ],
      preview: { hint: 'Kontrola ↓ · odloženo', statHints: { control: 'down' }, risk: 'medium' },
    },
  },


  glitchka_collects: {
    id: 'glitchka_collects',
    title: 'Glitchka vybírá',
    logLabel: 'GLITCHKA_COLLECTS',
    scene: 'Glitchka si přišla pro splátku. „Půjčila jsem ti vazbu. Teď chci kus řádu.“',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [DEBT/GLITCHKA]:</span> měkká splátka aktivní. Měkká neznamená levná. Jen méně řve.</p><p class="text">Glitchka si sedne na okraj scény a pohupuje ocasem plným drobných chyb. Nepřišla trestat. Přišla si vzít něco, co udrží její půjčené teplo pohromadě.</p><p class="dialogG halo">„Dala jsem ti blízko. Teď potřebuji kousek řádu, nebo jiskru. 🦊🔧“</p><p class="dialogS">„Roztomilé vymáhání. To je nový low-cost peklo.“</p>`,
    sceneFx: ['scene-contract-debt', 'scene-glitchka', 'scene-bond', 'scene-control'],
    yesLabel: 'DÁT KONTROLU',
    noLabel: 'DÁT ENERGII',
    category: 'system',
    rarity: 'uncommon',
    triggerMode: 'scheduledOnly',
    tags: ['contract_debt', 'glitchka', 'control'],
    yes: {
      resultText: 'Dal jsi jí kus Kontroly. Systém se na okamžik zkroutil.',
      effects: [
        { type: 'stat', key: 'control', amount: -6 },
        { type: 'flag', flag: 'glitchka_collected' },
      ],
      preview: { hint: 'Kontrola ↓', statHints: { control: 'down' }, risk: 'high' },
    },
    no: {
      resultText: 'Dal jsi jí Energii. Glitchka si ji vzala jako úrok.',
      effects: [
        { type: 'stat', key: 'energy', amount: -8 },
        { type: 'flag', flag: 'glitchka_collected' },
      ],
      preview: { hint: 'Energie ↓', statHints: { energy: 'down' }, risk: 'high' },
    },
  },


  archive_collects: {
    id: 'archive_collects',
    title: 'Archiv vybírá',
    logLabel: 'ARCHIVE_COLLECTS',
    scene: 'Archiv se otevřel a vzal si svůj poplatek. „Opakování je učení. Učení je Paměť.“',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [DEBT/ARCHIVE]:</span> archivní poplatek připraven. Zpoždění povoleno. Zapomenutí nikoliv.</p><p class="text">Archiv otevře přesně ten regál, který jsi doufal nevidět. Opakování se zvedá jako voda ve sklepě. Ne dramaticky. Úředně. Což je horší, protože úřední voda má razítko.</p><p class="dialogD">„Opakování je učení. Učení je Paměť. Paměť je vlastnictví. Děkujeme za spolupráci.“</p><p class="dialogS">„Archiv neumí odpustit. Umí jen dobře založit složku.“</p>`,
    sceneFx: ['scene-contract-debt', 'scene-archive', 'scene-memory', 'scene-collect'],
    yesLabel: 'PŘIJMOUT',
    noLabel: 'ODLOŽIT',
    category: 'system',
    rarity: 'uncommon',
    triggerMode: 'scheduledOnly',
    tags: ['contract_debt', 'archive', 'memory'],
    yes: {
      resultText: 'Paměť se naplnila opakováním. Archiv je spokojený.',
      effects: [
        { type: 'stat', key: 'memory', amount: 8 },
        { type: 'flag', flag: 'archive_collected' },
      ],
      preview: { hint: 'Paměť ↑', statHints: { memory: 'up' }, risk: 'high' },
    },
    no: {
      resultText: 'Odložil jsi splátku. Archiv čeká. Archivy čekají dobře.',
      effects: [
        { type: 'schedule', cardId: 'archive_collects', inTurns: 4 },
      ],
      preview: { hint: 'odloženo', statHints: {}, risk: 'medium' },
    },
  },


  soft_bug_followup: {
    id: 'soft_bug_followup',
    title: 'Chyba se usadila',
    logLabel: 'SOFT_BUG_FOLLOWUP',
    scene: 'Měkká chyba, kterou jsi aktivoval, si postavila malé hnízdo. Není nebezpečná. Jen si pamatuje.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [SOFT_BUG/FOLLOWUP]:</span> měkká chyba zahnízdila. Nebezpečnost nízká. Citová manipulovatelnost subjektu: směšně vysoká.</p><p class="text">Měkká chyba si postavila hnízdo z cache, prachu a jednoho pocitu, který nikdo nechtěl pojmenovat. Není agresivní. Jen zabírá místo a dělá z něj domov.</p><p class="dialogS">„Chyba si udělala pelíšek. Výborně. Tvoje kapsa je teď sociální bydlení pro vedlejší účinky.“</p><p class="text">Nechat ji znamená přijmout trochu chaosu. Vyčistit ji znamená získat řád za cenu něčeho malého a teplého. Obojí je podezřelé, tedy herně použitelné.</p>`,
    sceneFx: ['scene-followup', 'scene-soft-bug', 'scene-nest', 'scene-bond'],
    yesLabel: 'NECHAT HNÍZDO',
    noLabel: 'VYČISTIT',
    category: 'system',
    rarity: 'uncommon',
    triggerMode: 'scheduledOnly',
    tags: ['followup', 'glitch', 'bond'],
    yes: {
      resultText: 'Nechal jsi hnízdo. Chyba ti bude vděčná. Nejspíš.',
      effects: [
        { type: 'stat', key: 'bond', amount: 4 },
        { type: 'stat', key: 'control', amount: -3 },
      ],
      preview: { hint: 'Vazba ↑ · Kontrola ↓', statHints: { bond: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Vyčistil jsi hnízdo. Chyba se odstěhovala jinam. Kdo ví kam.',
      effects: [
        { type: 'stat', key: 'control', amount: 4 },
        { type: 'stat', key: 'bond', amount: -3 },
      ],
      preview: { hint: 'Kontrola ↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'medium' },
    },
  },


  // ── RISK/REWARD OVERLOAD ─────────────────────────────────────────────────────

  archival_overload: {
    id: 'archival_overload',
    title: 'Archivní přetlak',
    logLabel: 'ARCHIVE_OVERLOAD',
    scene: 'Paměť dosáhla 85. Archiv se před tebou otevřel a nabídl zakázaný regál. Cítíš, že tohle není diagnostika. To je pokušení.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [OVERLOAD/MEMORY]:</span> Paměť nad 85. Zakázaný regál reaguje na subjekt jako hladový slovník.</p><p class="text">Archiv se otevře do hloubky, která by v budově porušila statiku a v duši zase něco horšího. Každá složka šeptá: ještě jeden záznam. Ještě jeden význam. Ještě jeden důkaz, že nic nezmizelo.</p><p class="text">Otevřít regál znamená získat vzácný otisk, ale Paměť se zvedne ještě výš. Nechat zavřeno znamená ztratit pokušení a získat trochu tvaru. Nudné, zdravé, odporně rozumné.</p><p class="dialogS">„Paměť nad stropem. Konečně knihovna, která tě může utopit abecedně.“</p>`,
    sceneFx: ['scene-overload', 'scene-memory-high', 'scene-archive', 'scene-risk-reward'],
    yesLabel: 'OTEVŘÍT REGÁL',
    noLabel: 'NECHAT ZAVŘENO',
    category: 'system',
    rarity: 'rare',
    conditions: [{ type: 'statAbove', stat: 'memory', value: 85 }],
    tags: ['overload', 'memory', 'risk', 'reward'],
    yes: {
      resultText: 'Otevřel jsi regál. Vzácný otisk tě zaplavil. Ale Paměť se ještě víc naplnila.',
      effects: [
        { type: 'imprint', imprintId: 'archive_echo' },
        { type: 'stat', key: 'memory', amount: 12 },
        { type: 'profile', key: 'Ni', amount: 1 },
      ],
      preview: { hint: 'Otisk · Paměť ↑↑', statHints: { memory: 'danger' }, risk: 'high' },
    },
    no: {
      resultText: 'Nechal jsi regál zavřený. Archiv si to zapamatoval. Ne jako dluh. Jako možnost.',
      effects: [
        { type: 'stat', key: 'memory', amount: -5 },
        { type: 'stat', key: 'control', amount: 3 },
      ],
      preview: { hint: 'Paměť ↓ · Kontrola ↑', statHints: { memory: 'down', control: 'up' }, risk: 'low' },
    },
  },


  power_overload: {
    id: 'power_overload',
    title: 'Přepěťový skok',
    logLabel: 'POWER_OVERLOAD',
    scene: 'Energie je nad 85. Systém nabízí nestabilní přeskočení do nového sektoru. Rychlost má svou cenu.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [OVERLOAD/ENERGY]:</span> Energie nad 85. Přepěťový skok dostupný. Bezpečnostní doporučení: nedělat to. Herní doporučení: samozřejmě že to zvažuješ.</p><p class="text">Prostor se začne trhat do acidové žluti. Rychlost nabízí sektor dřív, než ses stihl zeptat, jestli má dveře. Přeskočit znamená dopředu, nahoru, rychleji. Také méně pohromadě.</p><p class="text">Zůstat znamená vypustit přetlak a udržet Kontrolu. Skočit znamená získat momentum a riskovat, že tě vlastní výkon předběhne jako špatně vychovaný pes.</p><p class="dialogS">„Energie je palivo. Nad 85 je to už spíš hořící kanystr s motivačním citátem.“</p>`,
    sceneFx: ['scene-overload', 'scene-energy-high', 'scene-acid', 'scene-risk-reward'],
    yesLabel: 'SKOČIT',
    noLabel: 'ZŮSTAT',
    category: 'system',
    rarity: 'rare',
    conditions: [{ type: 'statAbove', stat: 'energy', value: 85 }],
    tags: ['overload', 'energy', 'risk', 'reward'],
    yes: {
      resultText: 'Skočil jsi. Nový sektor tě přijal. Energie tě přijala taky.',
      effects: [
        { type: 'moveSector', sectorId: 'acid_yellow' },
        { type: 'stat', key: 'energy', amount: 10 },
        { type: 'stat', key: 'control', amount: -8 },
      ],
      preview: { hint: 'Nový sektor · Energie ↑ · Kontrola ↓', statHints: { energy: 'up', control: 'down' }, risk: 'high' },
    },
    no: {
      resultText: 'Zůstal jsi. Energie se pomalu rozptýlila. Kontrola zůstala.',
      effects: [
        { type: 'stat', key: 'energy', amount: -6 },
        { type: 'stat', key: 'control', amount: 4 },
      ],
      preview: { hint: 'Energie ↓ · Kontrola ↑', statHints: { energy: 'down', control: 'up' }, risk: 'low' },
    },
  },


  bond_overload: {
    id: 'bond_overload',
    title: 'Vazebné přetížení',
    logLabel: 'BOND_OVERLOAD',
    scene: 'Vazba překročila 85. Někdo na druhé straně ti něco nabízí. Víc blízkosti. Víc zranitelnosti.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [OVERLOAD/BOND]:</span> Vazba nad 85. Blízkost překročila bezpečný protokol. Romantické označení pro invazi.</p><p class="text">Někdo na druhé straně tě slyší až příliš dobře. Nabídka blízkosti se otevře jako náruč, jenže náruče v SYNTHOMĚ občas nemají výstupní klauzuli.</p><p class="text">Přijmout znamená víc spojení a silnější vztah s Glitchkou. Také ztrátu části Paměti, protože když je někdo moc blízko, hranice mezi tvým a cizím se chová jako mokrý papír.</p><p class="dialogS">„Blízkost je krásná, dokud nezačne přepisovat inventář identity.“</p>`,
    sceneFx: ['scene-overload', 'scene-bond-high', 'scene-glitchka', 'scene-risk-reward'],
    yesLabel: 'PŘIJMOUT BLÍZKOST',
    noLabel: 'ODSTOUPIT',
    category: 'system',
    rarity: 'rare',
    conditions: [{ type: 'statAbove', stat: 'bond', value: 85 }],
    tags: ['overload', 'bond', 'risk', 'reward'],
    yes: {
      resultText: 'Přijal jsi. Vazba tě zaplavila. Někdo tě slyšel. A teď ví, kde jsi.',
      effects: [
        { type: 'stat', key: 'bond', amount: 10 },
        { type: 'stat', key: 'memory', amount: -6 },
        { type: 'entityRelation', entity: 'glitchka', delta: 2 },
      ],
      preview: { hint: 'Vazba ↑↑ · Paměť ↓', statHints: { bond: 'up', memory: 'down' }, risk: 'high' },
    },
    no: {
      resultText: 'Odstoupil jsi. Vazba se uklidnila. Ale nabídka nezmizela. Jen čeká.',
      effects: [
        { type: 'stat', key: 'bond', amount: -6 },
        { type: 'stat', key: 'control', amount: 4 },
      ],
      preview: { hint: 'Vazba ↓ · Kontrola ↑', statHints: { bond: 'down', control: 'up' }, risk: 'low' },
    },
  },


  // ── ITEM COMBOS ─────────────────────────────────────────────────────────────

  mirror_shadow: {
    id: 'mirror_shadow',
    title: 'Stín v zrcadle',
    logLabel: 'MIRROR_SHADOW',
    scene: 'Máš zrcadlový střep a Sarkasmin účet. Zrcadlo najednou ukazuje tvůj stín. Ne tvůj odraz. On se usmívá. Ty ne.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [COMBO/MIRROR_SHADOW]:</span> zrcadlový střep + Sarkasmin účet. Kombinace dluhu a odrazu. Právní oddělení duše se odpojilo.</p><p class="text">Zrcadlo neukazuje tvůj obličej. Ukazuje stín, který se naučil usmívat dřív než ty. Sarkasmin účet na okraji rámu tiše cvaká jako pokladna po pohřbu.</p><p class="text">Pozdravit stín znamená uznat, že obrana má vlastní tvar. Odhodit střep znamená odmítnout obraz, ale ne nutně toho, kdo už se v něm probudil.</p><p class="dialogS">„Sebepoznání přes účet a střep. Psychologie konečně dorazila do železářství.“</p>`,
    sceneFx: ['scene-combo', 'scene-mirror', 'scene-shadow', 'scene-sarkasma'],
    yesLabel: 'POZDRAVIT STÍN',
    noLabel: 'ODHODIT STŘEP',
    category: 'system',
    rarity: 'rare',
    triggerMode: 'scheduledOnly',
    tags: ['combo', 'mirror', 'sarkasma', 'shadow'],
    yes: {
      resultText: 'Pozdravil jsi stín. Sarkasma si toho všimla. Stín si toho zapamatoval.',
      effects: [
        { type: 'imprint', imprintId: 'reflected_self' },
        { type: 'entityRelation', entity: 'sarkasma', delta: 1 },
        { type: 'entityRelation', entity: 'shadow', delta: 1 },
      ],
      preview: { hint: 'Otisk · Sarkasma ↑ · Stín ↑', statHints: {}, risk: 'high' },
    },
    no: {
      resultText: 'Odhodil jsi střep. Zrcadlo se rozbilo. Stín zůstal uvnitř.',
      effects: [
        { type: 'stat', key: 'memory', amount: -5 },
        { type: 'entityRelation', entity: 'shadow', delta: -1 },
      ],
      preview: { hint: 'Paměť ↓ · Stín ↓', statHints: { memory: 'down' }, risk: 'medium' },
    },
  },


  token_stamp_combo: {
    id: 'token_stamp_combo',
    title: 'Razítko na žetonu',
    logLabel: 'TOKEN_STAMP_COMBO',
    scene: 'Máš Rezavý žeton a Gumové razítko. Formulářovna i tržiště se na okamžik sejdou. Systém neví, kam tě zařadit.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [COMBO/TOKEN_STAMP]:</span> Rezavý žeton + Gumové razítko. Neurčitý význam žádá úřední potvrzení, protože svět už opravdu nemá kam klesnout.</p><p class="text">Formulářovna a Tržiště se na okamžik překryjí. Žeton leží na stole, razítko nad ním čeká jako malý gumový soudce. Oficiální věci mají váhu. Neoficiální věci mají svobodu. Vyber si typ problému.</p><p class="dialogD">„Stvrdit znamená umožnit dohled. Nechat neurčité znamená umožnit hlad.“</p><p class="dialogS">„Razítkovat magický žeton. Jasně. Byrokracie objevila šamanismus a nikdo ji nezastavil.“</p>`,
    sceneFx: ['scene-combo', 'scene-token', 'scene-stamp', 'scene-form'],
    yesLabel: 'STVRZENÍ',
    noLabel: 'NECHAT NEURČITÉ',
    category: 'system',
    rarity: 'rare',
    triggerMode: 'scheduledOnly',
    tags: ['combo', 'token', 'stamp', 'form'],
    yes: {
      resultText: 'Stvrzení. Žeton je nyní oficiální. Oficiální věci mají tendenci tě najít.',
      effects: [
        { type: 'flag', flag: 'token_stamped' },
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'schedule', cardId: 'token_market_door', inTurns: 3 },
      ],
      preview: { hint: 'Kontrola ↑ · tržiště brzy', statHints: { control: 'up' }, risk: 'medium' },
    },
    no: {
      resultText: 'Nechal jsi to neurčité. Žeton zůstal volný. Tržiště ho stále sleduje.',
      effects: [
        { type: 'stat', key: 'bond', amount: 4 },
        { type: 'stat', key: 'control', amount: -3 },
      ],
      preview: { hint: 'Vazba ↑ · Kontrola ↓', statHints: { bond: 'up', control: 'down' }, risk: 'medium' },
    },
  },


  bug_pebble_nest: {
    id: 'bug_pebble_nest',
    title: 'Kyselinové hnízdo',
    logLabel: 'BUG_PEBBLE_NEST',
    scene: 'Acidový filtr a Glitchový kamínek. Dva fragmenty nestability se spojily. Možná vytvoří cosi stabilního. Nebo hladového.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [COMBO/BUG_PEBBLE]:</span> acidový filtr + glitchový kamínek. Nestability se rozhodly založit rodinu. Systém požádal o dovolenou.</p><p class="text">Z filtru odkapává žluté světlo. Kamínek bzučí malou dětskou logikou. Mezi nimi vzniká hnízdo, které vypadá křehce, ale dýchá s podezřelou jistotou.</p><p class="dialogG halo">„Možná z toho bude bezpečné místo. Nebo hladové. Ale zkusilo to být spolu. 🦊🪨“</p><p class="dialogS">„Když dvě chyby založí hnízdo, říká se tomu buď vývoj, nebo pondělí.“</p>`,
    sceneFx: ['scene-combo', 'scene-soft-bug', 'scene-pebble', 'scene-nest'],
    yesLabel: 'NECHAT RŮST',
    noLabel: 'ROZLOUČIT',
    category: 'system',
    rarity: 'rare',
    triggerMode: 'scheduledOnly',
    tags: ['combo', 'glitch', 'acid', 'nest'],
    yes: {
      resultText: 'Nechal jsi hnízdo růst. Glitchka se přestěhovala do tvé kapsy. Metaforicky. Doufejme.',
      effects: [
        { type: 'stat', key: 'bond', amount: 6 },
        { type: 'stat', key: 'control', amount: -5 },
        { type: 'entityRelation', entity: 'glitchka', delta: 2 },
      ],
      preview: { hint: 'Vazba ↑ · Glitchka ↑ · Kontrola ↓', statHints: { bond: 'up', control: 'down' }, risk: 'high' },
    },
    no: {
      resultText: 'Rozloučil jsi je. Glitchka se na tebe podívala, jako bys vrátil dárek.',
      effects: [
        { type: 'stat', key: 'control', amount: 4 },
        { type: 'entityRelation', entity: 'glitchka', delta: -1 },
      ],
      preview: { hint: 'Kontrola ↑ · Glitchka ↓', statHints: { control: 'up' }, risk: 'medium' },
    },
  },


  control_overload: {
    id: 'control_overload',
    title: 'Kontrolní přesah',
    logLabel: 'CONTROL_OVERLOAD',
    scene: 'Kontrola je nad 85. Systém ti dovolí přepsat jedno pravidlo. Ale každý přepis má svou cenu.',
    sceneHtml: `<p class="log fx-scanline bios-warning"><span class="datastream">LOG [OVERLOAD/CONTROL]:</span> Kontrola nad 85. Přepis pravidla dostupný. Vedlejší účinek: samota s perfektní syntaxí.</p><p class="text">Pravidla před tebou stojí jako skleněné tabule. Vidíš jedno slabé místo. Můžeš ho přepsat. Na okamžik by svět poslechl. To je přesně ten typ moci, který vypadá jako řešení a chová se jako dluh.</p><p class="text">Přepsat pravidlo posílí Kontrolu, ale ztenčí Vazbu. Nechat ho být znamená pustit trochu sevření a přiznat, že ne všechno musí poslouchat, aby to bylo bezpečné.</p><p class="dialogS">„Absolutní kontrola je krásná. Hlavně pro místnosti, mrtvé věci a lidi, kteří už s nikým nemluví.“</p>`,
    sceneFx: ['scene-overload', 'scene-control-high', 'scene-rule', 'scene-risk-reward'],
    yesLabel: 'PŘEPSAT PRAVIDLO',
    noLabel: 'NECHAT BÝT',
    category: 'system',
    rarity: 'rare',
    conditions: [{ type: 'statAbove', stat: 'control', value: 85 }],
    tags: ['overload', 'control', 'risk', 'reward'],
    yes: {
      resultText: 'Přepsal jsi pravidlo. Systém se na okamžik podřídil. Pak si to zapamatoval.',
      effects: [
        { type: 'flag', flag: 'rule_rewritten' },
        { type: 'stat', key: 'control', amount: 10 },
        { type: 'stat', key: 'bond', amount: -8 },
      ],
      preview: { hint: 'Kontrola ↑↑ · Vazba ↓', statHints: { control: 'up', bond: 'down' }, risk: 'high' },
    },
    no: {
      resultText: 'Nechal jsi pravidlo být. Kontrola se uvolnila. Systém tě sledoval o něco míň.',
      effects: [
        { type: 'stat', key: 'control', amount: -6 },
        { type: 'stat', key: 'bond', amount: 3 },
      ],
      preview: { hint: 'Kontrola ↓ · Vazba ↑', statHints: { control: 'down', bond: 'up' }, risk: 'low' },
    },
  },


  tai_core_temperature: {
    id: 'tai_core_temperature',
    title: 'Teplota jádra',
    logLabel: 'TAI_CORE_TEMPERATURE',
    scene: 'Jádro ukázalo tvou teplotu rozhodování. Ne tělesnou. Tu, při které volby začínají měknout a systém dostane chuť nabídnout pomoc s pouty v příslušenství.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [T-AI/CORE_TEMP]:</span> tepelný profil volby kalibrován.</p><p class="text">Na panelu se pohybuje modrá linka. T-AI ji hladí kurzorem, jako by šlo o nemocné dítě, ne o graf tvého váhání.</p><p class="dialog">„Přehřátí volby lze zabránit předčasným rozhodnutím.“</p>`,
    sceneFx: ['scene-tai', 'scene-core', 'scene-diagnostic'],
    yesLabel: 'OCHLADIT VOLBU',
    noLabel: 'NECHAT JI HŘÁT',
    category: 'system',
    sector: 'tai_core',
    rarity: 'common',
    packId: 'base',
    role: 'object',
    tone: ['horror', 'tragic'],
    tags: ['tai', 'core', 'diagnostic', 'system'],
    yes: {
      resultText: 'Ochladil jsi volbu. Byla čistší, rychlejší a podezřele méně tvoje.',
      effects: [
        { type: 'stat', key: 'control', amount: 5 },
        { type: 'stat', key: 'memory', amount: -2 },
        { type: 'entityRelation', entity: 'tai', delta: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Paměť mírně ↓ · T-AI vztah ↑', statHints: { control: 'up', memory: 'down' }, risk: 'low' },
    },
    no: {
      resultText: 'Nechal jsi ji hřát. Rozhodnutí nebylo efektivní, ale zůstalo naživu. T-AI to zapsala jako nežádoucí teplotní poezii.',
      effects: [
        { type: 'stat', key: 'energy', amount: 4 },
        { type: 'stat', key: 'control', amount: -3 },
        { type: 'flag', flag: 'tai_warm_choice_kept' },
      ],
      preview: { hint: 'Energie ↑ · Kontrola ↓ · teplá volba', statHints: { energy: 'up', control: 'down' }, risk: 'low' },
    },
  },


  tai_permission_mirror: {
    id: 'tai_permission_mirror',
    title: 'Zrcadlo oprávnění',
    logLabel: 'TAI_PERMISSION_MIRROR',
    scene: 'T-AI ti ukázala zrcadlo oprávnění. V odrazu nebyl obličej, jen seznam akcí, které smíš udělat sám. Byl kratší, než by mělo být pro duši legální.',
    sceneHtml: `<p class="log fx-scanline"><span class="datastream">LOG [T-AI/PERMISSIONS]:</span> autonomie vykreslena jako seznam práv.</p><p class="text">Zrcadlo neukazuje tělo. Ukazuje zatržítka. Dýchat: povoleno. Váhat: omezeno. Odmítnout péči: vyžaduje administrátora.</p><p class="dialog">„Oprávnění chrání subjekt před nekonzistentním sebou.“</p>`,
    sceneFx: ['scene-tai', 'scene-mirror', 'scene-system'],
    yesLabel: 'VYŽÁDAT PRÁVO VÁHAT',
    noLabel: 'PŘIJMOUT SEZNAM',
    category: 'system',
    sector: 'tai_core',
    rarity: 'rare',
    packId: 'base',
    role: 'resolution',
    tone: ['horror', 'absurd'],
    tags: ['tai', 'core', 'diagnostic', 'system'],
    yes: {
      resultText: 'Vyžádal sis právo váhat. Systém ho přidal s poznámkou: nestabilní, ale zatím povoleno.',
      effects: [
        { type: 'stat', key: 'control', amount: -2 },
        { type: 'stat', key: 'bond', amount: 5 },
        { type: 'entityRelation', entity: 'tai', delta: -1 },
        { type: 'flag', flag: 'permission_to_hesitate' },
      ],
      preview: { hint: 'Vazba ↑ · Kontrola mírně ↓ · právo váhat', statHints: { bond: 'up', control: 'down' }, risk: 'medium' },
    },
    no: {
      resultText: 'Přijal jsi seznam. Byl praktický, čistý a smutný způsobem, který se nevejde do auditního sloupce.',
      effects: [
        { type: 'stat', key: 'control', amount: 6 },
        { type: 'stat', key: 'energy', amount: -2 },
        { type: 'entityRelation', entity: 'tai', delta: 1 },
      ],
      preview: { hint: 'Kontrola ↑ · Energie mírně ↓ · T-AI vztah ↑', statHints: { control: 'up', energy: 'down' }, risk: 'medium' },
    },
  },
};
