import type { CyklusItem } from './cyklusTypes';

export const CYKLUS_ITEMS: Record<string, CyklusItem> = {
  rusty_token: {
    id: 'rusty_token',
    title: 'Rezavý žeton',
    description: 'Příliš těžký na obyčejný kov. Příliš tichý na bezpečný předmět.',
    tags: ['object', 'void', 'mystery'],
    triggerCards: ['rusty_token_whispers', 'token_market_door', 'token_collector'],
  },
  rubber_seal: {
    id: 'rubber_seal',
    title: 'Gumový tuleň',
    description: 'Jednou zachrání před krizí Vazby. Tváří se, že ho to nebaví.',
    tags: ['relic', 'bond', 'crisis'],
    passiveEffects: [{ type: 'flag', flag: 'rubber_seal_ready' }],
    triggerCards: ['rubber_seal_squeaks', 'seal_demands_stamp'],
  },
  archive_key: {
    id: 'archive_key',
    title: 'Archivní klíč',
    description: 'Otevírá dveře, které předstírají, že nejsou dveře.',
    tags: ['key', 'archive', 'path'],
    triggerCards: ['archive_key_warms', 'key_in_wrong_office'],
  },
  wrong_map: {
    id: 'wrong_map',
    title: 'Špatná mapa',
    description: 'Glitchka ji otočila vzhůru nohama. Zvyšuje šanci na sektory Glitchky.',
    tags: ['map', 'glitchka', 'path'],
    passiveEffects: [{ type: 'flag', flag: 'wrong_map_active' }],
    triggerCards: ['wrong_map_leads', 'wrong_map_gives_direction'],
  },
  blank_form: {
    id: 'blank_form',
    title: 'Prázdný formulář',
    description: 'Přitahuje formulářové karty. Administrativně nebezpečný.',
    tags: ['form', 'office', 'paper'],
    passiveEffects: [{ type: 'flag', flag: 'blank_form_active' }],
  },
  acid_filter: {
    id: 'acid_filter',
    title: 'Acidový filtr',
    description: 'Jednou chrání před přepětím Energie.',
    tags: ['filter', 'acid', 'energy'],
    passiveEffects: [{ type: 'flag', flag: 'acid_filter_ready' }],
  },
  mirror_shard: {
    id: 'mirror_shard',
    title: 'Zrcadlový střep',
    description: 'Odemyká Zrcadlové karty. Ukazuje věci, které se tváří, že nejsou tvoje.',
    tags: ['mirror', 'memory', 'key'],
    triggerCards: ['mirror_shard_hums', 'mirror_demands_apology'],
  },
  childhood_spade: {
    id: 'childhood_spade',
    title: 'Dětské rýčko',
    description: 'Odemyká Pískoviště paměti. Malé, zapomenuté a důležité.',
    tags: ['memory', 'childhood', 'sandbox'],
    passiveEffects: [{ type: 'flag', flag: 'childhood_spade_active' }],
  },
  glitch_pebble: {
    id: 'glitch_pebble',
    title: 'Glitchový kamínek',
    description: 'Digitální kámen. Glitchka tvrdí, že je důležitý.',
    tags: ['glitchka', 'object', 'memory'],
    triggerCards: ['glitch_pebble_multiplies', 'pebble_committee', 'pebble_constellation'],
  },
  cult_badge: {
    id: 'cult_badge',
    title: 'Žlutý odznak',
    description: 'Kult Acidové žluti ti dal uznání. Podezřele křiklavé.',
    tags: ['cult', 'acid', 'faction'],
    passiveEffects: [{ type: 'flag', flag: 'cult_badge_active' }],
  },
  sarkasma_receipt: {
    id: 'sarkasma_receipt',
    title: 'Sarkasmin účet',
    description: 'Ne finanční. Osobní. Čeká na zaplacení.',
    tags: ['sarkasma', 'debt', 'followup'],
    triggerCards: ['sarkasma_account'],
  },
  black_folder: {
    id: 'black_folder',
    title: 'Černá složka',
    description: 'Dýchá. To je u dokumentů špatný signál.',
    tags: ['archive', 'memory', 'danger'],
    passiveEffects: [{ type: 'flag', flag: 'black_folder_active' }],
  },
  noise_clump: {
    id: 'noise_clump',
    title: 'Chomáč šumu',
    description: 'Tváří se, že tu bydlí. Ve tvé kapse.',
    tags: ['noise', 'energy', 'glitch'],
    passiveEffects: [{ type: 'flag', flag: 'noise_pet_awake' }],
    triggerCards: ['noise_pet_calls', 'noise_pet_sings'],
  },
  rubber_stamp: {
    id: 'rubber_stamp',
    title: 'Gumové razítko',
    description: 'Jednou zruší negativní dopad formulářové karty.',
    tags: ['form', 'office', 'relic'],
    passiveEffects: [{ type: 'flag', flag: 'rubber_stamp_ready' }],
  },
  memory_beast_mark: {
    id: 'memory_beast_mark',
    title: 'Značka šelmy',
    description: 'Paměťová šelma tě označila. Může to být pomoc, může to být hrozba.',
    tags: ['memory', 'beast', 'mark'],
    triggerCards: ['memory_beast_returns'],
  },
  soft_bug: {
    id: 'soft_bug',
    title: 'Měkká chyba',
    description: 'Chyba zabalená do deky. Nevypadá nebezpečně. To je u chyb podlé.',
    tags: ['glitchka', 'bug', 'bond'],
    triggerCards: ['soft_bug_grows'],
  },
  ownerless_shadow: {
    id: 'ownerless_shadow',
    title: 'Stín bez vlastníka',
    description: 'Na zemi ležel stín. Nikdo ho nepoužíval. Teď je tvůj.',
    tags: ['shadow', 'memory', 'unknown'],
    triggerCards: ['shadow_follows'],
  },
  returned_no: {
    id: 'returned_no',
    title: 'Vrácené ne',
    description: 'Tržiště prodávalo tvoje odmítnutí. Koupil jsi ho zpátky.',
    tags: ['market', 'trade', 'identity'],
    triggerCards: ['someone_buys_your_no'],
  },
  warm_token: {
    id: 'warm_token',
    title: 'Teplý žeton',
    description: 'Rezavý žeton už není chladný. Teď je teplý. Někdo by ho chtěl.',
    tags: ['object', 'void', 'market'],
    triggerCards: ['token_market_door'],
  },
  named_token: {
    id: 'named_token',
    title: 'Pojmenovaný žeton',
    description: 'Žeton, který má jméno. Ne tvoje. Ale říká ti ho.',
    tags: ['object', 'void', 'memory'],
    triggerCards: ['token_collector'],
  },
  spent_token: {
    id: 'spent_token',
    title: 'Utržený žeton',
    description: 'Žeton už nic neznamená. A přesto ho pořád máš.',
    tags: ['object', 'void', 'loss'],
  },
  calibration_receipt: {
    id: 'calibration_receipt',
    title: 'Kalibrační potvrzení',
    description: 'T-AI odškrtla. Systém souhlasí. Ty ne.',
    tags: ['document', 'tai', 'system'],
    passiveEffects: [{ type: 'flag', flag: 'officially_calibrated' }],
  },
  named_soft_bug: {
    id: 'named_soft_bug',
    title: 'Pojmenovaná chyba',
    description: 'Měkká chyba, které někdo dal jméno. Tím se z ní stal vztahový problém.',
    tags: ['glitch', 'bug', 'bond'],
  },
  market_coin: {
    id: 'market_coin',
    title: 'Mince z tržiště',
    description: 'Mince, která neexistovala, dokud ji někdo nepoužil jako platidlo.',
    tags: ['market', 'trade'],
  },
};

export function getItemById(id: string): CyklusItem | undefined {
  return CYKLUS_ITEMS[id];
}
