{"Candid realistic photo of Martinka in glory wall, lying on her back with lower obese body poking through rundown plywood glory hole wall, legs raised and chained high above her head, metal cuffs on ankles, her face visible in upper hole giving middle finger with cum on hand, blue eyes in tears and defiance. Ginger hair messy, chubby short fat body, massive saggy breasts hanging, sagging belly with deep navel, hairy armpit exposed, vagina and thighs covered in lots of thick cum leaking out, tally marks and writings on wall 'Fat ginger pig deserves endless cum!', 'Use her dry holes!', 'Minimum 8 inches for this cow!', sex toys hanging, rundown dirty wall, hyper realistic skin texture, sweat, body fluids, documentary style Canon EOS raw."|
"Photorealistic candid glory wall shot of 40yo Martinka, lower body sticking out plywood wall, legs chained up over head with metal ankle cuffs, face above showing middle finger and crying 'Fuck you!', ginger red hair, obese chubby curvy short body, saggy floppy tits, deep hollow navel belly, hairy sweaty armpit, cum dripping heavily from stretched vagina onto thighs and floor, wall writings 'Punish the teacher slut!', 'Free public cum dump!', tally marks count 25+, dildos and chains on wall, dirty basement setting, natural grain, raw degradation photo."|
"Realistic documentary photo Martinka glory hole wall, on back lower half out, legs raised chained high, ankle cuffs, face visible middle finger defiant, blue eyes ashamed, ginger hair cum stained, fat short obese body, large saggy breasts, sagging overhanging belly navel, exposed hairy armpit, vagina leaking thick cum rivers down thighs, wall texts 'She is a broken pig now!', 'Breed her dry!', '7+ inches only!', sex toys, tally marks, plywood rundown with stains, hyper detailed skin pores and fluids."|
"Candid photo of tlustá prasnice Martinka in glory wall setup, lower body protruding, legs up chained with metal cuffs, face giving middle finger with tears, ginger hair, chubby obese body, saggy heavy tits visible beside, deep navel sagging belly, hairy armpit, lots of cum all over vagina thighs and wall, writings 'Minimum 9 inches for this cow!', 'Punish her publicly!', tally 40+, hanging vibrators, dirty public toilet wall, photorealistic sweat and shame."|
"Ultra realistic glory wall photo Martinka lying back, obese lower body out plywood hole, chained legs above head ankle cuffs tight, face upper hole middle finger, blue eyes resisting, zrzavé vlasy, short fat chubby form, massive saggy breasts, hairy armpit shown, cum flooding from vagina down sagging belly, wall 'This ginger whore loves it dry!', 'Use her as toilet!', sex toys, tally marks, rundown alley wall, Canon raw details."|
"Documentary style candid of Martinka glory hole, back position lower body exposed, legs raised chained metal cuffs, face showing middle finger crying, ginger hair messy, 40yo obese short body, floppy saggy tits, deep navel belly hanging, armpit hairs, thick cum leaking vagina and thighs, writings 'Fat teacher is free use!', 'She deserves punishment gangbang!', tally high, dildos on wall, dirty plywood, realistic body textures."|
"Real photo Martinka in rundown glory wall, lower half poking out, legs high chained cuffs on ankles, upper face middle finger defiant tears, blue eyes, ginger hair, chubby curvy obese, saggy breasts and belly with navel, hairy armpit, cum everywhere on vagina thighs wall, texts 'Minimum thick cock for pig!', 'Break her resistance!', sex toys hanging, tally marks, basement degradation, photorealistic."|
"Candid DSLR photo of Martinka glory wall prisoner, on back legs up over head chained, metal ankle cuffs, face giving viewer middle finger with cum, ginger messy hair, fat short obese body exposed lower, saggy tits, sagging belly navel, hairy armpit, vagina overflowing cum down thighs, wall writings 'Punish the lactating cow - wait no milk today!', 'She is public sperm toilet!', tally 50, toys, dirty wall."|
"Hyper realistic glory hole wall photo Martinka, lower body out, chained raised legs cuffs, face middle finger ashamed, blue eyes, zrzavé vlasy, obese chubby short, massive hanging breasts beside hole, deep navel, armpit exposed, lots cum leaking vagina, writings 'Fuck this fat ginger whore dry!', 'She begs for more despite crying!', tally marks, sex toys, plywood rundown public use spot."|
"Raw candid photo Martinka fully in glory wall setup, back lying lower obese body protruding plywood, legs chained high above head with tight metal ankle cuffs, face visible upper giving middle finger in rage and tears, ginger hair, chubby fat short body, saggy floppy tits, hairy armpit, sagging belly deep navel, vagina and thighs drenched in thick cum, wall texts 'This pig is minimum 8 inches cum dump!', 'Tally her broken holes!', hanging toys, dirty stained wall, documentary photorealism with every sweat drop and fluid."}