import type { CyklusItem } from './cyklusTypes';

export const CYKLUS_ITEMS: Record<string, CyklusItem> = {
  rusty_token: {
    id: 'rusty_token',
    title: 'Rezavý žeton',
    description: 'Příliš těžký na obyčejný kov. Příliš tichý na bezpečný předmět. Když ho držíš dlouho, připomíná ti drobný dluh vůči někomu, kdo ještě nemá tvář.',
    tags: ['object', 'void', 'mystery', 'token'],
    triggerCards: ['rusty_token_whispers', 'token_market_door', 'token_collector'],
    resonance: {
      poolIds: ['token_market_pool', 'market_pool', 'toll_dvanactnik_pool'],
      aliases: ['rusty_token', 'token', 'market', 'debt', 'name', 'coin'],
      favoriteSectors: ['market', 'void'],
      stabilizes: ['memory'],
      destabilizes: ['control'],
    },
  },
  rubber_seal: {
    id: 'rubber_seal',
    title: 'Gumový tuleň',
    description: 'Jednou zachrání před krizí Vazby. Tváří se, že ho to nebaví. Což je fér, málokterý kancelářský save point si vybral život hrdiny.',
    tags: ['relic', 'bond', 'crisis', 'seal'],
    passiveEffects: [{ type: 'flag', flag: 'rubber_seal_ready' }],
    triggerCards: ['rubber_seal_squeaks', 'seal_demands_stamp'],
    resonance: {
      poolIds: ['sealarium_pool', 'seal_aftermath', 'glitchka_pool'],
      aliases: ['rubber_seal', 'seal', 'sealarium', 'crisis', 'save', 'bond', 'stamp'],
      favoriteSectors: ['memory_sandbox', 'glitchka_nest', 'form_office'],
      stabilizes: ['bond'],
      entity: 'glitchka',
    },
  },
  archive_key: {
    id: 'archive_key',
    title: 'Archivní klíč',
    description: 'Otevírá dveře, které předstírají, že nejsou dveře. Má v sobě klid úředníka, který ví, kde je tvoje složka.',
    tags: ['key', 'archive', 'path'],
    triggerCards: ['archive_key_warms', 'key_in_wrong_office'],
    resonance: {
      poolIds: ['archive_pool', 'archive_forbidden_pool', 'detective_echo_case_pool'],
      aliases: ['archive_key', 'key', 'archive', 'drawer', 'door', 'case', 'memory'],
      favoriteSectors: ['archive', 'form_office'],
      stabilizes: ['memory'],
      destabilizes: ['energy'],
      entity: 'archive',
    },
  },
  wrong_map: {
    id: 'wrong_map',
    title: 'Špatná mapa',
    description: 'Glitchka ji otočila vzhůru nohama. Zvyšuje šanci na sektory Glitchky. Její největší problém je, že někdy lže pravdivěji než navigace.',
    tags: ['map', 'glitchka', 'path', 'wrong_name'],
    passiveEffects: [{ type: 'flag', flag: 'wrong_map_active' }],
    triggerCards: ['wrong_map_leads', 'wrong_map_gives_direction'],
    resonance: {
      poolIds: ['glitchka_pool', 'memory_sandbox_pool', 'wrong_name_pool'],
      aliases: ['wrong_map', 'map', 'path', 'glitchka', 'wrong_name', 'side_door'],
      favoriteSectors: ['glitchka_nest', 'memory_sandbox', 'residuum'],
      stabilizes: ['bond'],
      destabilizes: ['control'],
      entity: 'glitchka',
    },
  },
  blank_form: {
    id: 'blank_form',
    title: 'Prázdný formulář',
    description: 'Přitahuje formulářové karty. Administrativně nebezpečný. Nejhorší na prázdném formuláři je, že vypadá nevinně, dokud nezačne očekávat duši v kolonce 4b.',
    tags: ['form', 'office', 'paper', 'signature'],
    passiveEffects: [{ type: 'flag', flag: 'blank_form_active' }],
    resonance: {
      poolIds: ['form_office_pool', 'wrong_name_pool', 'audit_cards'],
      aliases: ['blank_form', 'form', 'office', 'signature', 'audit', 'paper'],
      favoriteSectors: ['form_office'],
      stabilizes: ['control'],
      destabilizes: ['bond'],
      entity: 'form',
    },
  },
  acid_filter: {
    id: 'acid_filter',
    title: 'Acidový filtr',
    description: 'Jednou chrání před přepětím Energie. Páchne po citrónu, ozónu a špatném rozhodnutí, které ještě nezačalo hořet.',
    tags: ['filter', 'acid', 'energy', 'overclock'],
    passiveEffects: [{ type: 'flag', flag: 'acid_filter_ready' }],
    resonance: {
      poolIds: ['acid_pool', 'acid_aftermath', 'overburn'],
      aliases: ['acid_filter', 'filter', 'acid', 'energy', 'overclock', 'overburn'],
      favoriteSectors: ['acid_yellow'],
      stabilizes: ['energy'],
      destabilizes: ['control'],
      entity: 'cult',
    },
  },
  mirror_shard: {
    id: 'mirror_shard',
    title: 'Zrcadlový střep',
    description: 'Odemyká Zrcadlové karty. Ukazuje věci, které se tváří, že nejsou tvoje. Střep je malý, ale má ambice celého soudního procesu.',
    tags: ['mirror', 'memory', 'key', 'identity'],
    triggerCards: ['mirror_shard_hums', 'mirror_demands_apology'],
    resonance: {
      poolIds: ['mirror_pool', 'shadow_pool', 'shattered_mirror_aftermath'],
      aliases: ['mirror_shard', 'mirror', 'reflection', 'shadow', 'identity', 'apology'],
      favoriteSectors: ['mirror', 'residuum'],
      stabilizes: ['memory'],
      destabilizes: ['bond'],
      entity: 'shadow',
    },
  },
  childhood_spade: {
    id: 'childhood_spade',
    title: 'Lopatka',
    description: 'Odemyká Pískoviště paměti. Malé, zapomenuté a důležité. Umí hrabat v písku i ve věcech, které by dospělí raději nazvali vývojem osobnosti.',
    tags: ['memory', 'childhood', 'sandbox', 'safe_mistake'],
    passiveEffects: [{ type: 'flag', flag: 'childhood_spade_active' }],
    resonance: {
      poolIds: ['memory_sandbox_pool', 'sandbox_absurd_pool', 'sandbox_aftermath_pool'],
      aliases: ['childhood_spade', 'spade', 'sandbox', 'childhood', 'safe_mistake', 'play'],
      favoriteSectors: ['memory_sandbox', 'glitchka_nest'],
      stabilizes: ['bond', 'memory'],
      entity: 'glitchka',
    },
  },
  glitch_pebble: {
    id: 'glitch_pebble',
    title: 'Glitchový kamínek',
    description: 'Digitální kámen. Glitchka tvrdí, že je důležitý. Kamínek s tím souhlasí mlčením, což je v SYNTHOMĚ skoro argument.',
    tags: ['glitchka', 'object', 'memory', 'pebble'],
    triggerCards: ['glitch_pebble_multiplies', 'pebble_committee', 'pebble_constellation'],
    resonance: {
      poolIds: ['glitchka_pool', 'glitch_pool', 'memory_sandbox_pool'],
      aliases: ['glitch_pebble', 'pebble', 'glitchka', 'glitch', 'constellation', 'committee'],
      favoriteSectors: ['glitchka_nest', 'memory_sandbox'],
      stabilizes: ['bond'],
      destabilizes: ['control'],
      entity: 'glitchka',
    },
  },
  cult_badge: {
    id: 'cult_badge',
    title: 'Žlutý odznak',
    description: 'Kult Acidové žluti ti dal uznání. Podezřele křiklavé. Odznak vypadá, že by ti prodal spásu ve třech splátkách a jedné migréně.',
    tags: ['cult', 'acid', 'faction', 'yellow'],
    passiveEffects: [{ type: 'flag', flag: 'cult_badge_active' }],
    resonance: {
      poolIds: ['acid_pool', 'acid_aftermath', 'overclock'],
      aliases: ['cult_badge', 'cult', 'acid', 'yellow', 'restart', 'overclock'],
      favoriteSectors: ['acid_yellow'],
      stabilizes: ['energy'],
      destabilizes: ['memory', 'control'],
      entity: 'cult',
    },
  },
  sarkasma_receipt: {
    id: 'sarkasma_receipt',
    title: 'Sarkasmin účet',
    description: 'Ne finanční. Osobní. Čeká na zaplacení. Papír nešustí, spíš si brousí hrany.',
    tags: ['sarkasma', 'debt', 'followup', 'receipt'],
    triggerCards: ['sarkasma_account'],
    resonance: {
      poolIds: ['sarkasma_debt_pool', 'sarkasma_pool', 'sarkasma_aftercare_pool'],
      aliases: ['sarkasma_receipt', 'receipt', 'sarkasma', 'debt', 'invoice', 'scalpel'],
      favoriteSectors: ['sarkasma_terminal'],
      stabilizes: ['control'],
      destabilizes: ['energy'],
      entity: 'sarkasma',
    },
  },
  black_folder: {
    id: 'black_folder',
    title: 'Černá složka',
    description: 'Dýchá. To je u dokumentů špatný signál. Její hřbet je popsaný písmem, které vypadá jako poznámka z porady po apokalypse.',
    tags: ['archive', 'memory', 'danger', 'blackbox'],
    passiveEffects: [{ type: 'flag', flag: 'black_folder_active' }],
    resonance: {
      poolIds: ['archive_forbidden_pool', 'blackbox_aftermath_pool', 'brutal_blackbox_pool'],
      aliases: ['black_folder', 'folder', 'blackbox', 'archive', 'forbidden', 'anonymization'],
      favoriteSectors: ['archive', 'tai_core'],
      stabilizes: ['memory'],
      destabilizes: ['control'],
      entity: 'archive',
    },
  },
  noise_clump: {
    id: 'noise_clump',
    title: 'Chomáč šumu',
    description: 'Tváří se, že tu bydlí. Ve tvé kapse. Nemá nájemní smlouvu, jen vibrující sebevědomí drobné katastrofy.',
    tags: ['noise', 'energy', 'glitch', 'pet'],
    passiveEffects: [{ type: 'flag', flag: 'noise_pet_awake' }],
    triggerCards: ['noise_pet_calls', 'noise_pet_sings'],
    resonance: {
      poolIds: ['noise_pool', 'glitch_pool', 'soft_bug_pool'],
      aliases: ['noise_clump', 'noise', 'noise_pet', 'glitch', 'pet', 'signal'],
      favoriteSectors: ['glitchka_nest', 'acid_yellow'],
      stabilizes: ['energy'],
      destabilizes: ['control'],
    },
  },
  rubber_stamp: {
    id: 'rubber_stamp',
    title: 'Gumové razítko',
    description: 'Jednou zruší negativní dopad formulářové karty. Vypadá jako maličkost, dokud nezjistíš, že autorita je často jen guma s inkoustem.',
    tags: ['form', 'office', 'relic', 'stamp'],
    passiveEffects: [{ type: 'flag', flag: 'rubber_stamp_ready' }],
    resonance: {
      poolIds: ['form_office_pool', 'sealarium_pool', 'audit_cards'],
      aliases: ['rubber_stamp', 'stamp', 'form', 'office', 'audit', 'seal'],
      favoriteSectors: ['form_office', 'market'],
      stabilizes: ['control'],
      destabilizes: ['memory'],
      entity: 'form',
    },
  },
  memory_beast_mark: {
    id: 'memory_beast_mark',
    title: 'Značka šelmy',
    description: 'Paměťová šelma tě označila. Může to být pomoc, může to být hrozba. Nejčastěji je to obojí, protože svět neumí vyplnit jednoduchý formulář.',
    tags: ['memory', 'beast', 'mark', 'selma'],
    triggerCards: ['memory_beast_returns'],
    resonance: {
      poolIds: ['memory_beast_pool', 'archive_pool', 'memory_flood'],
      aliases: ['memory_beast_mark', 'beast', 'mark', 'selma', 'memory', 'predator'],
      favoriteSectors: ['archive', 'residuum'],
      stabilizes: ['memory'],
      destabilizes: ['energy'],
      entity: 'selma',
    },
  },
  soft_bug: {
    id: 'soft_bug',
    title: 'Měkká chyba',
    description: 'Chyba zabalená do deky. Nevypadá nebezpečně. To je u chyb podlé. Dýchá tak tiše, až to zní jako past v pyžamu.',
    tags: ['glitchka', 'bug', 'bond', 'soft_error'],
    triggerCards: ['soft_bug_grows'],
    resonance: {
      poolIds: ['soft_bug_pool', 'glitchka_pool', 'sandbox_aftermath_pool'],
      aliases: ['soft_bug', 'named_soft_bug', 'bug', 'soft_error', 'glitchka', 'blanket'],
      favoriteSectors: ['glitchka_nest', 'memory_sandbox'],
      stabilizes: ['bond'],
      destabilizes: ['control'],
      entity: 'glitchka',
    },
  },
  ownerless_shadow: {
    id: 'ownerless_shadow',
    title: 'Stín bez vlastníka',
    description: 'Na zemi ležel stín. Nikdo ho nepoužíval. Teď je tvůj. Což je přesně ten druh věty, po které normální člověk zavře dveře.',
    tags: ['shadow', 'memory', 'unknown', 'mirror'],
    triggerCards: ['shadow_follows'],
    resonance: {
      poolIds: ['shadow_pool', 'mirror_pool', 'shattered_mirror_aftermath'],
      aliases: ['ownerless_shadow', 'shadow', 'mirror', 'unknown', 'follows'],
      favoriteSectors: ['mirror', 'residuum'],
      stabilizes: ['control'],
      destabilizes: ['bond'],
      entity: 'shadow',
    },
  },
  returned_no: {
    id: 'returned_no',
    title: 'Vrácené ne',
    description: 'Tržiště prodávalo tvoje odmítnutí. Koupil jsi ho zpátky. Teď má účtenku, pach cizích rukou a mnohem pevnější záda.',
    tags: ['market', 'trade', 'identity', 'boundary'],
    triggerCards: ['someone_buys_your_no'],
    resonance: {
      poolIds: ['market_sells_no_pool', 'market_pool', 'desire_aftercare_pool'],
      aliases: ['returned_no', 'no', 'boundary', 'market', 'trade', 'refusal'],
      favoriteSectors: ['market', 'residuum'],
      stabilizes: ['control', 'bond'],
      entity: 'residuum',
    },
  },
  warm_token: {
    id: 'warm_token',
    title: 'Teplý žeton',
    description: 'Rezavý žeton už není chladný. Teď je teplý. Někdo by ho chtěl. A předměty, které někdo chce, se v SYNTHOMĚ rychle naučí být drahé.',
    tags: ['object', 'void', 'market', 'token'],
    triggerCards: ['token_market_door'],
    resonance: {
      poolIds: ['token_market_pool', 'market_pool', 'toll_dvanactnik_pool'],
      aliases: ['warm_token', 'token', 'market', 'toll', 'debt', 'coin'],
      favoriteSectors: ['market'],
      stabilizes: ['energy'],
      destabilizes: ['memory'],
    },
  },
  named_token: {
    id: 'named_token',
    title: 'Pojmenovaný žeton',
    description: 'Žeton, který má jméno. Ne tvoje. Ale říká ti ho. To by bylo dojemné, kdyby pojmenování nebylo v SYNTHOMĚ první krok k vymáhání.',
    tags: ['object', 'void', 'memory', 'token', 'name'],
    triggerCards: ['token_collector'],
    resonance: {
      poolIds: ['token_market_pool', 'wrong_name_pool', 'market_pool'],
      aliases: ['named_token', 'token', 'name', 'wrong_name', 'collector', 'market'],
      favoriteSectors: ['market', 'residuum'],
      stabilizes: ['memory'],
      destabilizes: ['bond'],
    },
  },
  spent_token: {
    id: 'spent_token',
    title: 'Utržený žeton',
    description: 'Žeton už nic neznamená. A přesto ho pořád máš. Nejhorší relikvie jsou ty, které přežily vlastní smysl.',
    tags: ['object', 'void', 'loss', 'token'],
    resonance: {
      poolIds: ['token_market_pool', 'toll_debt_pool', 'post_format'],
      aliases: ['spent_token', 'token', 'loss', 'spent', 'debt', 'empty'],
      favoriteSectors: ['void', 'market'],
      stabilizes: ['control'],
      destabilizes: ['memory'],
    },
  },
  calibration_receipt: {
    id: 'calibration_receipt',
    title: 'Kalibrační potvrzení',
    description: 'T-AI odškrtla. Systém souhlasí. Ty ne. Papír voní po bezpečí, což je většinou jen hezčí název pro dohled.',
    tags: ['document', 'tai', 'system', 'calibration'],
    passiveEffects: [{ type: 'flag', flag: 'officially_calibrated' }],
    resonance: {
      poolIds: ['crystal_cards', 'audit_cards'],
      aliases: ['calibration_receipt', 'calibration', 'tai', 'system', 'audit', 'control'],
      favoriteSectors: ['tai_core', 'form_office'],
      stabilizes: ['control'],
      destabilizes: ['bond'],
      entity: 'tai',
    },
  },
  named_soft_bug: {
    id: 'named_soft_bug',
    title: 'Pojmenovaná chyba',
    description: 'Měkká chyba, které někdo dal jméno. Tím se z ní stal vztahový problém. Gratulujeme, bug má teď sociální dopady.',
    tags: ['glitch', 'bug', 'bond', 'name'],
    resonance: {
      poolIds: ['soft_bug_pool', 'glitchka_deeper_chat_pool', 'relationship_followups'],
      aliases: ['named_soft_bug', 'soft_bug', 'bug', 'name', 'relationship', 'glitchka'],
      favoriteSectors: ['glitchka_nest', 'memory_sandbox'],
      stabilizes: ['bond'],
      destabilizes: ['control'],
      entity: 'glitchka',
    },
  },
  market_coin: {
    id: 'market_coin',
    title: 'Mince z tržiště',
    description: 'Mince, která neexistovala, dokud ji někdo nepoužil jako platidlo. Od té chvíle je velmi přesvědčená o své hodnotě, což z ní dělá ekonomiku v malém.',
    tags: ['market', 'trade', 'coin'],
    resonance: {
      poolIds: ['market_pool', 'toll_dvanactnik_pool', 'toll_debt_pool'],
      aliases: ['market_coin', 'coin', 'market', 'trade', 'debt', 'toll'],
      favoriteSectors: ['market'],
      stabilizes: ['energy'],
      destabilizes: ['memory'],
    },
  },
};

export function getItemById(id: string): CyklusItem | undefined {
  return CYKLUS_ITEMS[id];
}
